import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function IsHumanismAReligionSubstitute() {
  return <Chapter title={["Is Humanism a Religion Substitute?"]}>


    <p><span className="dropCap">F</span>or many years before the Wright Brothers, people dreamed of flying with magic potions. There was nothing irrational about the <em>raw desire</em> to fly. There was nothing <em>tainted</em> about the wish to look down on a cloud from above. Only the “magic potions” part was irrational.</p>
    <p>Suppose you were to put me into an fMRI scanner, and take a movie of my brain’s activity levels, while I watched a space shuttle launch. (Wanting to visit space is not “realistic,” but it is an essentially lawful dream—one that can be fulfilled in a lawful universe.) The fMRI might—maybe, maybe not—resemble the f MRI of a devout Christian watching a nativity scene.</p>
    <p>Should an experimenter obtain this result, there’s a lot of people out there, both Christians and some atheists, who would gloat: “Ha, ha, space travel is your religion!”</p>
    <p>But that’s drawing the wrong category boundary. It’s like saying that, because some people once tried to fly by irrational means, no one should ever enjoy looking out of an airplane window on the clouds below.</p>
    <p>If a rocket launch is what it takes to give me a feeling of aesthetic transcendence, I do not see this as a <em>substitute</em> for religion. That is theomorphism—the viewpoint from gloating religionists who assume that everyone who <em>isn’t</em> religious has a hole in their mind that wants filling.</p>
    <p>Now, to be fair to the religionists, this is not <em>just</em> a gloating assumption. There <em>are</em> atheists who have religion-shaped holes in their minds. I <em>have</em> seen attempts to substitute atheism or even transhumanism for religion. And the result is invariably awful. Utterly awful. Absolutely abjectly awful.</p>
    <p>I call such efforts, “hymns to the nonexistence of God.”</p>
    <p>When someone sets out to write an atheistic hymn—“Hail, oh unintelligent universe,” blah, blah, blah—the result will, without exception, suck.</p>
    <p>Why? Because they’re being imitative. Because they have no motivation for writing the hymn <em>except</em> a vague feeling that since churches have hymns, they ought to have one too. And, on a purely artistic level, that puts them far beneath genuine religious art that is not an imitation of anything, but an original expression of emotion.</p>
    <p>Religious hymns were (often) written by people who <em>felt strongly</em> and <em>wrote honestly</em> and put serious effort into the prosody and imagery of their work— that’s what gives their work the grace that it possesses, of artistic integrity.</p>
    <p>So are atheists doomed to hymnlessness?</p>
    <p>There is an acid test of attempts at post-theism. The acid test is: “If religion had never existed among the human species—if we had <em>never made</em> the original mistake—would this song, this art, this ritual, this way of thinking, still make sense?”</p>
    <p>If humanity had never made the original mistake, there would be no hymns to the nonexistence of God. But there would still be marriages, so the notion of an atheistic marriage ceremony makes perfect sense—as long as you don’t suddenly launch into a lecture on how God doesn’t exist. Because, in a world where religion <em>never had</em> existed, nobody would interrupt a wedding to talk about the implausibility of a distant hypothetical concept. They’d talk about love, children, commitment, honesty, devotion, but who the heck would mention God?</p>
    <p>And, in a human world where religion <em>never had</em> existed, there would still be people who got tears in their eyes watching a space shuttle launch.</p>
    <p>Which is why, even if experiment shows that watching a shuttle launch makes “religion”-associated areas of my brain light up, associated with feelings of transcendence, I do not see that as a <em>substitute</em> for religion; I expect the same brain areas would light up, for the same reason, if I lived in a world where religion had never been invented.</p>
    <p>A good “atheistic hymn” is simply a song about anything worth singing about that doesn’t happen to be religious.</p>
    <p>Also, reversed stupidity is not intelligence. The world’s greatest idiot may say the Sun is shining, but that doesn’t make it dark out. The point is <em>not</em> to create a life that resembles religion as little as possible in every surface aspect—this is the same kind of thinking that inspires hymns to the nonexistence of God. If humanity had never made the original mistake, no one would be <em>trying to avoid</em> things that vaguely resembled religion. Believe accurately, then feel accordingly: If space launches actually exist, and watching a rocket rise makes you want to sing, then write the song, dammit.</p>
    <p>If I get tears in my eyes at a space shuttle launch, it doesn’t mean I’m trying to fill a hole left by religion—it means that my emotional energies, my <em>caring</em>, are bound into the real world.</p>
    <p>If God did speak plainly, and answer prayers reliably, God would just become one more boringly real thing, no more worth believing in than the postman. If God were real, it would destroy the inner uncertainty that brings forth outward fervor in compensation. And if everyone else believed God were real, it would destroy the specialness of being one of the elect.</p>
    <p>If you invest your emotional energy in space travel, you don’t have those vulnerabilities. I can see the Space Shuttle rise without losing the awe. Everyone else can believe that Space Shuttles are real, and it doesn’t make them any less special. I haven’t painted myself into the corner.</p>
    <p>The choice between God and humanity is not just a choice of drugs. Above all, humanity <em>actually exists</em>.</p>
  </Chapter>;
}