import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function MundaneMagic() {
  return <Chapter title={["Mundane Magic"]}>


    <p><span className="dropCap">I</span> think that part of the rationalist ethos is <em>binding yourself emotionally</em> to an absolutely lawful reductionistic universe—a universe containing no supernatural things such as souls or magic—and pouring all your hope and all your care into that merely real universe and its possibilities, without disappointment.</p>
    <p>There’s an old trick for combating dukkha where you make a list of things you’re grateful for, like a roof over your head.</p>
    <p>So why not make a list of abilities you have that would be amazingly cool <em>if they were magic</em>, or if only a few chosen individuals had them?</p>
    <p>For example, suppose that instead of one eye, you possessed a magical <em>second</em> eye embedded in your forehead. And this second eye enabled you to <em>see into the third dimension</em>—so that you could somehow tell <em>how far away</em> things were—where an ordinary eye would see only a two-dimensional shadow of the true world. Only the possessors of this ability can accurately aim the legendary distance-weapons that kill at ranges far beyond a sword, or use to their fullest potential the shells of ultrafast machinery called “cars.”</p>
    <p>“Binocular vision” would be too light a term for this ability. We’ll only appreciate it once it has a properly impressive name, like Mystic Eyes of Depth Perception.</p>
    <p>So here’s a list of some of my favorite magical powers:</p>
    <ul>
      <li><em>Vibratory Telepathy</em>. By transmitting invisible vibrations through the very air itself, two users of this ability can <em>share thoughts</em>. As a result, Vibratory Telepaths can form emotional bonds much deeper than those possible to other primates.</li>
      <li><em>Psychometric Tracery</em>. By tracing small fine lines on a surface, the Psychometric Tracer can leave impressions of emotions, history, knowledge, even the structure of other spells. This is a higher level than Vibratory Telepathy as a Psychometric Tracer can share the thoughts of long-dead Tracers who lived thousands of years earlier. By reading one Tracery and inscribing another simultaneously, Tracers can duplicate Tracings; and these replicated Tracings can even contain the detailed pattern of other spells and magics. Thus, the Tracers wield almost unimaginable power as magicians; but Tracers can get in trouble trying to use complicated Traceries that they could not have Traced themselves.</li>
      <li><em>Multidimensional Kinesis</em>. With simple, almost unthinking acts of will, the Kinetics can cause extraordinarily complex forces to flow through small tentacles and into any physical object within touching range—not just pushes, but combinations of pushes at many points that can effectively apply torques and twists. The Kinetic ability is far subtler than it first appears: they use it not only to wield existing objects with martial precision, but also to apply forces that sculpt objects into forms more suitable for Kinetic wielding. They even create tools that extend the power of their Kinesis and enable them to sculpt ever-finer and ever-more-complicated tools, a positive feedback loop fully as impressive as it sounds.</li>
      <li><em>The Eye</em>. The user of this ability can perceive infinitesimal traveling twists in the Force that binds matter—tiny vibrations, akin to the life-giving power of the Sun that falls on leaves, but far more subtle. A bearer of the Eye can sense objects far beyond the range of touch using the tiny disturbances they make in the Force. Mountains many days travel away can be known to them as if within arm’s reach. According to the bearers of the Eye, when night falls and sunlight fails, they can sense huge fusion fires burning at unthinkable distances—though no one else has any way of verifying this. Possession of a single Eye is said to make the bearer equivalent to royalty.</li>
    </ul>
    <p>And finally,</p>
    <ul>
      <li><p><em>The Ultimate Power</em>. The user of this ability contains a smaller, imperfect echo of the entire universe, enabling them to search out paths through probability to any desired future. If this sounds like a ridiculously powerful ability, you’re right—game balance goes right out the window with this one. Extremely rare among life forms, it is the <em>sekai no ougi</em> or “hidden technique of the world.”</p></li>
      <li><p>Nothing can oppose the Ultimate Power except the Ultimate Power. Any less-than-ultimate Power will simply be “comprehended” by the Ultimate and disrupted in some inconceivable fashion, or even absorbed into the Ultimates’ own power base. For this reason the Ultimate Power is sometimes called the “master technique of techniques” or the “trump card that trumps all other trumps.” The more powerful Ultimates can stretch their “comprehension” across galactic distances and aeons of time, and even perceive the bizarre laws of the hidden “world beneath the world.”</p></li>
      <li><p>Ultimates have been killed by immense natural catastrophes, or by extremely swift surprise attacks that give them no chance to use their power. But all such victories are ultimately a matter of luck—it does not confront the Ultimates on their own probability-bending level, and if they survive they will begin to bend Time to avoid future attacks.</p></li>
      <li><p>But the Ultimate Power itself is also dangerous, and many Ultimates have been destroyed by their own powers—falling into one of the flaws in their imperfect inner echo of the world.</p></li>
      <li><p>Stripped of weapons and armor and locked in a cell, an Ultimate is still one of the most dangerous life-forms on the planet. A sword can be broken and a limb can be cut off, but the Ultimate Power is “the power that cannot be removed without removing you.”</p></li>
      <li><p>Perhaps because this connection is so intimate, the Ultimates regard one who loses their Ultimate Power permanently—without hope of regaining it—as <em>schiavo</em>, or “dead while breathing.” The Ultimates argue that the Ultimate Power is so important as to be a necessary part of what makes a creature an end in itself, rather than a means. The Ultimates even insist that anyone who lacks the Ultimate Power cannot begin to truly comprehend the Ultimate Power, and hence, cannot understand why the Ultimate Power is morally important—a suspiciously self-serving argument.</p></li>
      <li><p>The users of this ability form an absolute aristocracy and treat all other life forms as their pawns.</p></li>
    </ul>
  </Chapter>;
}