import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function Scarcity() {
  return <Chapter title={["Scarcity"]}>

    <p><span className="dropCap">W</span>hat follows is taken primarily from Robert Cialdini’s <em>Influence: The Psychology of Persuasion</em>.<span class="footnote">Robert B. Cialdini, <em>Influence: The Psychology of Persuasion: Revised Edition</em> (New York: Quill, 1993). </span> I own three copies of this book: one for myself, and two for loaning to friends.</p>
    <p><em>Scarcity</em>, as that term is used in social psychology, is when things become <em>more desirable</em> as they appear <em>less obtainable</em>.</p>
    <ul>
      <li>If you put a two-year-old boy in a room with two toys, one toy in the open and the other behind a Plexiglas wall, the two-year-old will ignore the easily accessible toy and go after the apparently forbidden one. If the wall is low enough to be easily climbable, the toddler is no more likely to go after one toy than the other.<span class="footnote">Sharon S. Brehm and Marsha Weintraub, “Physical Barriers and Psychological Reactance: Two-year-olds’ Responses to Threats to Freedom,” <em>Journal of Personality and Social Psychology</em> 35 (1977): 830–836.</span></li>
      <li>When Dade County forbade use or possession of phosphate detergents, many Dade residents drove to nearby counties and bought huge amounts of phosphate laundry detergents. Compared to Tampa residents not affected by the regulation, Dade residents rated phosphate detergents as gentler, more effective, more powerful on stains, and even believed that phosphate detergents poured more easily.<span class="footnote">Michael B. Mazis, Robert B. Settle, and Dennis C. Leslie, “Elimination of Phosphate Detergents and Psychological Reactance,” <em>Journal of Marketing Research</em> 10 (1973): 2; Michael B. Mazis, “Antipollution Measures and Psychological Reactance Theory: A Field Experiment,” <em>Journal of Personality and Social Psychology</em> 31 (1975): 654–666.</span></li>
    </ul>
    <p>Similarly, information that appears forbidden or secret seems more important and trustworthy:</p>
    <ul>
      <li>When University of North Carolina students learned that a speech opposing coed dorms had been banned, they became more opposed to coed dorms (without even hearing the speech).<span class="footnote">Richard D. Ashmore, Vasantha Ramchandra, and Russell A. Jones, “Censorship as an Attitude Change Induction,” <em>Paper presented at Eastern Psychological Association meeting</em> (1971).</span></li>
      <li>When a driver said he had liability insurance, experimental jurors awarded his victim an average of four thousand dollars more than if the driver said he had no insurance. If the judge afterward informed the jurors that information about insurance was inadmissible and must be ignored, jurors awarded an average of thirteen thousand dollars more than if the driver had no insurance.<span class="footnote">Dale Broeder, “The University of Chicago Jury Project,” <em>Nebraska Law Review</em> 38 (1959): 760–774.</span></li>
      <li>Buyers for supermarkets, told by a supplier that beef was in scarce supply, gave orders for twice as much beef as buyers told it was readily available. Buyers told that beef was in scarce supply, and furthermore, that the information about scarcity was itself scarce—that the shortage was not general knowledge—ordered six times as much beef. (Since the study was conducted in a real-world context, the information provided was in fact correct.)<span class="footnote">A. Knishinsky, “The Effects of Scarcity of Material and Exclusivity of Information on Industrial Buyer Perceived Risk in Provoking a Purchase Decision” (Doctoral dissertation, Arizona State University, 1982).</span></li>
    </ul>
    <p>The conventional theory for explaining this is “psychological reactance,” socialpsychology-speak for “When you tell people they can’t do something, they’ll just try even harder.” The fundamental instincts involved appear to be preservation of status and preservation of options. We resist dominance, when any human agency tries to restrict our freedom. And when options seem to be in danger of disappearing, even from natural causes, we try to leap on the option before it’s gone.</p>
    <p>Leaping on disappearing options may be a good adaptation in a hunter-gatherer society—gather the fruits while they are still ripe—but in a money-based society it can be rather costly. Cialdini reports that in one appliance store he observed, a salesperson who saw that a customer was evincing signs of interest in an appliance would approach, and sadly inform the customer that the item was out of stock, the last one having been sold only twenty minutes ago. Scarcity creating a sudden jump in desirability, the customer would often ask whether there was any chance that the salesperson could locate an unsold item in the back room, warehouse, or anywhere. “Well,” says the salesperson, “that’s possible, and I’m willing to check; but do I understand that this is the model you want, and if I can find it at this price, you’ll take it?”</p>
    <p>As Cialdini remarks, a chief sign of this malfunction is that you dream of <em>possessing</em> something, rather than <em>using</em> it. (Timothy Ferriss offers similar advice on planning your life: ask which <em>ongoing experiences</em> would make you happy, rather than which possessions or status-changes.)</p>
    <p>But the really fundamental problem with desiring the unattainable is that as soon as you actually get it, it stops being unattainable. If we cannot take joy in the merely available, our lives will always be frustrated…</p>
  </Chapter>;
}