import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function SearchingForBayesStructure() {
  return <Chapter title={["Searching for Bayes-Structure"]}>


    <blockquote>
      <p><em>Gnomish helms</em> should not function. Their very construction seems to defy the nature of thaumaturgical law. In fact, they are impossible. Like most products of gnomish minds, they include a large number of bells and whistles, and very little substance. Those that work usually have a <em>minor helm</em> contained within, always hidden away, disguised to appear innocuous and inessential.</p>
      <p>—<em>Spelljammer</em> campaign set</p>
    </blockquote>
    <p><span className="dropCap">W</span>e have seen that knowledge implies mutual information between a mind and its environment, and we have seen that this mutual information is negentropy in a very physical sense: If you know where molecules are and how fast they’re moving, you can turn heat into work via a Maxwell’s Demon / Szilárd engine.</p>
    <p>We have seen that forming true beliefs without evidence is the same sort of improbability as a hot glass of water spontaneously reorganizing into ice cubes and electricity. Rationality takes “work” in a thermodynamic sense, not just the sense of mental effort; minds have to radiate heat if they are not perfectly efficient. This cognitive work is governed by probability theory, of which thermodynamics is a special case. (Statistical mechanics is a special case of statistics.)</p>
    <p>If you saw a machine continually spinning a wheel, apparently without being plugged into a wall outlet or any other source of power, then you would look for a hidden battery, or a nearby broadcast power source—something to explain the work being done, without violating the laws of physics.</p>
    <p>So if a mind is arriving at true beliefs, and we assume that the Second Law of Thermodynamics has not been violated, that mind must be doing something at least <em>vaguely</em> Bayesian—at least one process with a sort-of Bayesian structure <em>somewhere</em>—or it <em>couldn’t possibly work</em>.</p>
    <p>In the beginning, at time <em>T</em> = 0, a mind has no mutual information with a subsystem <em>S</em> in its environment. At time <em>T</em> = 1, the mind has 10 bits of mutual information with <em>S</em>. Somewhere in between, the mind must have encountered evidence—under the Bayesian definition of evidence, because all Bayesian evidence is mutual information and all mutual information is Bayesian evidence, they are just different ways of looking at it—and processed at least some of that evidence, however inefficiently, in the right direction according to Bayes on at least some occasions. The mind must have <em>moved in harmony with the Bayes</em> at least a little, somewhere along the line—either that or violated the Second Law of Thermodynamics by creating mutual information from nothingness.</p>
    <p>In fact, any <em>part</em> of a cognitive process that <em>contributes usefully</em> to truth-finding must have at least a little Bayesian structure—must harmonize with Bayes, at some point or another—must partially conform with the Bayesian flow, however noisily—despite however many disguising bells and whistles— even if this Bayesian structure is only apparent in the context of surrounding processes. Or it couldn’t even <em>help</em>.</p>
    <p>How philosophers pondered the nature of words! All the ink spent on the true definitions of words, and the true meaning of definitions, and the true meaning of meaning! What collections of gears and wheels they built, in their explanations! And all along, it was a disguised form of Bayesian inference!</p>
    <p>I was actually a bit disappointed that no one in the audience jumped up and said: “<em>Yes! Yes, that’s it! Of course! It was really Bayes all along!</em>”</p>
    <p>But perhaps it is not <em>quite</em> as exciting to see something that <em>doesn’t</em> look Bayesian on the surface, revealed as Bayes wearing a clever disguise, if: (a) you don’t unravel the mystery yourself, but read about someone else doing it (Newton had more fun than most students taking calculus), and (b) you don’t realize that <em>searching for the hidden Bayes-structure</em> is this huge, difficult, omnipresent quest, like searching for the Holy Grail.</p>
    <p>It’s a different quest for each facet of cognition, but the Grail always <em>turns out</em> to be the same. It has to be the <em>right</em> Grail, though—and the <em>entire</em> Grail, without any parts missing—and so each time you have to go on the quest looking for a full answer <em>whatever</em> form it may take, rather than trying to artificially construct vaguely hand-waving Grailish arguments. <em>Then</em> you always find the same Holy Grail at the end.</p>
    <p>It was previously pointed out to me that I might be losing some of my readers with the long essays, because I hadn’t “made it clear where I was going”…</p>
    <p>… but it’s not so easy to just tell people where you’re going, when you’re going somewhere like <em>that</em>.</p>
    <p className="newpage">It’s not very helpful to merely <em>know that</em> a form of cognition is Bayesian, if you don’t <em>know how</em> it is Bayesian. If you can’t see the detailed flow of probability, you have nothing but a password—or, a bit more charitably, a hint at the form an answer would take; but certainly not an answer. That’s why there’s a Grand Quest for the Hidden Bayes-Structure, rather than being done when you say “Bayes!” Bayes-structure can be buried under all kinds of disguises, hidden behind thickets of wheels and gears, obscured by bells and whistles.</p>
    <p>The way you begin to grasp the Quest for the Holy Bayes is that you learn about cognitive phenomenon XYZ, which seems really useful—and there’s this bunch of philosophers who’ve been arguing about its true nature for centuries, and they are still arguing—and there’s a bunch of AI scientists trying to make a computer do it, but they can’t agree on the philosophy—</p>
    <p>And—<em>Huh, that’s odd!</em>—this cognitive phenomenon didn’t look anything like Bayesian on the surface, but there’s this non-obvious underlying structure that has a Bayesian interpretation—but wait, there’s still some useful work getting done that can’t be explained in Bayesian terms—no wait, <em>that’s</em> Bayesian too—Oh My God this <em>completely different</em> cognitive process, that <em>also</em> didn’t look Bayesian on the surface, also has Bayesian structure—hold on, are these non-Bayesian parts even <em>doing</em> anything?</p>
    <ul>
      <li><em>Yes:</em> Wow, those are Bayesian too!</li>
      <li><em>No:</em> Dear heavens, what a stupid design. I could eat a bucket of amino acids and puke a better brain architecture than that.</li>
    </ul>
    <p>Once this happens to you a few times, you kinda pick up the rhythm. That’s what I’m talking about here, the rhythm.</p>
    <p className="newpage">Trying to talk about the rhythm is like trying to dance about architecture.</p>
    <p>This left me in a bit of a pickle when it came to trying to explain in advance where I was going. I know from experience that if I say, “Bayes is the secret of the universe,” some people may say “Yes! Bayes is the secret of the universe!”; and others will snort and say, “How narrow-minded you are; look at all these other ad-hoc but amazingly useful methods, like regularized linear regression, that I have in my toolbox.”</p>
    <p>I hoped that with a specific example in hand of “something that doesn’t look all that Bayesian on the surface, but turns out to be Bayesian after all”—<em>and</em> an explanation of the difference between passwords and knowledge—<em>and</em> an explanation of the difference between tools and laws—maybe <em>then</em> I could convey such of the rhythm as can be understood without personally going on the quest.</p>
    <p>Of course this is not the <em>full</em> Secret of the Bayesian Conspiracy, but it’s all that I can convey at this point. Besides, the complete secret is known only to the Bayes Council, and if I told you, I’d have to hire you.</p>
    <p>To <em>see through</em> the surface adhockery of a cognitive process, to the Bayesian structure <em>underneath</em>—to perceive the probability flows, and <em>know how</em>, not just <em>know that</em>, this cognition too is Bayesian—as it always is—as it always must be—to be able to sense the Force underlying all cognition—this, is the Bayes-Sight.</p>
    <blockquote>
      <p>“… And the Queen of Kashfa sees with the Eye of the Serpent.”</p>
      <p>“I don’t know that she sees with it,” I said. “She’s still recovering from the operation. But that’s an interesting thought. If she could see with it, what might she behold?”</p>
      <p>“The clear, cold lines of eternity, I daresay. Beneath all Shadow.”</p>
      <p>—Roger Zelazny, <em>Prince of Chaos</em><span class="footnote">Roger Zelazny, <em>Prince of Chaos</em> (Thorndike Press, 2001).</span></p>
    </blockquote>
  </Chapter>;
}