import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function LotteriesAWasteOfHope() {
  return <Chapter title={["Lotteries: A Waste of Hope"]}>
    <p><span className="dropCap">T</span>he classic criticism of the lottery is that the people who play are the ones who can least afford to lose; that the lottery is a sink of money, draining wealth from those who most need it. Some lottery advocates, and even some commentors on <em>Overcoming Bias</em>, have tried to defend lottery-ticket buying as a <em>rational purchase of fantasy</em>—paying a dollar for a day’s worth of pleasant anticipation, imagining yourself as a millionaire.</p>
    <p>But consider exactly what this implies. It would mean that you’re occupying your valuable brain with a fantasy whose real probability is nearly zero—a tiny line of likelihood which you, yourself, can do nothing to realize. The lottery balls will decide your future. The fantasy is of wealth that arrives without effort—without conscientiousness, learning, charisma, or even patience.</p>
    <p>Which makes the lottery another kind of sink: a sink of emotional energy. It encourages people to invest their dreams, their hopes for a better future, into an infinitesimal probability. If not for the lottery, maybe they would fantasize about going to technical school, or opening their own business, or getting a promotion at work—things they might be able to actually <em>do</em>, hopes that would make them want to become stronger. Their dreaming brains might, in the 20th visualization of the pleasant fantasy, notice a way to really do it. Isn’t that what dreams and brains are <em>for</em>? But how can such reality-limited fare compete with the artificially sweetened prospect of instant wealth—not after herding a dot-com startup through to IPO, but on Tuesday?</p>
    <p>Seriously, why can’t we just say that buying lottery tickets is stupid? Human beings <em>are</em> stupid, from time to time—it shouldn’t be so surprising a hypothesis.</p>
    <p>Unsurprisingly, the human brain doesn’t do 64-bit floating-point arithmetic, and it can’t devalue the emotional force of a pleasant anticipation by a factor of 0.00000001 without dropping the line of reasoning entirely. Unsurprisingly, many people don’t realize that a numerical calculation of expected utility ought to <em>override</em> or <em>replace</em> their imprecise financial instincts, and instead treat the calculation as merely one <em>argument</em> to be balanced against their pleasant anticipations—an emotionally weak argument, since it’s made up of mere squiggles on paper, instead of visions of fabulous wealth.</p>
    <p>This seems sufficient to explain the popularity of lotteries. Why do so many arguers feel impelled to defend this classic form of self-destruction?</p>
    <p>The process of overcoming bias requires (1) first noticing the bias, (2) analyzing the bias in detail, (3) deciding that the bias is bad, (4) figuring out a workaround, and then (5) implementing it. It’s unfortunate how many people get through steps 1 and 2 and then bog down in step 3, which by rights should be the easiest of the five. Biases are lemons, not lemonade, and we shouldn’t try to make lemonade out of them—just burn those lemons <em>down</em>.</p>
  </Chapter>;
}