import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function NewImprovedLottery() {
  return <Chapter title={["New Improved Lottery"]}>
    <p><span className="dropCap tall">P</span>eople are&nbsp;still suggesting&nbsp;that the lottery is not a&nbsp;waste of hope, but a service which enables purchase of fantasy—“daydreaming&nbsp;about becoming a millionaire for much less money than daydreaming about hollywood stars in movies.” One&nbsp;commenter&nbsp;wrote: “There is a big difference between zero chance of becoming wealthy, and epsilon. Buying a ticket allows your dream of riches to bridge that gap.”</p>
    <p>Actually, one of the points I was trying to make is that between zero chance of becoming wealthy, and epsilon chance, there is an order-of-epsilon difference. If you doubt this, let epsilon equal one over googolplex.</p>
    <p>Anyway, if we pretend that the lottery sells epsilon hope, this suggests a design for a New Improved Lottery. The New Improved Lottery pays out every five years on average, at a random time—determined, say, by the decay of a not-very-radioactive element. You buy in once, for a single dollar, and get not just a few days of epsilon chance of becoming rich, but a few&nbsp;<em>years</em>&nbsp;of epsilon. Not only that, your wealth could strike at any time! At&nbsp;<em>any minute</em>, the phone could ring to inform you that&nbsp;<em>you, yes, you</em>&nbsp;are a millionaire!</p>
    <p>Think of how much better this would be than an ordinary lottery drawing, which only takes place at defined times, a few times per week. Let’s say the boss comes in and demands you rework a proposal, or restock inventory, or something similarly annoying. Instead of getting to work, you could turn to the phone and stare, hoping for that call—because there would be epsilon chance that,&nbsp;<em>at that exact moment, you yes you</em>&nbsp;would be awarded the Grand Prize! And even if it doesn’t happen&nbsp;<em>this</em>&nbsp;minute, why, there’s no need to be disappointed—it might happen the&nbsp;<em>next</em>&nbsp;minute!</p>
    <p>Think of how many more fantasies this New Improved Lottery would enable. You could shop at the store, adding expensive items to your shopping cart—if your cellphone doesn’t ring with news of a lottery win, you could always put the items back, right?</p>
    <p>Maybe the New Improved Lottery could even show a constantly fluctuating probability distribution over the likelihood of a win occurring, and the likelihood of particular numbers being selected, with the overall expectation working out to the aforesaid Poisson distribution. Think of how much fun&nbsp;<em>that</em>&nbsp;would be! Oh, goodness, right this minute the chance of a win occurring is nearly ten times higher than usual! And look, the number 42 that I selected for the Mega Ball has nearly twice the usual chance of winning! You could feed it to a display on people’s cellphones, so they could just flip open the cell-phone and see their chances of winning. Think of how exciting that would be! Much more exciting than trying to balance your checkbook! Much more exciting than doing your homework! This new dream would be&nbsp;so much tastier&nbsp;that it would compete with, not only hopes of going to technical school, but even hopes of getting home from work early. People could just stay glued to the screen all day long, why, they wouldn’t need to dream about anything else!</p>
    <p>Yep, offering people tempting daydreams&nbsp;<em>that will not actually happen</em>&nbsp;sure is a valuable service, all right. People are willing to pay; it must be valuable. The alternative is that consumers are making mistakes, and we all know that can’t happen.</p>
    <p>And yet current governments, with their vile monopoly on lotteries, don’t offer this simple and obvious service. Why? Because they want to overcharge people. They want them to spend money every week. They want them to spend a hundred dollars for the thrill of believing their chance of winning is a hundred times as large, instead of being able to stare at a cellphone screen waiting for the likelihood to spike. So if you believe that the lottery is a service, it is clearly an enormously overpriced service—charged to the poorest members of society—and it is your solemn duty as a citizen to demand the New Improved Lottery instead.</p>
  </Chapter>;
}