import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function TheFallacyOfGray() {
  return <Chapter title={["The Fallacy of Gray"]}>
    <blockquote>
      <p><span className="smallCaps">The Sophisticate:</span>&nbsp;“The world isn’t black and white. No one does pure good or pure bad. It’s all gray. Therefore, no one is better than anyone else.”</p>
      <p><span className="smallCaps">The Zetet:</span>&nbsp;“Knowing only gray, you conclude that all grays are the same shade. You mock the simplicity of the two-color view, yet you replace it with a one-color view . . .”</p>
      <p>—Marc Stiegler, David’s Sling<span className="footnote">Marc Stiegler,&nbsp;<em>David’s Sling</em>&nbsp;(Baen, 1988).</span></p>
    </blockquote>
    <p><span className="dropCap">I</span> don’t know if the Sophisticate’s mistake has an official name, but I call it the Fallacy of Gray. We saw it manifested in the previous essay—the one who believed that odds of two to the power of seven hundred and fifty millon to one, against, meant “there was still a chance.” All probabilities, to him, were simply “uncertain” and that meant he was licensed to ignore them if he pleased. “The Moon is made of green cheese” and “the Sun is made of mostly hydrogen and helium” are both uncertainties, but they are not the same uncertainty.</p>
    <p>Everything is shades of gray, but there are shades of gray so light as to be very nearly white, and shades of gray so dark as to be very nearly black. Or even if not, we can still compare shades, and say “it is darker” or “it is lighter.”</p>
    <p>Years ago, one of the strange little formative moments in my career as a rationalist was reading this paragraph from&nbsp;<em>Player of Games</em>&nbsp;by Iain M. Banks, especially the sentence in bold:<span className="footnote">Iain Banks,&nbsp;<em>The Player of Games</em>&nbsp;(Orbit, 1989).</span></p>
    <blockquote>
      <p>A guilty system recognizes no innocents. As with any power apparatus which thinks everybody’s either for it or against it, we’re against it. You would be too, if you thought about it. The very way you think places you amongst its enemies. This might not be your fault, because&nbsp;<strong>every society imposes some of its values on those raised within it, but the point is that some societies try to maximize that effect, and some try to minimize it</strong>. You come from one of the latter and you’re being asked to explain yourself to one of the former. Prevarication will be more difficult than you might imagine; neutrality is probably impossible. You cannot choose not to have the politics you do; they are not some separate set of entities somehow detachable from the rest of your being; they are a function of your existence. I know that and they know that; you had better accept it.</p>
    </blockquote>
    <p>Now, don’t write angry comments saying that, if societies impose fewer of their values, then each succeeding generation has more work to start over from scratch. That’s not what I got out of the paragraph.</p>
    <p>What I got out of the paragraph was something which seems so obvious in retrospect that I could have conceivably picked it up in a hundred places; but something about that one paragraph made it click for me.</p>
    <p>It was the whole notion of the Quantitative Way applied to life-problems like moral judgments and the quest for personal self-improvement. That, even if you couldn’t switch something from on to off, you could still tend to increase it or decrease it.</p>
    <p>Is this too obvious to be worth mentioning? I say it is not too obvious, for many bloggers have said of&nbsp;<em>Overcoming Bias</em>: “It is impossible, no one can completely eliminate bias.” I don’t care if the one is a professional economist, it is clear that they have not yet grokked the Quantitative Way as it applies to everyday life and matters like personal self-improvement. That which I cannot&nbsp;<em>eliminate</em>&nbsp;may be well worth&nbsp;<em>reducing</em>.</p>
    <p>Or consider this exchange between&nbsp;Robin Hanson&nbsp;and&nbsp;Tyler Cowen. Robin Hanson said that he preferred to put at least 75% weight on the prescriptions of economic theory versus his intuitions: “I try to mostly just straightforwardly apply economic theory, adding little personal or cultural judgment.” Tyler Cowen replied:</p>
    <blockquote>
      <p>In my view there is no such thing as “straightforwardly applying economic theory” … theories are always applied through our personal and cultural filters and there is no other way it can be.</p>
    </blockquote>
    <p>Yes, but you can try to minimize that effect, or you can do things that are bound to increase it. And&nbsp;<em>if</em>&nbsp;you try to minimize it, then in many cases I don’t think it’s unreasonable to call the output “straightforward”—even in economics.</p>
    <p>“Everyone is imperfect.” Mohandas Gandhi was imperfect and Joseph Stalin was imperfect, but they were not the same shade of imperfection. “Everyone is imperfect” is an excellent example of replacing a two-color view with a one-color view. If you say, “No one is perfect, but&nbsp;<em>some people are less imperfect than others</em>,” you may not gain&nbsp;applause; but for those who strive to&nbsp;do better, you have held out hope. No one is&nbsp;<em>perfectly</em>&nbsp;imperfect, after all.</p>
    <p>(Whenever someone says to me, “Perfectionism is bad for you,” I reply: “I think it’s okay to be imperfect, but not so imperfect that other people notice.”)</p>
    <p>Likewise the folly of those who say, “Every scientific paradigm imposes some of its assumptions on how it interprets experiments,” and then act like they’d proven science to occupy the same level with witchdoctoring. Every worldview imposes some of its structure on its observations, but the point is that there are worldviews which try to minimize that imposition, and worldviews which glory in it. There is no white, but there are shades of gray that are far lighter than others, and it is folly to treat them as if they were all on the same level.</p>
    <p>If the Moon has orbited the Earth these past few billion years, if you have seen it in the sky these last years, and you expect to see it in its appointed place and phase tomorrow, then that is not a certainty. And if you expect an&nbsp;invisible dragon&nbsp;to heal your daughter of cancer, that too is not a certainty. But they are rather different degrees of uncertainty—this business of expecting things to happen yet again in the same way you have previously predicted to twelve decimal places, versus expecting something to happen that&nbsp;<em>violates</em>&nbsp;the order previously observed. Calling them both “faith” seems a little too&nbsp;un-narrow.</p>
    <p>It’s a most peculiar psychology—this business of “Science is based on faith too, so there!” Typically this is said by people who claim that faith is a&nbsp;<em>good</em>&nbsp;thing. Then why do they say “Science is based on faith too!” in that angry-triumphal tone, rather than as a compliment? And a rather&nbsp;<em>dangerous</em>&nbsp;compliment to give, one would think, from their perspective. If science is based on “faith,” then science is of the same kind as religion—directly comparable. If science is a religion, it is the religion that heals the sick and reveals the secrets of the stars. It would make sense to say, “The priests of science can blatantly, publicly, verifiably walk on the Moon as a faith-based miracle, and your priests’ faith can’t do the same.” Are you sure you wish to go there, oh faithist? Perhaps, on further reflection, you would prefer to retract this whole business of “Science is a religion too!”</p>
    <p>There’s a strange dynamic here: You try to purify your shade of gray, and you get it to a point where it’s pretty light-toned, and someone stands up and says in a deeply offended tone, “But it’s not white! It’s gray!” It’s one thing when someone says, “This isn’t as light as you think, because of specific problems&nbsp;<em>X</em>, Y_,<em>&nbsp;and&nbsp;_Z</em>.” It’s a different matter when someone says angrily “It’s not white! It’s gray!” without pointing out any specific dark spots.</p>
    <p>In this case, I begin to suspect psychology that is more imperfect than usual—that someone may have made a devil’s bargain with their own mistakes, and now refuses to hear of any possibility of improvement. When someone finds an excuse not to try to do better, they often refuse to concede that anyone else can try to do better, and every mode of improvement is thereafter their enemy, and every claim that it is possible to move forward is an offense against them. And so they say in one breath proudly, “I’m glad to be gray,” and in the next breath angrily, “And&nbsp;<em>you’re gray too!</em>”</p>
    <p>If there is no black and white, there is yet lighter and darker, and not all grays are the same.</p>
    <p>G2&nbsp;points us to Asimov’s “The Relativity of Wrong”:<span className="footnote">Isaac Asimov,&nbsp;<em>The Relativity of Wrong</em>&nbsp;(Oxford University Press, 1989).</span></p>
    <blockquote>
      <p>When people thought the earth was flat, they were wrong. When people thought the earth was spherical, they were wrong. But if you think that thinking the earth is spherical is just as wrong as thinking the earth is flat, then your view is wronger than both of them put together.</p>
    </blockquote>

  </Chapter>;
}