import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function AnchoringAndAdjustment() {
  return <Chapter title={["Anchoring and", "Adjustment"]}>

    <p><span className="dropCap">S</span>uppose I spin a Wheel of Fortune device as you watch, and it comes up pointing to 65. Then I ask: Do you think the percentage of African countries in the UN is above or below this number? What do you think is the percentage of African countries in the UN? Take a moment to consider these two questions yourself, if you like, and please don’t Google.</p>
    <p>Also, try to guess, within <em>five seconds</em>, the value of the following arithmetical expression. Five seconds. Ready? Set… <em>Go!</em></p>
    <p>1 × 2 × 3 × 4 × 5 × 6 × 7 × 8</p>
    <p>Tversky and Kahneman recorded the estimates of subjects who saw the Wheel of Fortune showing various numbers.<span class="footnote">Amos Tversky and Daniel Kahneman, “Judgment Under Uncertainty: Heuristics and Biases,” <em>Science</em> 185, no. 4157 (1974): 1124–1131, doi:10.1126/science.185.4157.1124.</span>) The median estimate of subjects who saw the wheel show 65 was 45%; the median estimate of subjects who saw 10 was 25%.</p>
    <p>The current theory for this and similar experiments is that subjects take the initial, uninformative number as their starting point or <em>anchor</em>; and then they <em>adjust</em> upward or downward from their starting estimate until they reach an answer that “sounded plausible”; and then they stopp adjusting. This typically results in under-adjustment from the anchor—more distant numbers could also be “plausible,” but one stops at the first satisfying-sounding answer. Similarly, students shown “1 × 2 × 3 × 4 × 5 × 6 × 7 × 8” made a median estimate of 512, while students shown “8 × 7 × 6 × 5 × 4 × 3 × 2 × 1” made a median estimate of 2,250. The motivating hypothesis was that students would try to multiply (or guess-combine) the first few factors of the product, then adjust upward. In both cases the adjustments were insufficient, relative to the true value of 40,320; but the first set of guesses were much more insufficient because they started from a lower anchor.</p>
    <p>Tversky and Kahneman report that offering payoffs for accuracy did not reduce the anchoring effect.</p>
    <p>Strack and Mussweiler asked for the year Einstein first visited the United States.<span class="footnote">Fritz Strack and Thomas Mussweiler, “Explaining the Enigmatic Anchoring Effect: Mechanisms of Selective Accessibility,” <em>Journal of Personality and Social Psychology</em> 73, no. 3 (1997): 437–446.</span> Completely implausible anchors, such as 1215 or 1992, produced anchoring effects just as large as more plausible anchors such as 1905 or 1939.</p>
    <p>There are obvious applications in, say, salary negotiations, or buying a car. I won’t suggest that you exploit it, but watch out for exploiters.</p>
    <p>And watch yourself thinking, and try to notice when you are <em>adjusting</em> a figure in search of an estimate.</p>
    <p>Debiasing manipulations for anchoring have generally proved not very effective. I would suggest these two: First, if the initial guess sounds implausible, try to throw it away entirely and come up with a new estimate, rather than sliding from the anchor. But this in itself may not be sufficient—subjects instructed to avoid anchoring still seem to do so.<span class='footnote'>George A. Quattrone et al., “Explorations in Anchoring: The Effects of Prior Range, Anchor Extremity, and Suggestive Hints” (Unpublished manuscript, Stanford University, 1981).</span> So, second, even if you are trying the first method, try also to think of an anchor in the opposite direction—an anchor that is clearly too small or too large, instead of too large or too small—and dwell on it briefly.</p>
  </Chapter>;
}