import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function CachedThoughts() {
  return <Chapter title={["Cached Thoughts"]}>

    <p><span className="dropCap">O</span>ne of the single greatest puzzles about the human brain is how the damn thing works <em>at all</em> when most neurons fire 10–20 times per second, or 200Hz tops. In neurology, the “hundred-step rule” is that any postulated operation has to complete in <em>at most</em> 100 sequential steps—you can be as parallel as you like, but you can’t postulate more than 100 (preferably fewer) neural spikes one after the other.</p>
    <p>Can you imagine having to program using 100Hz CPUs, no matter how many of them you had? You’d also need a hundred billion processors just to get <em>anything</em> done in realtime.</p>
    <p>If you did need to write realtime programs for a hundred billion 100Hz processors, one trick you’d use as heavily as possible is caching. That’s when you store the results of previous operations and look them up next time, instead of recomputing them from scratch. And it’s a very <em>neural</em> idiom—recognition, association, completing the pattern.</p>
    <p>It’s a good guess that the actual <em>majority</em> of human cognition consists of cache lookups.</p>
    <p>This thought does tend to go through my mind at certain times.</p>
    <p>There was a wonderfully illustrative story which I thought I had bookmarked, but couldn’t re-find: it was the story of a man whose know-it-all neighbor had once claimed in passing that the best way to remove a chimney from your house was to knock out the fireplace, wait for the bricks to drop down one level, knock out those bricks, and repeat until the chimney was gone. Years later, when the man wanted to remove his own chimney, this cached thought was lurking, waiting to pounce…</p>
    <p>As the man noted afterward—you can guess it didn’t go well—his neighbor was not particularly knowledgeable in these matters, not a trusted source. If he’d <em>questioned</em> the idea, he probably would have realized it was a poor one. Some cache hits we’d be better off recomputing. But the brain completes the pattern automatically—and if you don’t consciously realize the pattern needs correction, you’ll be left with a completed pattern.</p>
    <p>I suspect that if the thought had occurred to the man himself—if he’d <em>personally</em> had this bright idea for how to remove a chimney—he would have examined the idea more critically. But if someone <em>else</em> has already thought an idea through, you can save on computing power by caching their <em>conclusion</em>—right?</p>
    <p>In modern civilization particularly, no one can think fast enough to think their own thoughts. If I’d been abandoned in the woods as an infant, raised by wolves or silent robots, I would scarcely be recognizable as human. No one can think fast enough to recapitulate the wisdom of a hunter-gatherer tribe in one lifetime, starting from scratch. As for the wisdom of a literate civilization, forget it.</p>
    <p>But the flip side of this is that I continually see people who aspire to critical thinking, repeating back cached thoughts which were not invented by critical thinkers.</p>
    <p>A good example is the skeptic who concedes, “Well, you can’t prove or disprove a religion by factual evidence.” As I have pointed out elsewhere, this is simply false as probability theory. And it is also simply false relative to the real psychology of religion—a few centuries ago, saying this would have gotten you burned at the stake. A mother whose daughter has cancer prays, “God, please heal my daughter,” not, “Dear God, I know that religions are not allowed to have any falsifiable consequences, which means that you can’t possibly heal my daughter, so… well, basically, I’m praying to make myself feel better, instead of doing something that could actually help my daughter.”</p>
    <p>But people read “You can’t prove or disprove a religion by factual evidence,” and then, the next time they see a piece of evidence disproving a religion, their brain completes the pattern. Even some atheists repeat this absurdity without hesitation. If they’d thought of the idea themselves, rather than hearing it from someone else, they would have been more skeptical.</p>
    <p>Death. Complete the pattern: “Death gives meaning to life.”</p>
    <p>It’s frustrating, talking to good and decent folk—people who would never in a thousand years <em>spontaneously</em> think of wiping out the human species—raising the topic of existential risk, and hearing them say, “Well, maybe the human species doesn’t deserve to survive.” They would never in a thousand years shoot their own child, who is a part of the human species, but the brain completes the pattern.</p>
    <p>What patterns are being completed, inside your mind, that you never chose to be there?</p>
    <p>Rationality. Complete the pattern: “Love isn’t rational.”</p>
    <p>If this idea had suddenly occurred to you personally, as an entirely new thought, how would you examine it critically? I know what <em>I</em> would say, but what would <em>you</em>? It can be hard to see with fresh eyes. Try to keep your mind from completing the pattern in the standard, unsurprising, already-known way. It may be that there is no better answer than the standard one, but you can’t <em>think</em> about the answer until you can stop your brain from filling in the answer automatically.</p>
    <p>Now that you’ve read this, the next time you hear someone unhesitatingly repeating a meme you think is silly or false, you’ll think, “Cached thoughts.” My belief is now there in your mind, waiting to complete the pattern. But is it true? Don’t let your mind complete the pattern! <em>Think!</em></p>
  </Chapter>;
}