import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function DoWeBelieveEverythingWereTold() {
  return <Chapter title={["Do We Believe", "Everything We're Told?"]}>

    <p><span className="dropCap">S</span>ome early experiments on anchoring and adjustment tested whether <em>distracting</em> the subjects—rendering subjects cognitively “busy” by asking them to keep a lookout for “5” in strings of numbers, or some such—would decrease adjustment, and hence increase the influence of anchors. Most of the experiments seemed to bear out the idea that cognitive busyness increased anchoring, and more generally contamination.</p>
    <p>Looking over the accumulating experimental results—more and more findings of contamination, exacerbated by cognitive busyness—Daniel Gilbert saw a truly crazy pattern emerging: Do we believe <em>everything</em> we’re told?</p>
    <p>One might naturally think that on being told a proposition, we would first <em>comprehend</em> what the proposition meant, then <em>consider</em> the proposition, and finally <em>accept</em> or <em>reject</em> it. This obvious-seeming model of cognitive process flow dates back to Descartes. But Descartes’s rival, Spinoza, disagreed; Spinoza suggested that we first <em>passively accept a proposition in the course of comprehending it</em>, and only afterward <em>actively disbelieve</em> propositions which are rejected by consideration.</p>
    <p>Over the last few centuries, philosophers pretty much went along with Descartes, since his view seemed more, y’know, logical and intuitive. But Gilbert saw a way of testing Descartes’s and Spinoza’s hypotheses experimentally.</p>
    <p>If Descartes is right, then distracting subjects should interfere with both accepting true statements and rejecting false statements. If Spinoza is right, then distracting subjects should cause them to remember false statements as being true, but should not cause them to remember true statements as being false.</p>
    <p>Gilbert, Krull, and Malone bear out this result, showing that, among subjects presented with novel statements labeled true or false, distraction had no effect on identifying true propositions (55% success for uninterrupted presentations, vs. 58% when interrupted); but did affect identifying false propositions (55% success when uninterrupted, vs. 35% when interrupted).<span class="footnote">Daniel T. Gilbert, Douglas S. Krull, and Patrick S. Malone, “Unbelieving the Unbelievable: Some Problems in the Rejection of False Information,” <em>Journal of Personality and Social Psychology</em> 59 (4 1990): 601–613, doi:10.1037/0022-3514.59.4.601.</span></p>
    <p>A much more dramatic illustration was produced in followup experiments by Gilbert, Tafarodi, and Malone.<span class="footnote">Gilbert, Tafarodi, and Malone, “You Can’t Not Believe Everything You Read.”</span> Subjects read aloud crime reports crawling across a video monitor, in which the color of the text indicated whether a particular statement was true or false. Some reports contained false statements that exacerbated the severity of the crime, other reports contained false statements that extenuated (excused) the crime. Some subjects also had to pay attention to strings of digits, looking for a “5,” while reading the crime reports—this being the distraction task to create cognitive busyness. Finally, subjects had to recommend the length of prison terms for each criminal, from 0 to 20 years.</p>
    <p>Subjects in the cognitively busy condition recommended an average of 11.15 years in prison for criminals in the “exacerbating” condition, that is, criminals whose reports contained labeled false statements exacerbating the severity of the crime. Busy subjects recommended an average of 5.83 years in prison for criminals whose reports contained labeled false statements excusing the crime. This nearly twofold difference was, as you might suspect, statistically significant.</p>
    <p>Non-busy participants read exactly the same reports, with the same labels, and the same strings of numbers occasionally crawling past, except that they did not have to search for the number “5.” Thus, they could devote more attention to “unbelieving” statements labeled false. These non-busy participants recommended 7.03 years versus 6.03 years for criminals whose reports falsely exacerbated or falsely excused.</p>
    <p>Gilbert, Tafarodi, and Malone’s paper was entitled “You Can’t Not Believe Everything You Read.”</p>
    <p>This suggests—to say the very least—that we should be more careful when we expose ourselves to unreliable information, especially if we’re doing something else at the time. Be careful when you glance at that newspaper in the supermarket.</p>
    <p>PS: According to an unverified rumor I just made up, people will be less skeptical of this essay because of the distracting color changes. <span class="footnote">Editor's Note: In the original version of this chapter, random sections of the text were various colors.</span></p>
  </Chapter>;
}