import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function PrimingAndContamination() {
  return <Chapter title={["Priming and", "Contamination"]}>

    <p><span className="dropCap">S</span>uppose you ask subjects to press one button if a string of letters forms a word, and another button if the string does not form a word (e.g., “banack” vs. “banner”). Then you show them the string “water.” Later, they will more quickly identify the string “drink” as a word. This is known as “cognitive priming”; this particular form would be “semantic priming” or “conceptual priming.”</p>
    <p>The fascinating thing about priming is that it occurs at such a low level— priming speeds up <em>identifying letters as forming a word</em>, which one would expect to take place <em>before</em> you deliberate on the word’s meaning.</p>
    <p>Priming also reveals the massive parallelism of spreading activation: if seeing “water” activates the word “drink,” it probably also activates “river,” or “cup,” or “splash”… and this activation spreads, from the semantic linkage of concepts, all the way back to recognizing strings of letters.</p>
    <p>Priming is subconscious and unstoppable, an artifact of the human neural architecture. Trying to stop yourself from priming is like trying to stop the spreading activation of your own neural circuits.</p>
    <p>In Mussweiler and Strack’s experiment, subjects were asked an anchoring question: “Is the annual mean temperature in Germany higher or lower than 5 °C / 20 °C?”<span class="footnote">Thomas Mussweiler and Fritz Strack, “Comparing Is Believing: A Selective Accessibility Model of Judgmental Anchoring,” <em>European Review of Social Psychology</em> 10 (1 1999): 135–167, doi:10.1080/14792779943000044.</span> Afterward, on a word-identification task, subjects presented with the 5 °C anchor were faster on identifying words like “cold” and “snow,” while subjects with the high anchor were faster to identify “hot” and “sun.” This shows a non-adjustment mechanism for anchoring: priming compatible thoughts and memories.</p>
    <p>The more general result is that <em>completely uninformative</em>, <em>known false</em>, or <em>totally irrelevant</em> “information” can influence estimates and decisions. In the field of heuristics and biases, this more general phenomenon is known as <em>contamination</em>.<span class="footnote">Gretchen B. Chapman and Eric J. Johnson, “Incorporating the Irrelevant: Anchors in Judgments of Belief and Value,” in Gilovich, Griffin, and Kahneman, <em>Heuristics and Biases</em>, 120–138.</span></p>
    <p>Early research in heuristics and biases discovered anchoring effects, such as subjects giving lower (higher) estimates of the percentage of UN countries found within Africa, depending on whether they were first asked if the percentage was more or less than 10 (65). This effect was originally attributed to subjects adjusting from the anchor as a starting point, stopping as soon as they reached a plausible value, and under-adjusting because they were stopping at one end of a confidence interval.<span class="footnote">Tversky and Kahneman, “Judgment Under Uncertainty.”</span></p>
    <p>Tversky and Kahneman’s early hypothesis still appears to be the correct explanation in some circumstances, notably when subjects generate the initial estimate themselves.<span class="footnote">Nicholas Epley and Thomas Gilovich, “Putting Adjustment Back in the Anchoring and Adjustment Heuristic: Differential Processing of Self-Generated and Experimentor-Provided Anchors,” <em>Psychological Science</em> 12 (5 2001): 391–396, doi:10.1111/1467-9280.00372.</span> But modern research seems to show that most anchoring is actually due to contamination, not sliding adjustment. (Hat tip to Unnamed for reminding me of this—I’d read the Epley and Gilovich paper years ago, as a chapter in <em>Heuristics and Biases</em>, but forgotten it.)</p>
    <p>Your grocery store probably has annoying signs saying “Limit 12 per customer” or “5 for $10.” Are these signs effective at getting customers to buy in larger quantities? You probably think you’re not influenced. But <em>someone</em> must be, because these signs have been shown to work, which is why stores keep putting them up.<span class="footnote">Brian Wansink, Robert J. Kent, and Stephen J. Hoch, “An Anchoring and Adjustment Model of Purchase Quantity Decisions,” <em>Journal of Marketing Research</em> 35, no. 1 (1998): 71–81, http://www.jstor.org/stable/3151931</span></p>
    <p>Yet the most fearsome aspect of contamination is that it serves as yet another of the thousand faces of confirmation bias. Once an idea gets into your head, it primes information compatible with it—and thereby ensures its continued existence. Never mind the selection pressures for winning political arguments; confirmation bias is built directly into our hardware, associational networks priming compatible thoughts and memories. An unfortunate side effect of our existence as neural creatures.</p>
    <p>A single fleeting image can be enough to prime associated words for recognition. Don’t think it takes anything more to set confirmation bias in motion. All it takes is that one quick flash, and the bottom line is already decided, for we change our minds less often than we think…</p>
  </Chapter>;
}