import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function TheVirtueOfNarrowness() {
  return <Chapter title={["The Virtue of Narrowness"]}>

    <blockquote>
      <p>What is true of one apple may not be true of another apple; thus more can be said about a single apple than about all the apples in the world.</p>
      <p>—The Twelve Virtues of Rationality</p>
    </blockquote>
    <p><span className="dropCap">W</span>ithin their own professions, people grasp the importance of narrowness; a car mechanic knows the difference between a carburetor and a radiator, and would not think of them both as “car parts.” A hunter-gatherer knows the difference between a lion and a panther. A janitor does not wipe the floor with window cleaner, even if the bottles look similar to one who has not mastered the art.</p>
    <p>Outside their own professions, people often commit the misstep of trying to broaden a word as widely as possible, to cover as much territory as possible. Is it not more glorious, more wise, more impressive, to talk about all the apples in the world? How much loftier it must be to <em>explain human thought in general</em>, without being distracted by smaller questions, such as how humans invent techniques for solving a Rubik’s Cube. Indeed, it scarcely seems necessary to consider <em>specific</em> questions at all; isn’t a general theory a worthy enough accomplishment on its own?</p>
    <p>It is the way of the curious to lift up one pebble from among a million pebbles on the shore, and see something new about it, something interesting, something different. You call these pebbles “diamonds,” and ask what might be special about them—what inner qualities they might have in common, beyond the glitter you first noticed. And then someone else comes along and says:</p>
    <p>“Why not call <em>this</em> pebble a diamond too? And this one, and this one?” They are enthusiastic, and they mean well. For it seems undemocratic and exclusionary and elitist and unholistic to call some pebbles “diamonds,” and others not. It seems… <em>narrow-minded</em>… if you’ll pardon the phrase. Hardly <em>open</em>, hardly <em>embracing</em>, hardly <em>communal</em>.</p>
    <p>You might think it poetic, to give one word many meanings, and thereby spread shades of connotation all around. But even poets, if they are good poets, must learn to see the world precisely. It is not enough to compare love to a flower. Hot jealous unconsummated love is not the same as the love of a couple married for decades. If you need a flower to symbolize jealous love, you must go into the garden, and look, and make subtle distinctions—find a flower with a heady scent, and a bright color, and thorns. Even if your intent is to shade meanings and cast connotations, you must keep precise track of exactly which meanings you shade and connote.</p>
    <p>It is a necessary part of the rationalist’s art—or even the poet’s art!—to focus narrowly on unusual pebbles which possess some special quality. And look at the details which those pebbles—and those pebbles alone!—share among each other. This is not a sin.</p>
    <p>It is perfectly all right for modern evolutionary biologists to explain <em>just</em> the patterns of living creatures, and not the “evolution” of stars or the “evolution” of technology. Alas, some unfortunate souls use the same word “evolution” to cover the naturally selected patterns of replicating life, <em>and</em> the strictly accidental structure of stars, <em>and</em> the intelligently configured structure of technology. And as we all know, if people use the same word, it must all be the same thing. We should automatically generalize anything we think we know about biological evolution to technology. Anyone who tells us otherwise must be a mere pointless pedant. It couldn’t possibly be that our ignorance of modern evolutionary theory is so total that we can’t tell the difference between a carburetor and a radiator. That’s unthinkable. No, the <em>other</em> person—you know, the one who’s studied the math—is just too dumb to see the connections.</p>


    <p>And what could be more virtuous than seeing connections? Surely the wisest of all human beings are the New Age gurus who say, “Everything is connected to everything else.” If you ever say this aloud, you should pause, so that everyone can absorb the sheer shock of this Deep Wisdom.</p>
    <p>There is a trivial mapping between a graph and its complement. A fully connected graph, with an edge between every two vertices, conveys the same amount of information as a graph with no edges at all. The important graphs are the ones where some things are <em>not</em> connected to some other things.</p>
    <p>When the unenlightened ones try to be profound, they draw endless verbal comparisons between this topic, and that topic, which is like this, which is like that; until their graph is fully connected and also totally useless. The remedy is specific knowledge and in-depth study. When you understand things in detail, you can see how they are <em>not</em> alike, and start enthusiastically subtracting edges <em>off</em> your graph.</p>
    <p>Likewise, the important categories are the ones that do not contain everything in the universe. Good hypotheses can only explain some possible outcomes, and not others.</p>
    <p>It was perfectly all right for Isaac Newton to explain <em>just</em> gravity, <em>just</em> the way things fall down—and how planets orbit the Sun, and how the Moon generates the tides—but <em>not</em> the role of money in human society or how the heart pumps blood. Sneering at narrowness is rather reminiscent of ancient Greeks who thought that going out and actually <em>looking</em> at things was manual labor, and manual labor was for slaves.</p>
    <p>As Plato put it in <em>The Republic, Book VII</em>:<span class="footnote">Plato, <em>Great Dialogues of Plato</em>, ed. Eric H. Warmington and Philip G. Rouse (Signet Classic, 1999).</span></p>
    <blockquote>
      <p>If anyone should throw back his head and learn something by staring at the varied patterns on a ceiling, apparently you would think that he was contemplating with his reason, when he was only staring with his eyes… I cannot but believe that no study makes the soul look on high except that which is concerned with real being and the unseen. Whether he gape and stare upwards, or shut his mouth and stare downwards, if it be things of the senses that he tries to learn something about, I declare he never could learn, for none of these things admit of knowledge: I say his soul is looking down, not up, even if he is floating on his back on land or on sea!</p>
    </blockquote>
    <p>Many today make a similar mistake, and think that narrow concepts are as lowly and unlofty and unphilosophical as, say, going out and looking at things—an endeavor only suited to the underclass. But rationalists—and also poets—need narrow words to express precise thoughts; they need categories that include only some things, and exclude others. There’s nothing wrong with focusing your mind, narrowing your categories, excluding possibilities, and sharpening your propositions. Really, there isn’t! If you make your words too broad, you end up with something that isn’t true and doesn’t even make good poetry.</p>
    <p><em>And <span className="smallCaps">don’t even get me started</span> on people who think Wikipedia is an “Artificial Intelligence,” the invention of LSD was a “Singularity,” or that corporations are “superintelligent”!</em></p>

  </Chapter >;
}