import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function MakeAnExtraordinaryEffort() {
  return <Chapter title={["Make an Extraordinary Effort"]}>


    <blockquote>
      <p>It is essential for a man to strive with all his heart, and to understand that it is difficult even to reach the average if he does not have the intention of surpassing others in whatever he does.</p>
      <p>—<em>Budo Shoshinshu</em><span class="footnote"><em>Daidoji Yuzan et al., _Budoshoshinshu: The Warrior’s Primer of Daidoji Yuzan</em> (Black Belt Communications Inc., 1984).</span></p>
    </blockquote >
    <blockquote>
      <p>In important matters, a “strong” effort usually results in only mediocre results. Whenever we are attempting anything truly worthwhile our effort must be as if our life is at stake, just as if we were under a physical attack! It is this extraordinary effort—an effort that drives us beyond what we thought we were capable of—that ensures victory in battle and success in life’s endeavors.</p>
      <p>—<em>Flashing Steel: Mastering Eishin-Ryu Swordsmanship</em><span class="footnote">Masayuki Shimabukuro, <em>Flashing Steel: Mastering Eishin-Ryu Swordsmanship</em> (Frog Books, 1995).</span></p>
    </blockquote>
    <p><span className="dropCap">A</span> ‘strong’ effort usually results in only mediocre results”—I have seen this over and over again. The slightest effort suffices to convince ourselves that we have done our best.</p>
    <p>There is a level beyond the virtue of <em>tsuyoku naritai</em> (“I want to become stronger”). <em>Isshoukenmei</em> was originally the loyalty that a samurai offered in return for his position, containing characters for “life” and “land.” The term evolved to mean “make a desperate effort”: Try your hardest, your utmost, as if your life were at stake. It was part of the gestalt of <em>bushido</em>, which was not reserved only for fighting. I’ve run across variant forms <em>issho kenmei</em> and <em>isshou kenmei</em>; one source indicates that the former indicates an all-out effort on some single point, whereas the latter indicates a lifelong effort.</p>
    <p>I try not to praise the East too much, because there’s a tremendous selectivity in which parts of Eastern culture the West gets to hear about. But on some points, at least, Japan’s culture scores higher than America’s. Having a handy compact phrase for “make a desperate all-out effort as if your own life were at stake” is one of those points. It’s the sort of thing a Japanese parent might say to a student before exams—but don’t think it’s cheap hypocrisy, like it would be if an American parent made the same statement. They take exams very seriously in Japan.</p>
    <p>Every now and then, someone asks why the people who call themselves “rationalists” don’t always seem to do all that much better in life, and from my own history the answer seems straightforward: It takes a <em>tremendous</em> amount of rationality before you stop making stupid damn mistakes.</p>
    <p>As I’ve mentioned a couple of times before: Robert Aumann, the Nobel laureate who first proved that Bayesians with the same priors cannot agree to disagree, is a believing Orthodox Jew. Surely he understands the math of probability theory, but that is not enough to save him. What more does it take? Studying heuristics and biases? Social psychology? Evolutionary psychology? Yes, but also it takes <em>isshoukenmei</em>, a desperate effort to be rational—to rise above the level of Robert Aumann.</p>
    <p>Sometimes I do wonder if I ought to be peddling rationality in Japan instead of the United States—but Japan is not preeminent over the United States scientifically, despite their more studious students. The Japanese don’t rule the world today, though in the 1980s it was widely suspected that they would (hence the Japanese asset bubble). Why not?</p>
    <p>In the West, there is a saying: “The squeaky wheel gets the grease.”</p>
    <p>In Japan, the corresponding saying runs: “The nail that sticks up gets hammered down.”</p>
    <p>This is hardly an original observation on my part: but entrepreneurship, risk-taking, leaving the herd, are still advantages the West has over the East. And since Japanese scientists are not yet preeminent over American ones, this would seem to count for at least as much as desperate efforts.</p>
    <p>Anyone who can muster their willpower for thirty seconds can make a <em>desperate</em> effort to lift more weight than they usually could. But what if the weight that needs lifting is a truck? Then desperate efforts won’t suffice; you’ll have to do something <em>out of the ordinary</em> to succeed. You may have to do something that you weren’t taught to do in school. Something that others aren’t expecting you to do, and might not understand. You may have to go outside your comfortable routine, take on difficulties you don’t have an existing mental program for handling, and bypass the System.</p>
    <p>This is not included in <em>isshokenmei</em>, or Japan would be a very different place.</p>
    <p>So then let us distinguish between the virtues “make a desperate effort” and “make an extraordinary effort.”</p>
    <p>And I will even say: The second virtue is higher than the first.</p>
    <p>The second virtue is also more dangerous. If you put forth a <em>desperate</em> effort to lift a heavy weight, using all your strength without restraint, you may tear a muscle. Injure yourself, even permanently. But if a <em>creative</em> idea goes wrong, you could blow up the truck and any number of innocent bystanders. Think of the difference between a businessperson making a <em>desperate</em> effort to generate profits, because otherwise they must go bankrupt; versus a businessperson who goes to <em>extraordinary</em> lengths to profit, in order to conceal an embezzlement that could send them to prison. Going outside the system isn’t always a good thing.</p>
    <p>A friend of my little brother’s once came over to my parents’ house, and wanted to play a game—I entirely forget which one, except that it had complex but well-designed rules. The friend wanted to change the rules, not for any particular reason, but on the general principle that playing by the ordinary rules of anything was too boring. I said to him: “Don’t violate rules for the sake of violating them. If you break the rules only when you have an overwhelmingly good reason to do so, you will have more than enough trouble to last you the rest of your life.”</p>
    <p>Even so, I think that we could do with more appreciation of the virtue “make an extraordinary effort.” I’ve lost count of how many people have said to me something like: “It’s futile to work on Friendly AI, because the first AIs will be built by powerful corporations and they will only care about maximizing profits.” “It’s futile to work on Friendly AI, the first AIs will be built by the military as weapons.” And I’m standing there thinking: <em>Does it even occur to them that this might be a time to try for something other than the default outcome?</em> They and I have different basic assumptions about how this whole AI thing works, to be sure; but if I believed what they believed, I wouldn’t be shrugging and going on my way.</p>
    <p>Or the ones who say to me: “You should go to college and get a Master’s degree and get a doctorate and publish a lot of papers on ordinary things— scientists and investors won’t listen to you otherwise.” Even assuming that I tested out of the bachelor’s degree, we’re talking about at least a ten-year detour in order to <em>do everything the ordinary, normal, default way</em>. And I stand there thinking: <em>Are they really under the impression that humanity can survive if every single person does everything the ordinary, normal, default way?</em></p>
    <p>I am not fool enough to make plans that depend on a <em>majority</em> of the people, or even 10% of the people, being willing to think or act outside their comfort zone. That’s why I tend to think in terms of the privately funded “brain in a box in a basement” model. Getting that private funding does require a tiny fraction of humanity’s six billions to spend more than five seconds thinking about a non-prepackaged question. As challenges posed by Nature go, this seems to have a kind of awful justice to it—that the life or death of the human species depends on whether we can put forth a <em>few</em> people who can do things that are at least a <em>little</em> extraordinary. The penalty for failure is disproportionate, but that’s still better than most challenges of Nature, which have no justice at all. Really, among the six billion of us, there ought to be at least a few who can think outside their comfort zone at least some of the time.</p>
    <p>Leaving aside the details of that debate, I am still stunned by how often a single element of the extraordinary is unquestioningly taken as an absolute and unpassable obstacle.</p>
    <p>Yes, “keep it ordinary as much as possible” can be a useful heuristic. Yes, the risks accumulate. But sometimes you have to go to that trouble. You should have a sense of the risk of the extraordinary, but also a sense of the cost of ordinariness: it isn’t always something you can afford to lose.</p>
    <p>Many people imagine some future that won’t be much fun—and it doesn’t even seem to occur to them to try and change it. Or they’re satisfied with futures that seem to me to have a tinge of sadness, of loss, and they don’t even seem to <em>ask</em> if we could do better—because that sadness seems like an ordinary outcome to them.</p>
    <p>As a smiling man once said, “It’s all part of the plan.”</p>

  </Chapter >;
}