import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function TsuyokuNaritai() {
  return <Chapter title={["Tsuyoku Naritai!", "(I Want to Become Stronger)"]}>


    <p><span className="dropCap">I</span>n Orthodox Judaism there is a saying: “The previous generation is to the next one as angels are to men; the next generation is to the previous one as donkeys are to men.” This follows from the Orthodox Jewish belief that all Judaic law was given to Moses by God at Mount Sinai. After all, it’s not as if you could do an experiment to gain new halachic knowledge; the only way you can know is if someone tells you (who heard it from someone else, who heard it from God). Since there is no new source of information, it can only be degraded in transmission from generation to generation.</p>
    <p>Thus, modern rabbis are not allowed to overrule ancient rabbis. Crawly things are ordinarily unkosher, but it is permissible to eat a worm found in an apple—the ancient rabbis believed the worm was spontaneously generated inside the apple, and therefore was part of the apple. A modern rabbi cannot say, “Yeah, well, the ancient rabbis knew diddly-squat about biology. Overruled!” A modern rabbi cannot possibly know a halachic principle the ancient rabbis did not, because how could the ancient rabbis have passed down the answer from Mount Sinai to him? Knowledge derives from authority, and therefore is only ever lost, not gained, as time passes.</p>
    <p>When I was first exposed to the angels-and-donkeys proverb in (religious) elementary school, I was not old enough to be a full-blown atheist, but I still thought to myself: “Torah loses knowledge in every generation. Science gains knowledge with every generation. No matter where they started out, sooner or later science must surpass Torah.”</p>
    <p>The most important thing is that there should be progress. So long as you keep moving forward you will reach your destination; but if you stop moving you will never reach it.</p>
    <p><em>Tsuyoku naritai</em> is Japanese. <em>Tsuyoku</em> is “strong”; <em>naru</em> is “becoming,” and the form <em>naritai</em> is “want to become.” Together it means “I want to become stronger,” and it expresses a sentiment embodied more intensely in Japanese works than in any Western literature I’ve read. You might say it when expressing your determination to become a professional Go player—or after you lose an important match, but you haven’t given up—or after you win an important match, but you’re not a ninth-dan player yet—or after you’ve become the greatest Go player of all time, but you still think you can do better. That is <em>tsuyoku naritai</em>, the will to transcendence.</p>
    <p><em>Tsuyoku naritai</em> is the driving force behind my essay The Proper Use of Humility, in which I contrast the student who humbly double-checks their math test, and the student who modestly says, “But how can we ever really know? No matter how many times I check, I can never be absolutely certain.” The student who double-checks their answers <em>wants to become stronger</em>; they react to a possible inner flaw by doing what they can to repair the flaw, not with resignation.</p>
    <p>Each year on Yom Kippur, an Orthodox Jew recites a litany which begins <em>Ashamnu, bagadnu, gazalnu, dibarnu dofi</em>, and goes on through the entire Hebrew alphabet: <em>We have acted shamefully, we have betrayed, we have stolen, we have slandered</em>…</p>
    <p>As you pronounce each word, you strike yourself over the heart in penitence. There’s no exemption whereby, if you manage to go without stealing all year long, you can skip the word <em>gazalnu</em> and strike yourself one less time. That would violate the community spirit of Yom Kippur, which is about <em>confessing</em> sins—not <em>avoiding</em> sins so that you have less to confess.</p>
    <p>By the same token, the <em>Ashamnu</em> does not end, “But that was this year, and next year I will do better.”</p>
    <p>The <em>Ashamnu</em> bears a remarkable resemblance to the notion that the way of rationality is to beat your fist against your heart and say, “We are all biased, we are all irrational, we are not fully informed, we are overconfident, we are poorly calibrated…”</p>
    <p>Fine. Now tell me how you plan to become <em>less</em> biased, <em>less</em> irrational, <em>more</em> informed, <em>less</em> overconfident, <em>better</em> calibrated.</p>
    <p>There is an old Jewish joke: During Yom Kippur, the rabbi is seized by a sudden wave of guilt, and prostrates himself and cries, “God, I am nothing before you!” The cantor is likewise seized by guilt, and cries, “God, I am nothing before you!” Seeing this, the janitor at the back of the synagogue prostrates himself and cries, “God, I am nothing before you!” And the rabbi nudges the cantor and whispers, “Look who thinks he’s nothing.”</p>
    <p>Take no pride in your confession that you too are biased; do not glory in your self-awareness of your flaws. This is akin to the principle of not taking pride in confessing your ignorance; for if your ignorance is a source of pride to you, you may become loath to relinquish your ignorance when evidence comes knocking. Likewise with our flaws—we should not gloat over how self-aware we are for confessing them; the occasion for rejoicing is when we have a little less to confess.</p>
    <p>Otherwise, when the one comes to us with a plan for <em>correcting</em> the bias, we will snarl, “Do you think to set yourself above us?” We will shake our heads sadly and say, “You must not be very self-aware.”</p>
    <p>Never confess to me that you are just as flawed as I am unless you can tell me what you plan to do about it. Afterward you will still have plenty of flaws left, but that’s not the point; the important thing is to <em>do better</em>, to keep moving ahead, to take one more step forward. <em>Tsuyoku naritai!</em></p>

  </Chapter>;
}