import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function ArguingByDefinition() {
  return <Chapter title={["Arguing \"By Definition\""]}>

    <p>“This plucked chicken has two legs and no feathers—therefore, <em>by definition</em>, it is a human!”</p>
    <p><span className="dropCap">W</span>hen people argue definitions, they usually start with some visible, known, or at least widely believed set of characteristics; then pull out a dictionary, and point out that these characteristics fit the dictionary definition; and so conclude, “Therefore, <em>by definition</em>, atheism is a religion!”</p>
    <p>But visible, known, widely believed characteristics are rarely the real point of a dispute. Just the fact that someone thinks Socrates’s two legs are evident enough to make a good premise for the argument, “Therefore, <em>by definition</em>, Socrates is human!” indicates that bipedalism probably isn’t <em>really</em> what’s at stake—or the listener would reply, “Whaddaya mean Socrates is bipedal? That’s what we’re arguing about in the first place!”</p>
    <p>Now there is an important sense in which we can legitimately move from evident characteristics to not-so-evident ones. You can, legitimately, see that Socrates is human-shaped, and predict his vulnerability to hemlock. But this <em>probabilistic</em> inference does not rely on dictionary definitions or common usage; it relies on the universe containing empirical clusters of similar things.</p>
    <p>This cluster structure is not going to change depending on how you define your words. Even if you look up the dictionary definition of “human” and it says “all featherless bipeds except Socrates,” that isn’t going to change the <em>actual</em> degree to which Socrates is similar to the rest of us featherless bipeds.</p>
    <p>When you are arguing <em>correctly</em> from cluster structure, you’ll say something like, “Socrates has two arms, two feet, a nose and tongue, speaks fluent Greek, uses tools, and in every aspect I’ve been able to observe him, seems to have every major and minor property that characterizes <em>Homo sapiens</em>; so I’m going to guess that he has human DNA, human biochemistry, and is vulnerable to hemlock just like all other <em>Homo sapiens</em> in whom hemlock has been clinically tested for lethality.”</p>
    <p>And suppose I reply, “But I saw Socrates out in the fields with some herbologists; I think they were trying to prepare an antidote. Therefore I <em>don’t</em> expect Socrates to keel over after he drinks the hemlock—he will be an exception to the general behavior of objects in his cluster: they did not take an antidote, and he did.”</p>
    <p>Now there’s not much point in arguing over whether Socrates is “human” or not. The conversation has to move to a more detailed level, poke around <em>inside</em> the details that make up the “human” category—talk about human biochemistry, and specifically, the neurotoxic effects of coniine.</p>
    <p>If you go on insisting, “But Socrates is a human and humans, <em>by definition</em>, are mortal!” then what you’re really trying to do is blur out everything you know about Socrates <em>except</em> the fact of his humanity—insist that the only correct prediction is the one you would make if you knew nothing about Socrates <em>except</em> that he was human.</p>
    <p>Which is like insisting that a coin is 50% likely to be showing heads or tails, because it is a “fair coin,” after you’ve <em>actually looked at the coin</em> and it’s showing heads. It’s like insisting that Frodo has ten fingers, because most hobbits have ten fingers, after you’ve <em>already looked at his hands</em> and seen nine fingers. Naturally this is illegal under Bayesian probability theory: You can’t just refuse to condition on new evidence.</p>
    <p>And you can’t just keep one categorization and make estimates based on that, while deliberately throwing out everything else you know.</p>
    <p>Not every piece of new evidence makes a significant difference, of course. If I see that Socrates has nine fingers, this isn’t going to noticeably change my estimate of his vulnerability to hemlock, because I’ll expect that the way Socrates lost his finger didn’t change the rest of his biochemistry. And this is true, <em>whether or not</em> the dictionary’s definition says that human beings have ten fingers. The legal inference is based on the cluster structure of the environment, and the causal structure of biology; <em>not</em> what the dictionary editor writes down, nor even “common usage.”</p>
    <p>Now ordinarily, when you’re doing this <em>right</em>—in a <em>legitimate</em> way—you just say, “The coniine alkaloid found in hemlock produces muscular paralysis in humans, resulting in death by asphyxiation.” Or more simply, “Humans are vulnerable to hemlock.” That’s how it’s usually said in a <em>legitimate</em> argument.</p>
    <p>When would someone feel the need to <em>strengthen</em> the argument with the emphatic phrase “by definition”? (E.g. “Humans are vulnerable to hemlock <em>by definition!</em>”) Why, when the inferred characteristic has been called into doubt—Socrates has been seen consulting herbologists—and so the speaker feels the need to tighten the vise of logic.</p>
    <p>So when you see “by definition” used like this, it usually means: “Forget what you’ve heard about Socrates consulting herbologists—humans, <em>by definition</em>, are mortal!”</p>
    <p>People feel the need to squeeze the argument onto a single course by saying “Any <em>P</em>, by definition, has property <em>Q</em>!,” on exactly those occasions when they see, and prefer to dismiss out of hand, <em>additional arguments</em> that call into doubt the default inference based on clustering.</p>
    <p>So too with the argument “<em>X</em>, <em>by definition</em>, is a <em>Y</em> !” E.g., “Atheists believe that God doesn’t exist; therefore atheists have beliefs about God, because a negative belief is still a belief; therefore atheism asserts answers to theological questions; therefore atheism is, <em>by definition</em>, a religion.”</p>
    <p>You wouldn’t feel the need to say, “Hinduism, <em>by definition</em>, is a religion!” because, well, of course Hinduism is a religion. It’s not just a religion “by definition,” it’s, like, an <em>actual</em> religion.</p>
    <p>Atheism does not resemble the central members of the “religion” cluster, so if it wasn’t for the fact that atheism is a religion <em>by definition</em>, you might go around thinking that atheism <em>wasn’t</em> a religion. That’s why you’ve got to crush all opposition by pointing out that “Atheism is a religion” is true <em>by definition</em>, because it isn’t true any other way.</p>
    <p>Which is to say: People insist that “<em>X</em>, <em>by definition</em>, is a <em>Y</em> !” on those occasions when they’re trying to sneak in a connotation of <em>Y</em> that isn’t directly in the definition, and <em>X</em> doesn’t look all that much like other members of the <em>Y</em> cluster.</p>
    <p>Over the last thirteen years I’ve been keeping track of how often this phrase is used correctly versus incorrectly—though not with literal statistics, I fear. But eyeballing suggests that using the phrase <em>by definition</em>, anywhere outside of math, is among the most alarming signals of flawed argument I’ve ever found. It’s right up there with “Hitler,” “God,” “absolutely certain,” and “can’t prove that.”</p>
    <p>This heuristic of failure is not perfect—the first time I ever spotted a correct usage outside of math, it was by Richard Feynman; and since then I’ve spotted more. But you’re probably better off just deleting the phrase “by definition” from your vocabulary—and <em>always</em> on any occasion where you might be tempted to say it in italics or followed with an exclamation mark. That’s a bad idea <em>by definition!</em></p>
  </Chapter>;
}
