import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function CategorizingHasConsequences() {
  return <Chapter title={["Categorizing Has Consequences"]}>


    <p><span className="dropCap">A</span>mong the many genetic variations and mutations you carry in your genome, there are a very few alleles you probably know—including those determining your blood type: the presence or absence of the A, B, and + antigens. If you receive a blood transfusion containing an antigen you don’t have, it will trigger an allergic reaction. It was Karl Landsteiner’s discovery of this fact, and how to test for compatible blood types, that made it possible to transfuse blood without killing the patient. (1930 Nobel Prize in Medicine.) Also, if a mother with blood type A (for example) bears a child with blood type A+, the mother may acquire an allergic reaction to the + antigen; if she has another child with blood type A+, the child will be in danger, unless the mother takes an allergic suppressant during pregnancy. Thus people learn their blood types before they marry.</p>
    <p>Oh, and <em>also</em>: people with blood type A are earnest and creative, while people with blood type B are wild and cheerful. People with type O are agreeable and sociable, while people with type AB are cool and controlled. (You would think that O would be the absence of A and B, while AB would just be A plus B, but no…) All this, according to the Japanese blood type theory of personality.</p>
    <p>It would seem that blood type plays the role in Japan that astrological signs play in the West, right down to blood type horoscopes in the daily newspaper.</p>
    <p>This fad is especially odd because blood types have <em>never been</em> mysterious, not in Japan and not anywhere. We only know blood types even exist thanks to Karl Landsteiner. No mystic witch doctor, no venerable sorcerer, ever said a word about blood types; there are no ancient, dusty scrolls to shroud the error in the aura of antiquity. If the medical profession claimed tomorrow that it had all been a colossal hoax, we layfolk would not have one scrap of evidence from our unaided senses to contradict them.</p>
    <p>There’s never been a war between blood types. There’s never even been a political conflict between blood types. The stereotypes must have arisen <em>strictly</em> from the <em>mere existence</em> of the labels.</p>
    <p>Now, someone is bound to point out that this is a story of categorizing humans. Does the same thing happen if you categorize plants, or rocks, or office furniture? I can’t recall reading about such an experiment, but of course, that doesn’t mean one hasn’t been done. (I’d expect the chief difficulty of doing such an experiment would be finding a protocol that didn’t mislead the subjects into thinking that, since the label was given you, it must be significant somehow.) So while I don’t mean to update on imaginary evidence, I would predict a positive result for the experiment: I would expect them to find that mere labeling had power over all things, at least in the human imagination.</p>
    <p>You can see this in terms of similarity clusters: once you draw a boundary around a group, the mind starts trying to harvest similarities from the group. And unfortunately the human pattern-detectors seem to operate in such overdrive that we see patterns whether they’re there or not; a weakly negative correlation can be mistaken for a strong positive one with a bit of selective memory.</p>
    <p>You can see this in terms of neural algorithms: creating a name for a set of things is like allocating a subnetwork to find patterns in them.</p>
    <p>You can see this in terms of a compression fallacy: things given the same name end up dumped into the same mental bucket, blurring them together into the same point on the map.</p>
    <p>Or you can see this in terms of the boundless human ability to make stuff up out of thin air and believe it because no one can prove it’s wrong. As soon as you name the category, you can start making up stuff about it. The named thing doesn’t have to be perceptible; it doesn’t have to exist; it doesn’t even have to be coherent.</p>
    <p>And no, it’s not just Japan: Here in the West, a blood-type-based diet book called Eat Right 4 Your Type was a bestseller.</p>
    <p>Any way you look at it, drawing a boundary in thingspace is not a neutral act. Maybe a more cleanly designed, more purely Bayesian AI could ponder an arbitrary class and not be influenced by it. But you, a human, do not have that option. Categories are not static things in the context of a human brain; as soon as you actually think of them, they exert force on your mind. One more reason not to believe you can define a word any way you like.</p>
  </Chapter>;
}
