import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function ReplaceTheSymbolWithTheSubstance() {
  return <Chapter title={["Replace the Symbol with", "the Substance"]}>


    <p><span className="dropCap">W</span>hat does it take to—as in the previous essay’s example—see a “baseball game” as “An artificial group conflict in which you use a long wooden cylinder to whack a thrown spheroid, and then run between four safe positions”? What does it take to play the rationalist version of Taboo, in which the goal is not to find a synonym that isn’t on the card, but to find a way of describing without the standard concept-handle?</p>
    <p>You have to visualize. You have to make your mind’s eye see the details, as though looking for the first time. You have to perform an Original Seeing.</p>
    <p>Is that a “bat”? No, it’s a long, round, tapering, wooden rod, narrowing at one end so that a human can grasp and swing it.</p>
    <p>Is that a “ball”? No, it’s a leather-covered spheroid with a symmetrical stitching pattern, hard but not metal-hard, which someone can grasp and throw, or strike with the wooden rod, or catch.</p>
    <p>Are those “bases”? No, they’re fixed positions on a game field, that players try to run to as quickly as possible because of their safety within the game’s artificial rules.</p>
    <p>The chief obstacle to performing an original seeing is that your mind already has a nice neat summary, a nice little easy-to-use concept handle. Like the word “baseball,” or “bat,” or “base.” It takes an effort to stop your mind from sliding down the familiar path, the easy path, the path of least resistance, where the small featureless word rushes in and obliterates the details you’re trying to see. A word itself can have the destructive force of cliché; a word itself can carry the poison of a cached thought.</p>
    <p>Playing the game of Taboo—being able to describe without using the standard pointer/label/handle—is one of the <em>fundamental</em> rationalist capacities. It occupies the same primordial level as the habit of constantly asking “Why?” or</p>
    <p>“What does this belief make me anticipate?” The art is closely related to:</p>
    <ul>
      <li>Pragmatism, because seeing in this way often gives you a much closer connection to anticipated experience, rather than propositional belief;</li>
      <li>Reductionism, because seeing in this way often forces you to drop down to a lower level of organization, look at the parts instead of your eye skipping over the whole;</li>
      <li>Hugging the query, because words often distract you from the question you really want to ask;</li>
      <li>Avoiding cached thoughts, which will rush in using standard words, so you can block them by tabooing standard words;</li>
      <li>The writer’s rule of “Show, don’t tell!,” which has power among rationalists;</li>
      <li>And not losing sight of your original purpose. How could tabooing a word help you keep your purpose?</li>
    </ul>
    <p>From Lost Purposes:</p>
    <blockquote>
      <p>As you read this, some young man or woman is sitting at a desk in a university, earnestly studying material they have no intention of ever using, and no interest in knowing for its own sake. They want a high-paying job, and the high-paying job requires a piece of paper, and the piece of paper requires a previous master’s degree, and the master’s degree requires a bachelor’s degree, and the university that grants the bachelor’s degree requires you to take a class in twelfth-century knitting patterns to graduate. So they diligently study, intending to forget it all the moment the final exam is administered, but still seriously working away, because they <em>want</em> that piece of paper.</p>
    </blockquote>
    <p>Why are you going to “school”? To get an “education” ending in a “degree.” Blank out the forbidden words and all their obvious synonyms, visualize the actual details, and you’re much more likely to notice that “school” currently seems to consist of sitting next to bored teenagers listening to material you already know, that a “degree” is a piece of paper with some writing on it, and that “education” is forgetting the material as soon as you’re tested on it.</p>
    <p>Leaky generalizations often manifest through categorizations: People who actually learn in classrooms are categorized as “getting an education,” so “getting an education” must be good; but then anyone who actually shows up at a college will also match against the concept “getting an education,” whether or not they learn.</p>
    <p>Students who understand math will do well on tests, but if you require schools to produce good test scores, they’ll spend all their time teaching to the test. A <em>mental category</em>, that imperfectly matches your goal, can produce the same kind of incentive failure <em>internally</em>. You want to learn, so you need an “education”; and then as long as you’re getting anything that matches against the category “education,” you may not notice whether you’re learning or not. Or you’ll notice, but you won’t realize you’ve lost sight of your original purpose, because you’re “getting an education” and that’s how you mentally described your goal.</p>
    <p>To categorize is to throw away information. If you’re told that a falling tree makes a “sound,” you don’t know what the actual sound is; you haven’t actually heard the tree falling. If a coin lands “heads,” you don’t know its radial orientation. A blue egg-shaped thing may be a “blegg,” but what if the exact egg shape varies, or the exact shade of blue? You want to use categories to throw away irrelevant information, to sift gold from dust, but often the standard categorization ends up throwing out relevant information too. And when you end up in that sort of mental trouble, the first and most obvious solution is to play Taboo.</p>
    <p>For example: “Play Taboo” is itself a leaky generalization. Hasbro’s version is not the rationalist version; they only list five additional banned words on the card, and that’s not nearly enough coverage to exclude thinking in familiar old words. What rationalists do would count as playing Taboo—it would match against the “play Taboo” concept—but not everything that counts as playing Taboo works to force original seeing. If you just think “play Taboo to force original seeing,” you’ll start thinking that anything that counts as playing Taboo must count as original seeing.</p>
    <p>The rationalist version isn’t a game, which means that you can’t win by trying to be clever and stretching the rules. You have to play Taboo with a voluntary handicap: Stop yourself from using synonyms that aren’t on the card. You also have to stop yourself from inventing a new simple word or phrase that functions as an equivalent mental handle to the old one. You are trying to zoom in on your map, not rename the cities; dereference the pointer, not allocate a new pointer; see the events as they happen, not rewrite the cliché in a different wording.</p>
    <p>By visualizing the problem in more detail, you can see the lost purpose: Exactly what do you do when you “play Taboo”? What purpose does each and every part serve?</p>
    <p>If you see your activities and situation originally, you will be able to originally see your goals as well. If you can look with fresh eyes, as though for the first time, you will see yourself doing things that you would never dream of doing if they were not habits.</p>
    <p>Purpose is lost whenever the substance (learning, knowledge, health) is displaced by the symbol (a degree, a test score, medical care). To heal a lost purpose, or a lossy categorization, you must do the reverse:</p>
    <p>Replace the symbol with the substance; replace the signifier with the signified; replace the property with the membership test; replace the word with the meaning; replace the label with the concept; replace the summary with the details; replace the proxy question with the real question; dereference the pointer; drop into a lower level of organization; mentally simulate the process instead of naming it; zoom in on your map.</p>
    <p>The Simple Truth was generated by an exercise of this discipline to describe “truth” on a lower level of organization, without invoking terms like “accurate,” “correct,” “represent,” “reflect,” “semantic,” “believe,” “knowledge,” “map,” or “real.” (And remember that the goal is not <em>really</em> to play Taboo—the word “true” appears in the text, but <em>not</em> to define truth. It would get a buzzer in Hasbro’s game, but we’re not <em>actually</em> playing that game. Ask yourself whether the document fulfilled its purpose, not whether it followed the rules.)</p>
    <p>Bayes’s Rule itself describes “evidence” in pure math, without using words like “implies,” “means,” “supports,” “proves,” or “justifies.” Set out to <em>define</em> such philosophical terms, and you’ll just go in circles.</p>
    <p>And then there’s the most important word of all to Taboo. I’ve often warned that you should be careful not to overuse it, or even avoid the concept in certain cases. Now you know the real reason why. It’s not a bad subject to think about. But your true understanding is measured by your ability to describe what you’re doing and why, <em>without</em> using that word or any of its synonyms.</p>
  </Chapter>;
}
