import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function TheArgumentFromCommonUsage() {
  return <Chapter title={["The Argument from", "Common Usage"]}>


    <p>Part of the Standard Definitional Dispute runs as follows:</p>
    <blockquote>
      <p><span className="smallCaps">Albert:</span> “Look, suppose that I left a microphone in the forest and recorded the pattern of the acoustic vibrations of the tree falling. If I played that back to someone, they’d call it a ‘sound’! That’s the common usage! Don’t go around making up your own wacky definitions!”</p>
      <p><span className="smallCaps">Barry:</span> “One, I can define a word any way I like so long as I use it consistently. Two, the meaning I gave was in the dictionary. Three, who gave you the right to decide what is or isn’t common usage?”</p>
    </blockquote>
    <p><span className="dropCap tall">N</span>ot all definitional disputes progress as far as recognizing the notion of common usage. More often, I think, someone picks up a dictionary because they believe that words have meanings, and the dictionary faithfully records what this meaning is. Some people even seem to believe that the dictionary <em>determines</em> the meaning—that the dictionary editors are the Legislators of Language. Maybe because back in elementary school, their authority-teacher said that they had to obey the dictionary, that it was a mandatory rule rather than an optional one?</p>
    <p>Dictionary editors read what other people write, and record what the words seem to mean; they are historians. The Oxford English Dictionary may be <em>comprehensive</em>, but never <em>authoritative</em>.</p>
    <p>But surely there is a social imperative to use words in a commonly understood way? Does not our human telepathy, our valuable power of language, rely on mutual coordination to work? Perhaps we should voluntarily treat dictionary editors as supreme arbiters—even if <em>they</em> prefer to think of themselves as historians—in order to maintain the quiet cooperation on which all speech depends.</p>
    <p>The phrase “authoritative dictionary” is almost never used correctly, an example of proper usage being The Authoritative Dictionary of ieee Standards Terms. The ieee is a body of voting members who have a professional need for exact agreement on terms and definitions, and so <em>The Authoritative Dictionary of IEEE Standards Terms</em> is actual, negotiated legislation, which exerts whatever authority one regards as residing in the IEEE.</p>
    <p>In everyday life, shared language usually does not arise from a deliberate agreement, as of the IEEE. It’s more a matter of infection, as words are invented and diffuse through the culture. (A “meme,” one might say, following Richard Dawkins forty years ago—but you already know what I mean, and if not, you can look it up on Google, and then you too will have been infected.)</p>
    <p>Yet as the example of the IEEE shows, agreement on language can also be a cooperatively established public good. If you and I wish to undergo an exchange of thoughts via language, the human telepathy, then it is in our mutual interest that we use the <em>same</em> word for similar concepts—preferably, concepts similar to the limit of resolution in our brain’s representation thereof—even though we have no obvious mutual interest in using any <em>particular</em> word for a concept.</p>
    <p>We have no obvious mutual interest in using the word “oto” to mean sound, or “sound” to mean oto; but we have a mutual interest in using the same <em>word</em>, whichever word it happens to be. (Preferably, words we use frequently should be short, but let’s not get into information theory just yet.)</p>
    <p>But, while we have a mutual interest, it is not strictly <em>necessary</em> that you and I use the similar labels <em>internally</em>; it is only convenient. If I know that, to you, “oto” means sound—that is, you associate “oto” to a concept very similar to the one I associate to “sound”—then I can say “Paper crumpling makes a crackling oto.” It requires extra thought, but I can do it if I want.</p>
    <p>Similarly, if you say “What is the walking-stick of a bowling ball dropping on the floor?” and I know which concept <em>you</em> associate with the syllables “walking-stick,” then I can figure out what you mean. It may require some thought, and give me pause, because I ordinarily associate “walking-stick” with a different concept. But I can do it just fine.</p>
    <p>When humans really <em>want</em> to communicate with each other, we’re hard to stop! If we’re stuck on a deserted island with no common language, we’ll take up sticks and draw pictures in sand.</p>
    <p>Albert’s appeal to the Argument from Common Usage assumes that agreement on language is a cooperatively established public good. Yet Albert assumes this for the sole purpose of rhetorically accusing Barry of breaking the agreement, and endangering the public good. Now the falling-tree argument has gone all the way from botany to semantics to politics; and so Barry responds by challenging Albert for the authority to define the word.</p>
    <p>A rationalist, with the discipline of hugging the query active, would notice that the conversation had gone rather far astray.</p>
    <p>Oh, dear reader, is it all really necessary? Albert knows what Barry means by “sound.” Barry knows what Albert means by “sound.” Both Albert and Barry have access to words, such as “acoustic vibrations” or “auditory experience,” which they already associate to the same concepts, and which can describe events in the forest without ambiguity. If they were stuck on a deserted island, trying to communicate with each other, their work would be <em>done</em>.</p>
    <p>When both sides <em>know</em> what the other side <em>wants</em> to say, and both sides accuse the other side of defecting from “common usage,” then whatever it is they are about, it is clearly not <em>working out a way to communicate with each other</em>. But this is the whole benefit that common usage provides in the first place.</p>
    <p>Why would you argue about the meaning of a word, two sides trying to wrest it back and forth? If it’s just a namespace conflict that has gotten blown out of proportion, and nothing more is at stake, then the two sides need merely generate two new words and use them consistently.</p>
    <p>Yet often categorizations function as hidden inferences and disguised queries. Is atheism a “religion”? If someone is arguing that the reasoning methods used in atheism are on a par with the reasoning methods used in Judaism, or that atheism is on a par with Islam in terms of causally engendering violence, then they have a clear argumentative stake in lumping it all together into an indistinct gray blur of “faith.”</p>
    <p>Or consider the fight to blend together blacks and whites as “people.” This would not be a time to generate two words—what’s at stake is exactly the idea that you shouldn’t draw a moral distinction.</p>
    <p>But once any empirical proposition is at stake, <em>or</em> any moral proposition, you can no longer appeal to common usage.</p>
    <p>If the question is how to cluster together similar things for purposes of inference, empirical predictions will depend on the answer; which means that definitions can be <em>wrong</em>. A conflict of predictions cannot be settled by an opinion poll.</p>
    <p>If you want to know whether atheism should be clustered with supernaturalist religions for purposes of some particular empirical inference, the dictionary can’t answer you.</p>
    <p>If you want to know whether blacks are people, the dictionary can’t answer you.</p>
    <p>If everyone believes that the red light in the sky is Mars the God of War, the dictionary will define “Mars” as the God of War. If everyone believes that fire is the release of phlogiston, the dictionary will define “fire” as the release of phlogiston.</p>
    <p>There is an art to using words; even when definitions are not literally true or false, they are often wiser or more foolish. Dictionaries are mere histories of past usage; if you treat them as supreme arbiters of meaning, it binds you to the wisdom of the past, forbidding you to do better.</p>
    <p>Though do take care to ensure (if you must depart from the wisdom of the past) that people can figure out what you’re trying to swim.</p>
  </Chapter>;
}
