import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function TypicalityAndAsymmetricalSimilarity() {
  return <Chapter title={["Typicality and", "Asymmetrical Similarity"]}>


    <p><span className="dropCap">B</span>irds fly. Well, except ostriches don’t. But which is a more typical bird—a robin, or an ostrich?</p>
    <p>Which is a more typical chair: a desk chair, a rocking chair, or a beanbag chair?</p>
    <p>Most people would say that a robin is a more typical bird, and a desk chair is a more typical chair. The cognitive psychologists who study this sort of thing experimentally, do so under the heading of “typicality effects” or “prototype effects.”<span class="footnote">Eleanor Rosch, “Principles of Categorization,” in <em>Cognition and Categorization</em>, ed. Eleanor Rosch and Barbara B. Lloyd (Hillsdale, NJ: Lawrence Erlbaum, 1978).</span> For example, if you ask subjects to press a button to indicate “true” or “false” in response to statements like “A robin is a bird” or “A penguin is a bird,” reaction times are faster for more central examples.<span class="footnote">George Lakoff, <em>Women, Fire, and Dangerous Things: What Categories Reveal about the Mind</em> (Chicago: Chicago University Press, 1987).</span> Typicality measures correlate well using different investigative methods—reaction times are one example; you can also ask people to directly rate, on a scale of 1 to 10, how well an example (like a specific robin) fits a category (like “bird”).</p>
    <p>So we have a mental measure of typicality—which might, perhaps, function as a heuristic—but is there a corresponding bias we can use to pin it down?</p>
    <p>Well, which of these statements strikes you as more natural: “98 is approximately 100,” or “100 is approximately 98”? If you’re like most people, the first statement seems to make more sense.<span class="footnote">Jerrold Sadock, “Truth and Approximations,” <em>Papers from the Third Annual Meeting of the Berkeley Linguistics Society</em> (1977): 430–439.</span> For similar reasons, people asked to rate how similar Mexico is to the United States, gave consistently higher ratings than people asked to rate how similar the United States is to Mexico.<span class="footnote">Amos Tversky and Itamar Gati, “Studies of Similarity,” in <em>Cognition and Categorization</em>, ed. Eleanor Rosch and Barbara Lloyd (Hillsdale, NJ: Lawrence Erlbaum Associates, Inc., 1978), 79–98.</span></p>
    <p>And if that still seems harmless, a study by Rips showed that people were more likely to expect a disease would spread from robins to ducks on an island, than from ducks to robins.<span class="footnote">Lance J. Rips, “Inductive Judgments about Natural Categories,” <em>Journal of Verbal Learning and Verbal Behavior</em> 14 (1975): 665–681.</span> Now this is not a <em>logical</em> impossibility, but in a pragmatic sense, whatever difference separates a duck from a robin and would make a disease less likely to spread from a duck to a robin, must also be a difference between a robin and a duck, and would make a disease less likely to spread from a robin to a duck.</p>
    <p>Yes, you can come up with rationalizations, like “Well, there could be more neighboring species of the robins, which would make the disease more likely to spread initially, etc.,” but be careful not to try too hard to rationalize the probability ratings of subjects who didn’t even realize there was a comparison going on. And don’t forget that Mexico is more similar to the United States than the United States is to Mexico, and that 98 is closer to 100 than 100 is to 98. A simpler interpretation is that people are using the (demonstrated) similarity heuristic as a proxy for the probability that a disease spreads, and this heuristic is (demonstrably) asymmetrical.</p>
    <p>Kansas is unusually close to the center of the United States, and Alaska is unusually far from the center of the United States; so Kansas is probably closer to most places in the US and Alaska is probably farther. It does not follow, however, that Kansas is closer to Alaska than is Alaska to Kansas. But people seem to reason (metaphorically speaking) as if closeness is an inherent property of Kansas and distance is an inherent property of Alaska; so that Kansas is still close, even to Alaska; and Alaska is still distant, even from Kansas.</p>
    <p>So once again we see that Aristotle’s notion of categories—logical classes with membership determined by a collection of properties that are individually strictly necessary, and together strictly sufficient—is not a good model of human cognitive psychology. (Science’s view has changed somewhat over the last 2,350 years? Who would’ve thought?) We don’t even reason as if set membership is a true-or-false property: statements of set membership can be more or less true. (Note: This is <em>not</em> the same thing as being more or less probable.)</p>
    <p>One more reason not to pretend that you, or anyone else, is <em>really</em> going to treat words as Aristotelian logical classes.</p>
  </Chapter>;
}
