import Chapter from "@/components/Chapter/Chapter";

export default function WhatIsEvidence() {


  return <Chapter title={["What Is Evidence?"]}>
    <blockquote>
      <p>The sentence “snow is white” is <em>true</em> if and only if snow is white.</p>
      <p>—Alfred Tarski</p>
    </blockquote>
    <blockquote>
      <p>To say of what is, that it is, or of what is not, that it is not, is <em>true</em>.</p>
      <p>—Aristotle, Metaphysics IV</p>
    </blockquote>
    <p><span className="dropCap">I</span>f these two quotes don’t seem like a sufficient definition of “truth,” skip ahead to <em>The Simple Truth</em>. Here I’m going to talk about “evidence.” (I also intend to discuss beliefs-of-fact, not emotions or morality, as distinguished in <em>Feeling Rational</em>.)</p>
    <p>Walking along the street, your shoelaces come untied. Shortly thereafter, for some odd reason, you start <em>believing</em> your shoelaces are untied. Light leaves the Sun and strikes your shoelaces and bounces off; some photons enter the pupils of your eyes and strike your retina; the energy of the photons triggers neural impulses; the neural impulses are transmitted to the visual-processing areas of the brain; and there the optical information is processed and reconstructed into a 3D model that is recognized as an untied shoelace. There is a sequence of events, a chain of cause and effect, within the world and your brain, by which you end up believing what you believe. The final outcome of the process is a state of <em>mind</em> which mirrors the state of your actual <em>shoelaces</em>.</p>
    <p>What is <em>evidence</em>? It is an event entangled, by links of cause and effect, with whatever you want to know about. If the target of your inquiry is your shoelaces, for example, then the light entering your pupils is evidence entangled with your shoelaces. This should not be confused with the technical sense of “entanglement” used in physics—here I’m just talking about “entanglement” in the sense of two things that end up in correlated states because of the links of cause and effect between them.</p>
    <p>Not every influence creates the kind of “entanglement” required for evidence. It’s no help to have a machine that beeps when you enter winning lottery numbers, if the machine <em>also</em> beeps when you enter <em>losing</em> lottery numbers. The light reflected from your shoes would not be useful evidence about your shoelaces, if the photons ended up in the same physical state whether your shoelaces were tied or untied.</p>
    <p>To say it abstractly: For an event to be <em>evidence about</em> a target of inquiry, it has to happen <em>differently</em> in a way that’s entangled with the <em>different</em> possible states of the target. (To say it technically: There has to be Shannon mutual information between the evidential event and the target of inquiry, relative to your current state of uncertainty about both of them.)</p>
    <p>Entanglement can be contagious <em>when processed correctly</em>, which is why you need eyes and a brain. If photons reflect off your shoelaces and hit a rock, the rock won’t change much. The rock won’t reflect the shoelaces in any helpful way; it won’t be detectably different depending on whether your shoelaces were tied or untied. This is why rocks are not useful witnesses in court. A photographic film will contract shoelace-entanglement from the incoming photons, so that the photo can itself act as evidence. If your eyes and brain work correctly, you will become tangled up with your own shoelaces.</p>
    <p>This is why rationalists put such a heavy premium on the paradoxical-seeming claim that a belief is only really worthwhile if you could, in principle, be persuaded to believe otherwise. If your retina ended up in the same state regardless of what light entered it, you would be blind. Some belief systems, in a rather obvious trick to reinforce themselves, say that certain beliefs are only really worthwhile if you believe them <em>unconditionally</em>—no matter what you see, no matter what you think. Your brain is supposed to end up in the same state regardless. Hence the phrase, “blind faith.” If what you believe doesn’t depend on what you see, you’ve been blinded as effectively as by poking out your eyeballs.</p>
    <p>If your eyes and brain work correctly, your beliefs will end up entangled with the facts. <em>Rational thought produces beliefs which are themselves evidence</em>.</p>
    <p>If your tongue speaks truly, your rational beliefs, which are themselves evidence, can act as evidence for someone else. Entanglement can be transmitted through chains of cause and effect—and if you speak, and another hears, that too is cause and effect. When you say “My shoelaces are untied” over a cellphone, you’re sharing your entanglement with your shoelaces with a friend.</p>
    <p>Therefore rational beliefs are contagious, among honest folk who believe each other to be honest. And it’s why a claim that your beliefs are <em>not</em> contagious—that you believe for private reasons which are not transmissible— is so suspicious. If your beliefs are entangled with reality, they <em>should</em> be contagious among honest folk.</p>
    <p>If your model of reality suggests that the outputs of your thought processes should <em>not</em> be contagious to others, then your model says that your beliefs are not themselves evidence, meaning they are not entangled with reality. You should apply a reflective correction, and stop believing.</p>
    <p>Indeed, if you <em>feel</em>, on a <em>gut</em> level, what this all <em>means</em>, you will <em>automatically</em> stop believing. Because “my belief is not entangled with reality” means “my belief is not accurate.” As soon as you stop believing “ ‘snow is white’ is true,” you should (automatically!) stop believing “snow is white,” or something is very wrong.</p>
    <p>So go ahead and explain why the kind of thought processes you use systematically produce beliefs that mirror reality. Explain why you think you’re <em>rational</em>. Why you think that, using thought processes like the ones you use, minds will end up believing “snow is white” if and only if snow is white. If you don’t believe that the outputs of your thought processes are entangled with reality, why do you believe the outputs of your thought processes? It’s the same thing, or it should be.</p>
  </Chapter>
}