import Chapter from "@/components/Chapter/Chapter";

export default function YourStrengthAsARationalist() {


  return <Chapter title={["Your Strength", "as a Rationalist"]}>
    <p><span className="dropCap">T</span>he following happened to me in an IRC chatroom, long enough ago that I was still hanging around in IRC chatrooms. Time has fuzzed the memory and my report may be imprecise.</p>
    <p>So there I was, in an IRC chatroom, when someone reports that a friend of his needs medical advice. His friend says that he’s been having sudden chest pains, so he called an ambulance, and the ambulance showed up, but the paramedics told him it was nothing, and left, and now the chest pains are getting worse. What should his friend do?</p>
    <p>I was confused by this story. I remembered reading about homeless people in New York who would call ambulances just to be taken someplace warm, and how the paramedics always had to take them to the emergency room, even on the 27th iteration. Because if they didn’t, the ambulance company could be sued for lots and lots of money. Likewise, emergency rooms are legally obligated to treat anyone, regardless of ability to pay. (And the hospital absorbs the costs, which are enormous, so hospitals are closing their emergency rooms… It makes you wonder what’s the point of having economists if we’re just going to ignore them.) So I didn’t quite understand how the described events could have happened. <em>Anyone</em> reporting sudden chest pains should have been hauled off by an ambulance instantly.</p>
    <p>And this is where I fell down as a rationalist. I remembered several occasions where my doctor would completely fail to panic at the report of symptoms that seemed, to me, very alarming. And the Medical Establishment was always right. Every single time. I had chest pains myself, at one point, and the doctor patiently explained to me that I was describing chest muscle pain, not a heart attack. So I said into the IRC channel, “Well, if the paramedics told your friend it was nothing, it must <em>really be</em> nothing—they’d have hauled him off if there was the tiniest chance of serious trouble.”</p>
    <p>Thus I managed to explain the story within my existing model, though the fit still felt a little forced…</p>
    <p>Later on, the fellow comes back into the IRC chatroom and says his friend made the whole thing up. Evidently this was not one of his more reliable friends.</p>
    <p>I should have realized, perhaps, that an unknown acquaintance of an acquaintance in an IRC channel might be less reliable than a published journal article. Alas, belief is easier than disbelief; we believe instinctively, but disbelief requires a conscious effort.<span className="footnote">Daniel T. Gilbert, Romin W. Tafarodi, and Patrick S. Malone, “You Can’t Not Believe Everything You Read,” <em>Journal of Personality and Social Psychology</em> 65 (2 1993): 221–233, doi:10.1037/0022-3514.65.2.221.</span></p>
    <p>So instead, by dint of mighty straining, I forced my model of reality to explain an anomaly that <em>never actually happened</em>. And I <em>knew</em> how embarrassing this was. I <em>knew</em> that the usefulness of a model is not what it can explain, but what it can’t. A hypothesis that forbids nothing, permits everything, and thereby fails to constrain anticipation.</p>
    <p>Your strength as a rationalist is your ability to be more confused by fiction than by reality. If you are equally good at explaining any outcome, you have zero knowledge.</p>
    <p>We are all weak, from time to time; the sad part is that I <em>could</em> have been stronger. I had all the information I needed to arrive at the correct answer, I even <em>noticed</em> the problem, and then I ignored it. My feeling of confusion was a Clue, and I threw my Clue away.</p>
    <p>I should have paid more attention to that sensation of <em>still feels a little forced</em>. It’s one of the most important feelings a truthseeker can have, a part of your strength as a rationalist. It is a design flaw in human cognition that this sensation manifests as a quiet strain in the back of your mind, instead of a wailing alarm siren and a glowing neon sign reading:</p>
    <p style={{ textAlign: "center", fontSize: "1.618em", lineHeight: "1.618em", fontFamily: "var(--secondaryFont)" }}>Either Your Model Is False Or This Story Is Wrong.</p>
  </Chapter>
}