import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function CanHumanismMatchReligionsOutput() {
  return <Chapter title={["Can Humanism Match Religion's Output?"]}>


    <p><span className="dropCap tall">P</span>erhaps the single largest <em>voluntary</em> institution of our modern world—bound together not by police and taxation, not by salaries and managers, but by voluntary donations flowing from its members—is the Catholic Church.</p>
    <p>It’s too large to be held together by individual negotiations, like a group task in a hunter-gatherer band. But in a larger world with more people to be infected and faster transmission, we can expect more virulent memes. The Old Testament doesn’t talk about Hell, but the New Testament does. The Catholic Church is held together by affective death spirals—around the ideas, the institutions, and the leaders. By promises of eternal happiness and eternal damnation—theologians don’t really believe that stuff, but many ordinary Catholics do. By simple conformity of people meeting in person at a Church and being subjected to peer pressure. Et cetera.</p>
    <p>We who have the temerity to call ourselves “rationalists” think ourselves too good for such communal bindings.</p>
    <p>And so anyone with a <em>simple</em> and <em>obvious</em> charitable project—responding with food and shelter to a tidal wave in Thailand, say—would be better off by <em>far</em> pleading with the Pope to mobilize the Catholics, rather than with Richard Dawkins to mobilize the atheists.</p>
    <p><em>For so long as this is true</em>, any increase in atheism at the expense of Catholicism will be something of a hollow victory, regardless of all other benefits.</p>
    <p>True, the Catholic Church also goes around opposing the use of condoms in AIDS-ravaged Africa. True, they waste huge amounts of the money they raise on all that religious stuff. Indulging in unclear thinking is not harmless; prayer comes with a price.</p>
    <p>To refrain from doing damaging things <em>is</em> a true victory for a rationalist…</p>
    <p>Unless it is your <em>only</em> victory, in which case it seems a little empty.</p>
    <p>If you <em>discount all harm</em> done by the Catholic Church, and look <em>only</em> at the good… then does the average Catholic do more <em>gross</em> good than the average atheist, just by virtue of being more active?</p>
    <p>Perhaps if you are wiser but less motivated, you can search out interventions of high efficiency and purchase utilons on the cheap… But there are few of us who <em>really</em> do that, as opposed to planning to do it someday.</p>
    <p>Now you might at this point throw up your hands, saying: “For so long as we don’t have direct control over our brain’s motivational circuitry, it’s not realistic to expect a rationalist to be as strongly motivated as someone who genuinely believes that they’ll burn eternally in hell if they don’t obey.”</p>
    <p>This is a fair point. Any folk theorem to the effect that a rational agent should do at least as well as a non-rational agent will rely on the assumption that the rational agent can always just implement whatever “irrational” policy is observed to win. But if you can’t <em>choose</em> to have unlimited mental energy, then it may be that some false beliefs are, in cold fact, more strongly motivating than any available true beliefs. And if we all generally suffer from altruistic akrasia, being unable to bring ourselves to help as much as we think we should, then it is possible for the God-fearing to win the contest of altruistic output.</p>
    <p>But though it is a motivated continuation, let us consider this question a little further.</p>
    <p>Even the fear of hell is not a perfect motivator. Human beings are not given so much slack on evolution’s leash; we can resist motivation for a short time, but then we run out of mental energy (hat tip: infotropism). Even believing that you’ll go to hell does not change this brute fact about brain circuitry. So the religious sin, and then are tormented by thoughts of going to hell, in much the same way that smokers reproach themselves for being unable to quit.</p>
    <p>If a group of rationalists cared <em>a lot</em> about something… who says they wouldn’t be able to match the real, de-facto output of a believing Catholic? The stakes might not be “infinite” happiness or “eternal” damnation, but of course the brain can’t visualize 3↑↑↑3, let alone infinity. Who says that the actual quantity of caring neurotransmitters discharged by the brain (as ’twere) has to be so much less for “the growth and flowering of humankind” or even “tidal-wave-stricken Thais,” than for “eternal happiness in Heaven”? Anything involving more than 100 people is going to involve utilities too large to visualize. And there are all sorts of other standard biases at work here; knowing about them might be good for a bonus as well, one hopes?</p>
    <p>Cognitive-behavioral therapy and Zen meditation are two mental disciplines experimentally shown to yield real improvements. It is not the area of the art I’ve focused on developing, but then I don’t have a real martial art of rationality in back of me. If you combine a purpose genuinely worth caring about with discipline extracted from CBT and Zen meditation, then who says rationalists can’t keep up? Or even more generally: if we have an evidence-based art of fighting akrasia, with experiments to see what actually works, then who says we’ve got to be less motivated than some disorganized mind that fears God’s wrath?</p>
    <p>Still… that’s a further-future speculation that it might be possible to develop an art that doesn’t presently exist. It’s not a technique I can use right now. I present it just to illustrate the idea of <em>not giving up so fast on rationality</em>: Understanding what’s going wrong, trying intelligently to fix it, and gathering evidence on whether it worked—this is a powerful idiom, not to be lightly dismissed upon sighting the first disadvantage.</p>
    <p>Really, I suspect that what’s going on here has less to do with the motivating power of eternal damnation, and a lot more to do with the motivating power of <em>physically meeting</em> other people who share your cause. The power, in other words, of being physically present at church and having religious neighbors.</p>
    <p>This is a problem for the rationalist community in its present stage of growth, because we are rare and geographically distributed way the hell all over the place. If all the readers of <em>Less Wrong</em> lived within a five-mile radius of each other, I bet we’d get a lot more done, not for reasons of <em>coordination</em> but just sheer <em>motivation</em>.</p>
    <p>I’ll write later about some long-term, starry-eyed, idealistic thoughts on this particular problem. Shorter-term solutions that don’t rely on our increasing our numbers by a factor of 100 would be better. I wonder in particular whether the best modern videoconferencing software would provide some of the motivating effect of meeting someone in person; I suspect the answer is “no” but it might be worth trying.</p>
    <p>Meanwhile… in the short term, we’re stuck fighting akrasia mostly without the reinforcing physical presense of other people who care. I want to say something like “This is difficult, but it <em>can</em> be done,” except I’m not sure that’s even true.</p>
    <p>I suspect that the <em>largest</em> step rationalists could take toward matching the per-capita power output of the Catholic Church would be to have regular physical meetings of people contributing to the same task—just for purposes of motivation.</p>
    <p>In the absence of that…</p>
    <p>We could try for a group norm of being openly allowed—nay, applauded— for caring strongly about something. And a group norm of being expected to do something useful with your life—contribute your part to cleaning up this world. Religion doesn’t really emphasize the getting-things-<em>done</em> aspect as much.</p>
    <p>And if rationalists could match just <em>half</em> the average altruistic effort output per Catholic, then I don’t think it’s <em>remotely</em> unrealistic to suppose that with better targeting on more efficient causes, the modal rationalist could get twice as much done.</p>
    <p>How much of its earnings does the Catholic Church spend on all that useless religious stuff instead of actually helping people? More than 50%, I would venture. So then we could say—with a certain irony, though that’s not quite the spirit in which we should be doing things—that we should try to propagate a group norm of donating a minimum of 5% of income to <em>real</em> causes. (10% being the usual suggested minimum religious tithe.) And then there’s the art of picking causes for which expected utilons are orders of magnitude cheaper (for so long as the inefficient market in utilons lasts).</p>
    <p>But long before we can begin to dream of any such boast, we secular humanists need to work on at least <em>matching</em> the per capita benevolent output of the worshippers.</p>

  </Chapter>;
}