import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function GoForthAndCreateTheArt() {
  return <Chapter title={["Go Forth and Create the Art!"]}>

    <p><span className="dropCap">I</span> have said a thing or two about rationality, these past months. I have said a thing or two about how to untangle questions that have become confused, and how to tell the difference between real reasoning and fake reasoning, and the will to become stronger that leads you to try before you flee; I have said something about doing the impossible.</p>
    <p>And these are all techniques that I developed in the course of my own projects—which is why there is so much about cognitive reductionism, say— and it is possible that your mileage may vary in trying to apply it yourself. The one’s mileage may vary. Still, those wandering about asking “But what good is it?” might consider rereading some of the earlier essays; knowing about e.g. the conjunction fallacy, and how to spot it in an argument, hardly seems esoteric. Understanding why motivated skepticism is bad for you can constitute the whole difference, I suspect, between a smart person who ends up smart and a smart person who ends up stupid. Affective death spirals consume <em>many</em> among the unwary…</p>
    <p>Yet there is, I think, more <em>absent</em> than <em>present</em> in this “art of rationality”— defeating akrasia and coordinating groups are two of the deficits I feel most keenly. I’ve concentrated more heavily on epistemic rationality than instrumental rationality, in general. And then there’s training, teaching, verification, and becoming a proper experimental science based on that. And if you generalize a bit further, then <em>building the Art</em> could also be taken to include issues like developing better introductory literature, developing better slogans for public relations, establishing common cause with other Enlightenment subtasks, analyzing and addressing the gender imbalance problem… But those small pieces of rationality that I’ve set out… I <em>hope</em>… just maybe…</p>
    <p>I suspect—you could even call it a guess—that there is a <em>barrier to getting started</em>, in this matter of rationality. Where by default, in the beginning, you don’t have enough to build on. Indeed so little that you don’t have a clue that more exists, that there is an Art to be found. And if you do begin to sense that more is possible—then you may just <em>instantaneously</em> go wrong. As David Stove observes, most “great thinkers” in philosophy, e.g., Hegel, are properly objects of pity.<span class="footnote">David Charles Stove, <em>The Plato Cult and Other Philosophical Follies</em> (Cambridge University Press, 1991).</span> That’s what happens by default to anyone who sets out to develop the art of thinking; they develop fake answers.</p>
    <p>When you try to develop part of the human art of thinking… then you are doing something <em>not too dissimilar</em> to what I was doing over in Artificial Intelligence. You will be tempted by fake explanations of the mind, fake accounts of causality, mysterious holy words, and the amazing idea that solves everything.</p>
    <p>It’s not that the particular, epistemic, fake-detecting methods that I use are so good for every <em>particular</em> problem; but they seem like they might be helpful for discriminating good and bad <em>systems of thinking</em>.</p>
    <p>I hope that someone who learns the part of the Art that I’ve set down here will not <em>instantaneously</em> and <em>automatically</em> go wrong if they start asking themselves, “How should people think, in order to solve new problem <em>X</em> that I’m working on?” They will not immediately run away; they will not just make stuff up at random; they may be moved to consult the literature in experimental psychology; they will not automatically go into an affective death spiral around their Brilliant Idea; they will have some idea of what distinguishes a fake explanation from a real one. They will get a saving throw.</p>
    <p>It’s this sort of barrier, <em>perhaps</em>, that prevents people from <em>beginning</em> to develop an art of rationality, if they are not already rational.</p>
    <p>And so instead they… go off and invent Freudian psychoanalysis. Or a new religion. Or something. That’s what happens by <em>default</em>, when people start thinking about thinking.</p>
    <p>I hope that the part of the Art I have set down, as incomplete as it may be, can surpass that preliminary barrier—give people a base to build on; give them an idea that an Art exists, and somewhat of how it ought to be developed; and give them at least a <em>saving throw</em> before they <em>instantaneously</em> go astray.</p>
    <p>That’s my dream—that this highly-specialized-seeming art of answering confused questions may be some of what is needed, in the very beginning, <em>to go and complete the rest</em>.</p>
    <p>A task which I am leaving to <em>you</em>. Probably, anyway. I make no promises as to where my attention may turn in the future. But y’know, there <em>are</em> certain other things I need to do. Even if I develop yet more Art by accident, it may be that I will not have the time to write any of it up.</p>
    <p>Beyond all that I have said of fake answers and traps, there are two things I would like you to keep in mind.</p>
    <p>The first—that I drew on multiple sources to create my Art. I read many different authors, many different experiments, used analogies from many different fields. <em>You</em> will need to draw on multiple sources to create <em>your</em> portion of the Art. You should not be getting all your rationality from one author— though there might be, perhaps, a certain centralized website, where you went to post the links and papers that struck you as really important. And a maturing Art will need to draw from multiple sources. To the best of my knowledge there is <em>no</em> true science that draws its strength from only one person. To the best of my knowledge that is <em>strictly</em> an idiom of cults. A true science may have its heroes, it may even have its lonely defiant heroes, but it <em>will have more than one</em>.</p>
    <p>The second—that I created my Art in the course of <em>trying to do some particular thing</em> that animated all my efforts. Maybe I’m being too idealistic—maybe thinking too much of the way the world <em>should</em> work—but even so, I somewhat suspect that you couldn’t develop the Art <em>just</em> by sitting around thinking to yourself, “Now how can I fight that akrasia thingy?” You’d develop the rest of the Art in the course of trying to <em>do something</em>. Maybe even—if I’m not overgeneralizing from my own history—some task difficult enough to strain and break your old understanding and force you to reinvent a few things. But maybe I’m wrong, and the next leg of the work will be done by direct, specific investigation of “rationality,” without any need of a specific application considered more important.</p>
    <p>A past attempt of mine to describe this principle, in terms of maintaining a secret identity or day job in which one doesn’t teach rationality, was roundly rejected by my audience. Maybe “leave the house” would be more appropriate? It <em>sounds</em> to me like a really good, healthy idea. Still—perhaps I am deceived. We shall see where the next pieces of the Art do, in fact, come from.</p>
    <p>I have striven for a long time now to convey, pass on, share a piece of the strange thing I touched, which seems to me so precious. And I’m not sure that I ever said the central rhythm into words. Maybe you can find it by listening to the notes. I can say these words but not the rule that generates them, or the rule behind the rule; one can only hope that by <em>using</em> the ideas, perhaps, similar machinery might be born inside you. Remember that <em>all</em> human efforts at learning arcana slide by default into passwords, hymns, and floating assertions.</p>
    <p>I have striven for a long time now to convey my Art. Mostly without success, before this present effort. Earlier I made efforts only in passing, and got, perhaps, as much success as I deserved. Like throwing pebbles in a pond, that generate a few ripples, and then fade away… This time I put some back into it, and heaved a large rock. Time will tell if it was large enough—if I really <em>disturbed</em> anyone deeply enough that the waves of the impact will continue under their own motion. Time will tell if I have created anything that moves under its own power.</p>
    <p>I want people to go forth, but also to return. Or maybe even to go forth and stay simultaneously, because this is the Internet and we can get away with that sort of thing; I’ve learned some interesting things on <em>Less Wrong</em>, lately, and if continuing motivation over years is any sort of problem, talking to others (or even <em>seeing</em> that others are also trying) does often help.</p>
    <p>But at any rate, if I have affected you at all, then I hope you will go forth and confront challenges, and achieve somewhere beyond your armchair, and create new Art; and then, remembering whence you came, radio back to tell others what you learned.</p>


  </Chapter>;
}