import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function MoneyTheUnitOfCaring() {
  return <Chapter title={["Money: The Unit of Caring"]}>


    <p><span className="dropCap">S</span>teve Omohundro has suggested a folk theorem to the effect that, within the interior of any approximately rational self-modifying agent, the marginal benefit of investing additional resources in anything ought to be about equal. Or, to put it a bit more exactly, shifting a unit of resource between any two tasks should produce no increase in expected utility, relative to the agent’s utility function and its probabilistic expectations about its own algorithms.</p>
    <p>This resource balance principle implies that—over a very wide range of approximately rational systems, including even the interior of a self-modifying mind—there will exist some common currency of expected utilons, by which everything worth doing can be measured.</p>
    <p>In our society, this common currency of expected utilons is called “money.” It is the measure of how much society cares about something.</p>
    <p>This is a brutal yet obvious point, which many are motivated to deny.</p>
    <p>With this audience, I hope, I can simply state it and move on. It’s not as if you thought “society” was intelligent, benevolent, and sane up until this point, right?</p>
    <p>I say this to make a certain point held in common across many good causes. Any charitable institution you’ve ever had a kind word for, certainly <em>wishes</em> you would appreciate this point, whether or not they’ve ever said anything out loud. For I have listened to others in the nonprofit world, and I know that I am not speaking only for myself here…</p>
    <p>Many people, when they see something that they think is worth doing, would like to volunteer a few hours of spare time, or maybe mail in a five-year-old laptop and some canned goods, or walk in a march somewhere, but at any rate, not spend <em>money</em>.</p>
    <p>Believe me, I understand the feeling. Every time I spend money I feel like I’m losing hit points. That’s the problem with having a unified quantity describing your net worth: Seeing that number go down is not a pleasant feeling, even though it has to fluctuate in the ordinary course of your existence. There ought to be a fun-theoretic principle against it.</p>
    <p>But, well…</p>
    <p>There <em>is</em> this very, very old puzzle/observation in economics about the lawyer who spends an hour volunteering at the soup kitchen, instead of working an extra hour and donating the money to hire someone to work for five hours at the soup kitchen.</p>
    <p>There’s this thing called “Ricardo’s Law of Comparative Advantage.” There’s this idea called “professional specialization.” There’s this notion of “economies of scale.” There’s this concept of “gains from trade.” The whole reason why we have money is to realize the <em>tremendous</em> gains possible from each of us doing what we do <em>best</em>.</p>
    <p>This is what grownups do. This is what you do when you want something to actually get <em>done</em>. You use <em>money</em> to employ <em>full-time specialists</em>.</p>
    <p>Yes, people are sometimes limited in their ability to trade time for money (underemployed), so that it is better for them if they can directly donate that which they would usually trade for money. <em>If</em> the soup kitchen <em>needed</em> a lawyer, and the lawyer donated a <em>large contiguous high-priority</em> block of lawyering, then <em>that</em> sort of volunteering makes sense—that’s the same <em>specialized</em> capability the lawyer ordinarily trades for money. But “volunteering” just one hour of legal work, constantly delayed, spread across three weeks in casual minutes between other jobs? This is not the way something gets done <em>when anyone actually cares about it</em>, or to state it near-equivalently, <em>when money is involved</em>.</p>
    <p>To the extent that individuals fail to grasp this principle on a <em>gut level</em>, they may think that the use of money is somehow <em>optional</em> in the pursuit of things that merely seem <em>morally</em> desirable—as opposed to tasks like feeding ourselves, whose desirability seems to be treated oddly differently. This factor may be sufficient <em>by itself</em> to prevent us from pursuing our collective common interest in groups larger than 40 people.</p>
    <p>Economies of trade and professional specialization are not just vaguely good yet unnatural-sounding ideas, <em>they are the only way that anything ever gets done in this world</em>. Money is not pieces of paper, it is the <em>common currency of caring</em>.</p>
    <p>Hence the old saying: “Money makes the world go ‘round, love barely keeps it from blowing up.”</p>
    <p>Now, we do have the problem of akrasia—of not being able to do what we’ve decided to do—which is a part of the art of rationality that I hope someone else will develop; I specialize more in the impossible questions business. And yes, spending money is more painful than volunteering, because you can see the bank account number go down, whereas the remaining hours of our span are not visibly numbered. But when it comes time to feed yourself, do you think, “Hm, maybe I should try raising my own cattle, that’s less painful than spending money on beef?” Not everything can get done <em>without</em> invoking Ricardo’s Law; and on the other end of that trade are people who feel just the same pain at the thought of having less money.</p>
    <p>It does seem to me offhand that there ought to be things doable to diminish the pain of losing hit points, and to increase the felt strength of the connection from donating money to “I did a good thing!” Some of that I am trying to accomplish right now, by emphasizing the true nature and power of money; and by inveighing against the poisonous meme saying that someone who gives mere money must not care enough to get personally involved. This is a mere reflection of a mind that doesn’t understand the post-hunter-gatherer concept of a market economy. The act of donating money is not the momentary act of writing the check; it is the act of every hour you spent to earn the money to write that check—just as though you worked at the charity itself <em>in your professional capacity</em>, at maximum, grownup efficiency.</p>
    <p>If the lawyer needs to work an hour at the soup kitchen to keep themselves motivated and remind themselves why they’re doing what they’re doing, <em>that’s fine</em>. But they should <em>also</em> be donating some of the hours they worked at the office, because that is the power of professional specialization. One might consider the check as buying the right to volunteer at the soup kitchen, or validating the time spent at the soup kitchen. More on this later.</p>
    <p>To a first approximation, money is the unit of caring up to a positive scalar factor—the unit of relative caring. Some people are frugal and spend less money on <em>everything</em>; but if you would, in fact, spend $5 on a burrito, then whatever you will not spend $5 on, you care about <em>less than</em> you care about the burrito. If you don’t spend two months’ salary on a diamond ring, it doesn’t mean you don’t love your Significant Other. (“De Beers: It’s Just A Rock.”) But conversely, if you’re <em>always</em> reluctant to spend <em>any</em> money on your Significant Other, and yet seem to have no emotional problems with spending $1,000 on a flat-screen TV, then yes, this <em>does</em> say something about your relative values.</p>
    <p>Yes, frugality is a virtue. Yes, spending money hurts. But in the end, if you are never willing to spend any units of caring, it means you don’t care.</p>

  </Chapter>;
}