import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function PracticalAdviceBackedByDeepTheories() {
  return <Chapter title={["Practical Advice Backed by Deep Theories"]}>


    <p><span className="dropCap">O</span>nce upon a time, Seth Roberts took a European vacation and found that he started losing weight while drinking unfamiliar-tasting caloric fruit juices.</p>
    <p>Now suppose Roberts had not known, and never did know, anything about metabolic set points or flavor-calorie associations—all this high-falutin’ scientific experimental research that had been done on rats and occasionally humans.</p>
    <p>He would have posted to his blog, “Gosh, everyone! You should try these amazing fruit juices that are making me lose weight!” And that would have been the end of it. Some people would have tried it, it would have worked <em>temporarily</em> for some of them (until the flavor-calorie association kicked in) and there never would have been a Shangri-La Diet <em>per se</em>.</p>
    <p>The existing Shangri-La Diet is visibly incomplete—for some people, like me, it doesn’t seem to work, and there is no apparent reason for this or any logic permitting it. But the reason why as many people have benefited as they have—the reason why there was more than just one more blog post describing a trick that seemed to work for one person and didn’t work for anyone else—is that Roberts <em>knew the experimental science that let him interpret what he was seeing, in terms of deep factors that actually did exist</em>.</p>
    <p>One of the pieces of advice on <em>Overcoming Bias</em> / <em>Less Wrong</em> that was frequently cited as the most important thing learned, was the idea of “the bottom line”—that once a conclusion is written in your mind, it is already true or already false, already wise or already stupid, and no amount of later argument can change that except by changing the conclusion. And this ties directly into another oft-cited most important thing, which is the idea of “engines of cognition,” minds as mapping engines that require evidence as fuel.</p>
    <p>Suppose I had merely written one more blog post that said, “You know, you really should be more open to changing your mind—it’s pretty important—and oh yes, you should pay attention to the evidence too.” This would not have been as useful. Not just because it was <em>less persuasive</em>, but because the <em>actual operations</em> would have been much less clear without the explicit theory backing it up. What constitutes <em>evidence</em>, for example? Is it anything that seems like a forceful argument? Having an explicit probability theory and an explicit causal account of what makes reasoning effective makes a <em>large</em> difference in the forcefulness and implementational details of the old advice to “Keep an open mind and pay attention to the evidence.”</p>
    <p>It is also important to realize that <em>causal theories</em> are much more likely to be true when they are picked up from a science textbook than when invented on the fly—it is very easy to invent cognitive structures that look like causal theories but are not even anticipation-controlling, let alone true.</p>
    <p>This is the signature style I want to convey from all those essays that entangled cognitive science experiments and probability theory and epistemology with the practical advice—that practical advice actually becomes practically more powerful if you go out and read up on cognitive science experiments, or probability theory, or even materialist epistemology, and <em>realize what you’re seeing</em>. This is the brand that can distinguish <em>Less Wrong</em> from ten thousand other blogs purporting to offer advice.</p>
    <p>I could tell you, “You know, how much you’re satisfied with your food probably depends more on the quality of the food than on how much of it you eat.” And you would read it and forget about it, and the impulse to finish off a whole plate would still feel just as strong. But if I tell you about scope insensitivity, and duration neglect and the Peak–end rule, you are suddenly aware in a very concrete way, looking at your plate, that you will form almost exactly the same retrospective memory whether your portion size is large or small; you now possess a deep theory about the <em>rules</em> governing your memory, and you know that this is what the rules say. (You also know to save the dessert for last.)</p>
    <p>I want to hear how I can overcome akrasia—how I can have more willpower, or get more done with less mental pain. But there are ten thousand people purporting to give advice on this, and for the most part, it is on the level of that alternate Seth Roberts who just tells people about the amazing effects of drinking fruit juice. Or actually, somewhat worse than that—it’s people trying to describe internal mental levers that they pulled, for which there are no standard words, and which they do not actually know how to point to. See also the illusion of transparency, inferential distance, and double illusion of transparency. (Notice how “You overestimate how much you’re explaining and your listeners overestimate how much they’re hearing” becomes <em>much more forceful</em> as advice, after I back it up with a cognitive science experiment and some evolutionary psychology?)</p>
    <p>I think that the advice I <em>need</em> is from someone who reads up on a whole lot of experimental psychology dealing with willpower, mental conflicts, ego depletion, preference reversals, hyperbolic discounting, the breakdown of the self, picoeconomics, et cetera, and who, in the process of overcoming their own akrasia, manages to understand what they did in <em>truly general terms</em>—thanks to experiments that give them a vocabulary of cognitive phenomena that <em>actually exist</em>, as opposed to phenomena they just made up. And moreover, someone who can <em>explain</em> what they did to someone else, thanks again to the experimental and theoretical vocabulary that lets them point to replicable experiments that ground the ideas in very concrete results, or mathematically clear ideas.</p>
    <p>Note the grade of increasing difficulty in citing:</p>
    <ul>
      <li><em>Concrete experimental results</em> (for which one need merely consult a paper, hopefully one that reported <em>p</em> &lt; 0.01 because <em>p</em> &lt; 0.05 may fail to replicate);</li>
      <li><em>Causal accounts that are actually true</em> (which may be most reliably obtained by looking for the theories that are used by a majority within a given science);</li>
      <li><em>Math validly interpreted</em> (on which I have trouble offering useful advice because so much of my own math talent is intuition that kicks in before I get a chance to deliberate).</li>
    </ul>
    <p>If you don’t know who to trust, or you don’t trust yourself, you should concentrate on experimental results to start with, move on to thinking in terms of causal theories that are widely used within a science, and dip your toes into math and epistemology with extreme caution.</p>
    <p>But practical advice really, really <em>does</em> become a lot more powerful when it’s backed up by <em>concrete experimental results</em>, <em>causal accounts that are actually true</em>, and <em>math validly interpreted</em>.</p>

  </Chapter>;
}