import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function TheSinOfUnderconfidence() {
  return <Chapter title={["The Sin of Underconfidence"]}>

    <p><span className="dropCap">T</span>here are three great besetting sins of rationalists in particular, and the third of these is underconfidence. Michael Vassar regularly accuses me of this sin, which makes him unique among the entire population of the Earth.</p>
    <p>But he’s actually quite right to worry, and I worry too, and any adept rationalist will probably spend a fair amount of time worying about it. When subjects know about a bias or are warned about a bias, <em>overcorrection</em> is not unheard of as an experimental result. That’s what makes a lot of cognitive subtasks so troublesome—you know you’re biased but you’re not sure <em>how much</em>, and you don’t know if you’re correcting <em>enough</em>—and so perhaps you ought to correct a little more, and then a little more, but is <em>that</em> enough? Or have you, perhaps, far overshot? Are you now perhaps worse off than if you hadn’t tried any correction?</p>
    <p>You contemplate the matter, feeling more and more lost, and the very task of estimation begins to feel increasingly futile…</p>
    <p>And when it comes to the particular questions of <em>confidence</em>, <em>overconfidence</em>, and <em>underconfidence</em>—being interpreted now in the broader sense, not just calibrated confidence intervals—then there is a natural tendency to cast overconfidence as the <em>sin</em> of pride, out of that <em>other</em> list which never warned against the improper use of humility or the abuse of doubt. To place yourself too high—to overreach your proper place—to think too much of yourself—to put yourself forward—to put down your fellows by implicit comparison—and the consequences of humiliation and being cast down, perhaps publicly—are these not loathesome and fearsome things?</p>
    <p>To be too <em>modest</em>—seems lighter by comparison; it wouldn’t be so humiliating to be called on it publicly. Indeed, finding out that you’re better than you imagined might come as a warm surprise; and to put yourself down, and others implicitly above, has a positive tinge of <em>niceness</em> about it. It’s the sort of thing that Gandalf would do.</p>
    <p>So if you have learned a thousand ways that humans fall into error and read a hundred experimental results in which anonymous subjects are humiliated of their overconfidence—heck, even if you’ve just read a couple of dozen—and you don’t <em>know</em> exactly how overconfident you are—then yes, you might genuinely be in danger of nudging yourself a step too far down.</p>
    <p>I have no perfect formula to give you that will counteract this. But I have an item or two of advice.</p>
    <p>What is the <em>danger</em> of underconfidence?</p>
    <p>Passing up opportunities. Not doing things you could have done, but didn’t try (hard enough).</p>
    <p>So here’s a first item of advice: If there’s a way to <em>find out</em> how good you are, the thing to do is <em>test</em> it. <em>A hypothesis affords testing</em>; hypotheses about your own abilities likewise. Once upon a time it seemed to me that I ought to be able to win at the AI-Box Experiment; and it seemed like a very doubtful and hubristic thought; so I tested it. Then later it seemed to me that I might be able to win even with large sums of money at stake, and I tested that, but I only won one time out of three. So that was the limit of my ability at that time, and it was not necessary to argue myself upward or downward, because I could just <em>test</em> it.</p>
    <p>One of the chief ways that smart people end up stupid is by getting <em>so used to winning</em> that they stick to places where they <em>know they can win</em>—meaning that they never stretch their abilities, they never try anything difficult.</p>
    <p>It is said that this is linked to defining yourself in terms of your “intelligence” rather than “effort,” because then winning <em>easily</em> is a sign of your “intelligence,” where failing on a hard problem could have been interpreted in terms of a good effort.</p>
    <p>Now, I am not quite sure this is how an adept rationalist should think about these things: rationality <em>is</em> systematized winning and trying to try seems like a path to failure. I would put it this way: A hypothesis affords testing! If you <em>don’t know</em> whether you’ll win on a hard problem—then <em>challenge your rationality</em> to <em>discover</em> your current level. I don’t usually hold with congratulating yourself on having tried—it seems like a bad mental habit to me—but surely <em>not</em> trying is even <em>worse</em>. If you have cultivated a general habit of confronting challenges, and won on at least <em>some</em> of them, then you may, perhaps, think to yourself, “I did keep up my habit of confronting challenges, and will do so next time as well.” You may also think to yourself “I have gained valuable information about my current level and where I need improvement,” so long as you properly complete the thought, “I shall try not to gain this same valuable information again next time.”</p>
    <p>If you win <em>every</em> time, it means you aren’t stretching yourself enough. But you <em>should</em> seriously try to win every time. And if you console yourself too much for failure, you lose your winning spirit and become a scrub.</p>
    <p>When I try to imagine what a fictional master of the Competitive Conspiracy would say about this, it comes out something like: “It’s <em>not</em> okay to lose. But the <em>hurt</em> of losing is not something so scary that you should flee the challenge for fear of it. It’s not so scary that you have to carefully avoid feeling it, or refuse to admit that you lost and lost hard. Losing is <em>supposed</em> to hurt. If it didn’t hurt you wouldn’t be a Competitor. And there’s <em>no</em> Competitor who <em>never</em> knows the pain of losing. Now get out there and <em>win</em>.”</p>
    <p>Cultivate a habit of confronting challenges—not the ones that can kill you outright, perhaps, but perhaps ones that can potentially <em>humiliate</em> you. I recently read of a certain theist that he had defeated Christopher Hitchens in a debate (severely so; this was said by atheists). And so I wrote at once to the Bloggingheads folks and asked if they could arrange a debate. This seemed like someone I wanted to test myself against. Also, it was said by them that Christopher Hitchens should have watched the theist’s earlier debates and been prepared, so I decided <em>not</em> to do that, because I think I should be able to handle damn near anything on the fly, and I desire to learn whether this thought is correct; and I am willing to risk public humiliation to find out. Note that this is <em>not</em> self-handicapping in the classic sense—if the debate is indeed arranged (I haven’t yet heard back), and I do not prepare, and I fail, then I do lose those stakes of myself that I have put up; I gain information about my limits; I have <em>not</em> given myself anything I consider an excuse for losing.</p>
    <p>Of course this is only a way to think when you really <em>are</em> confronting a challenge just to test yourself, and not because you have to win at any cost. In <em>that</em> case you make everything as easy for yourself as possible. To do otherwise would be <em>spectacular</em> overconfidence, even if you’re playing tic-tac-toe against a three-year-old.</p>
    <p>A subtler form of underconfidence is <em>losing your forward momentum</em>—amid all the things you realize that humans are doing wrong, that you used to be doing wrong, of which you are probably still doing some wrong. You become timid; you question yourself <em>but don’t answer the self-questions and move on</em>; when you hypothesize your own inability <em>you do not put that hypothesis to the test</em>.</p>
    <p>Perhaps without there ever being a watershed moment when you deliberately, self-visibly <em>decide not to try</em> at some particular test… you just… slow…… down……</p>
    <p>It doesn’t seem worthwhile any more, to go on trying to fix one thing when there are a dozen other things that will still be wrong…</p>
    <p>There’s not enough hope of triumph to <em>inspire</em> you to try <em>hard</em>…</p>
    <p>When you consider doing any new thing, a dozen questions about your ability at once leap into your mind, and it does not occur to you that you could <em>answer</em> the questions by <em>testing</em> yourself…</p>
    <p>And having read so much wisdom of human flaws, it seems that the course of wisdom is ever doubting (never resolving doubts), ever the humility of refusal (never the humility of preparation), and just generally, that it is wise to say worse and worse things about human abilities, to pass into feel-good feel-bad cynicism.</p>
    <p>And so my last piece of advice is another perspective from which to view the problem—by which to judge any potential habit of thought you might adopt—and that is to ask:</p>
    <p><em>Does this way of thinking make me stronger, or weaker? Really truly?</em></p>
    <p>I have previously spoken of the danger of reasonableness—the reasonable-sounding argument that we should two-box on Newcomb’s problem, the reasonable-sounding argument that we can’t know anything due to the problem of induction, the reasonable-sounding argument that we will be better off on average if we always adopt the majority belief, and other such impediments to the Way. “Does it win?” is one question you could ask to get an alternate perspective. Another, slightly different perspective is to ask, “Does this way of thinking make me stronger, or weaker?” Does constantly reminding yourself to doubt everything make you stronger, or weaker? Does never resolving or decreasing those doubts make you stronger, or weaker? Does undergoing a deliberate crisis of faith in the face of uncertainty make you stronger, or weaker? Does answering every objection with a humble confession of you fallibility make you stronger, or weaker?</p>
    <p>Are your current attempts to compensate for possible overconfidence making you stronger, or weaker? Hint: If you are taking more precautions, more scrupulously trying to test yourself, asking friends for advice, working your way up to big things incrementally, or still failing sometimes but less often then you used to, you are probably getting stronger. If you are <em>never</em> failing, avoiding challenges, and feeling generally hopeless and dispirited, you are probably getting weaker.</p>
    <p>I learned the first form of this rule at a very early age, when I was practicing for a certain math test, and found that my score was going down with each practice test I took, and noticed going over the answer sheet that I had been pencilling in the correct answers and erasing them. So I said to myself, “All right, <em>this</em> time I’m going to use the Force and act on instinct,” and my score shot up to above what it had been in the beginning, and on the real test it was higher still. So that was how I learned that doubting yourself does not always make you stronger—especially if it interferes with your ability to be moved by good information, such as your math intuitions. (But I <em>did</em> need the test to tell me this!)</p>
    <p>Underconfidence is not a unique sin of rationalists alone. But it is a particular danger into which <em>the attempt to be rational</em> can lead you. And it is a <em>stopping</em> mistake—an error that prevents you from gaining that further experience that would correct the error.</p>
    <p>Because underconfidence actually <em>does</em> seem quite common among aspiring rationalists who I meet—though rather less common among rationalists who have become famous role models—I would indeed name it third among the three besetting sins of rationalists.</p>
  </Chapter>;
}
