import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function LeaveALineOfRetreat() {
  return <Chapter title={["Leave a Line of Retreat"]}>

    <blockquote>
      <p>When you surround the enemy  <br />
        Always allow them an escape route.  <br />
        They must see that there is  <br />
        An alternative to death.</p>
      <p>—Sun Tzu, <em>The Art of War</em><span class="footnote">Sun Tzu, <em>The Art of War</em> (Cloud Hands, Inc., 2004).</span></p>
    </blockquote>
    <blockquote>
      <p>Don’t raise the pressure, lower the wall.</p>
      <p>—Lois McMaster Bujold, <em>Komarr</em><span class="footnote">Lois McMaster Bujold, <em>Komarr</em>, Miles Vorkosigan Adventures (Baen, 1999).</span></p>
    </blockquote>
    <p><span className="dropCap">O</span>nce I happened to be conversing with a nonrationalist who had somehow wandered into a local rationalists’ gathering. She had just declared (a) her belief in souls and (b) that she didn’t believe in cryonics because she believed the soul wouldn’t stay with the frozen body. I asked, “But how do you know that?” From the confusion that flashed on her face, it was pretty clear that this question had never occurred to her. I don’t say this in a bad way—she seemed like a nice person with absolutely no training in rationality, just like most of the rest of the human species. I really need to write that book.</p>
    <p>Most of the ensuing conversation was on items already covered on <em>Overcoming Bias</em>—if you’re <em>really</em> curious about something, you probably <em>can</em> figure out a good way to test it; try to attain accurate beliefs first and then let your emotions flow from that—that sort of thing. But the conversation reminded me of one notion I haven’t covered here yet:</p>
    <p>“Make sure,” I suggested to her, “that you visualize what the world would be like if there are no souls, and what you would do about that. Don’t think about all the reasons that it can’t be that way, just accept it as a premise and then visualize the consequences. So that you’ll think, ‘Well, if there are no souls, I can just sign up for cryonics,’ or ‘If there is no God, I can just go on being moral anyway,’ rather than it being too horrifying to face. As a matter of self-respect you should try to believe the truth no matter how uncomfortable it is, like I said before; but as a matter of human nature, it helps to make a belief less uncomfortable, <em>before</em> you try to evaluate the evidence for it.”</p>
    <p>The principle behind the technique is simple: as Sun Tzu advises you to do with your enemies, you must do with yourself—leave yourself a line of retreat, so that you will have less trouble retreating. The prospect of losing your job, say, may seem a lot more scary when you can’t even bear to think about it, than after you have calculated exactly how long your savings will last, and checked the job market in your area, and otherwise planned out exactly what to do next. Only then will you be ready to <em>fairly</em> assess the probability of keeping your job in the planned layoffs next month. Be a true coward, and plan out your retreat in detail—visualize every step—preferably before you first come to the battlefield.</p>
    <p>The hope is that it takes less courage to visualize an uncomfortable state of affairs <em>as a thought experiment</em>, than to consider <em>how likely</em> it is to be true. But then after you do the former, it becomes easier to do the latter.</p>
    <p>Remember that Bayesianism is precise—even if a scary proposition really should seem unlikely, it’s still important to count up all the evidence, for and against, exactly fairly, to arrive at the rational quantitative probability. Visualizing a scary belief does <em>not</em> mean admitting that you think, deep down, it’s probably true. You can visualize a scary belief on general principles of good mental housekeeping. “The thought you cannot think controls you more than thoughts you speak aloud”—this happens even if the unthinkable thought is false!</p>
    <p>The leave-a-line-of-retreat technique does require a certain minimum of self-honesty to use correctly.</p>
    <p>For a start: You must at least be able to admit to yourself <em>which</em> ideas scare you, and which ideas you are attached to. But this is a substantially less difficult test than fairly counting the evidence for an idea that scares you. Does it help if I say that I have occasion to use this technique myself? A rationalist does not reject all emotion, after all. There are ideas which scare me, yet I still believe to be false. There are ideas to which I know I am attached, yet I still believe to be true. But I still plan my retreats, not because I’m planning <em>to</em> retreat, but because planning my retreat in advance helps me think about the problem without attachment.</p>
    <p>But the greater test of self-honesty is to <em>really</em> accept the uncomfortable proposition as a premise, and figure out how you would really deal with it. When we’re faced with an uncomfortable idea, our first impulse is naturally to think of all the reasons why it <em>can’t possibly</em> be so. And so you will encounter a certain amount of psychological resistance in yourself, if you try to visualize exactly how the world would be, and what you would do about it, if My-Most-Precious-Belief were false, or My-Most-Feared-Belief were true.</p>
    <p>Think of all the people who say that, without God, morality was impossible. (And yes, this topic did come up in the conversation; so I am not offering a strawman.) If theists could visualize their <em>real</em> reaction to believing as a fact that God did not exist, they could realize that, no, they wouldn’t go around slaughtering babies. They could realize that atheists are reacting to the nonexistence of God in pretty much the way they themselves would, if they came to believe that. I say this, to show that it <em>is</em> a considerable challenge to visualize the way you <em>really would</em> react, to believing the opposite of a tightly held belief.</p>
    <p>Plus it’s always counterintuitive to realize that, yes, people do get over things. Newly minted quadriplegics are not as sad, six months later, as they expect to be, etc. It can be equally counterintuitive to realize that if the scary belief turned out to be true, you <em>would</em> come to terms with it somehow. Quadriplegics deal, and so would you.</p>
    <p>See also the Litany of Gendlin and the Litany of Tarski. What is true is already so; owning up to it doesn’t make it worse. You shouldn’t be afraid to just <em>visualize</em> a world you fear. If that world is already actual, visualizing it won’t make it worse; and if it is <em>not</em> actual, visualizing it will do no harm. And remember, as you visualize, that if the scary things you’re imagining really are true—which they may not be!—then you would, indeed, want to believe it, and you should visualize that too; not believing wouldn’t help you.</p>
    <p>How many religious people would retain their belief in God, if they could <em>accurately</em> visualize that hypothetical world in which there was no God and they themselves have become atheists?</p>
    <p>Leaving a line of retreat is a powerful technique, but it’s not easy. <em>Honest</em> visualization doesn’t take as much effort as admitting <em>outright</em> that God doesn’t exist, but it does take an effort.</p>
  </Chapter>;
}