import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function TheMeditationOnCuriosity() {
  return <Chapter title={["The Meditation", "on Curiosity"]}>

    <blockquote>
      <p>The first virtue is curiosity.</p>
      <p>—The Twelve Virtues of Rationality</p>
    </blockquote>
    <p><span className="dropCap">A</span>s rationalists, we are obligated to criticize ourselves and question our beliefs… are we not?</p>
    <p>Consider what happens to you, on a psychological level, if you begin by saying: “It is my duty to criticize my own beliefs.” Roger Zelazny once distinguished between “wanting to be an author” versus “wanting to write.” Mark Twain said: “A classic is something that everyone wants to have read and no one wants to read.” Criticizing yourself from a sense of duty leaves you <em>wanting to have investigated</em>, so that you’ll be able to say afterward that your faith is not blind. This is not the same as <em>wanting to investigate</em>.</p>
    <p>This can lead to motivated stopping of your investigation. You consider an objection, then a counterargument to that objection, then you stop <em>there</em>. You repeat this with several objections, until you feel that you have done your duty to investigate, and then you <em>stop there</em>. You have achieved your underlying psychological objective: to get rid of the cognitive dissonance that would result from thinking of yourself as a rationalist and yet knowing that you had not tried to criticize your belief. You might call it purchase of rationalist satisfaction—trying to create a “warm glow” of discharged duty.</p>
    <p>Afterward, your stated probability level will be high enough to justify your keeping the plans and beliefs you started with, but not so high as to evoke incredulity from yourself or other rationalists.</p>
    <p>When you’re really curious, you’ll gravitate to inquiries that seem most promising of producing shifts in belief, or inquiries that are least like the ones you’ve tried before. Afterward, your probability distribution likely should <em>not</em> look like it did when you started out—shifts should have occurred, whether up or down; and either direction is equally fine to you, if you’re genuinely curious.</p>
    <p>Contrast this to the subconscious motive of keeping your inquiry on familiar ground, so that you can get your investigation over with quickly, so that you can <em>have investigated</em>, and restore the familiar balance on which your familiar old plans and beliefs are based.</p>
    <p>As for what I think true curiosity should look like, and the power that it holds, I refer you to A Fable of Science and Politics. Each of the characters is intended to illustrate different lessons. Ferris, the last character, embodies the power of innocent curiosity: which is lightness, and an eager reaching forth for evidence.</p>
    <p>Ursula K. LeGuin wrote: “In innocence there is no strength against evil. But there is strength in it for good.”<span class="footnote">Ursula K. Le Guin, <em>The Farthest Shore</em> (Saga Press, 2001).</span> Innocent curiosity may turn innocently awry; and so the training of a rationalist, and its accompanying sophistication, must be dared as a danger if we want to become stronger. Nonetheless we can try to keep the lightness and the eager reaching of innocence.</p>
    <p>As it is written in the Twelve Virtues:</p>
    <blockquote>
      <p>If in your heart you believe you already know, or if in your heart you do not wish to know, then your questioning will be purposeless and your skills without direction. Curiosity seeks to annihilate itself; there is no curiosity that does not want an answer.</p>
    </blockquote>
    <p>There just isn’t any good substitute for genuine curiosity. “A burning itch to know is higher than a solemn vow to pursue truth.” But you can’t produce curiosity just by willing it, any more than you can will your foot to feel warm when it feels cold. Sometimes, all we have is our mere solemn vows.</p>
    <p>So what can you do with duty? For a start, we can try to take an interest in our dutiful investigations—keep a close eye out for sparks of genuine intrigue, or even genuine ignorance and a desire to resolve it. This goes right along with keeping a special eye out for possibilities that are painful, that you are flinching away from—it’s not all negative thinking.</p>
    <p>It should also help to meditate on Conservation of Expected Evidence. For every <em>new</em> point of inquiry, for every piece of <em>unseen</em> evidence that you suddenly look at, the expected posterior probability should equal your prior probability. In the microprocess of inquiry, your belief should always be evenly poised to shift in either direction. Not every point may suffice to blow the issue wide open—to shift belief from 70% to 30% probability—but if your current belief is 70%, you should be as ready to drop it to 69% as raising it to 71%. You should not think that you know which direction it will go in (on average), because by the laws of probability theory, if you know your destination, you are already there. If you can investigate honestly, so that each <em>new</em> point really does have equal potential to shift belief upward or downward, this may help to keep you interested or even curious about the microprocess of inquiry.</p>
    <p>If the argument you are considering is <em>not</em> new, then why is your attention going here? Is this where you would look if you were genuinely curious? Are you subconsciously criticizing your belief at its strong points, rather than its weak points? Are you rehearsing the evidence?</p>
    <p>If you can manage not to rehearse already known support, and you can manage to drop down your belief by one tiny bite at a time from the new evidence, you may even be able to relinquish the belief entirely—to realize from which quarter the winds of evidence are blowing against you.</p>
    <p>Another restorative for curiosity is what I have taken to calling the Litany of Tarski, which is really a meta-litany that specializes for each instance (this is only appropriate). For example, if I am tensely wondering whether a locked box contains a diamond, then, rather than thinking about all the wonderful consequences if the box does contain a diamond, I can repeat the Litany of Tarski:</p>
    <p><em>If the box contains a diamond,</em></p>
    <p><em>I desire to believe that the box contains a diamond;</em></p>
    <p><em>If the box does not contain a diamond,</em></p>
    <p><em>I desire to believe that the box does not contain a diamond;</em></p>
    <p><em>Let me not become attached to beliefs I may not want.</em></p>
    <p>Then you should meditate upon the possibility that there is no diamond, and the subsequent advantage that will come to you if you believe there is no diamond, and the subsequent disadvantage if you believe there is a diamond. See also the Litany of Gendlin.</p>
    <p>If you can find within yourself the slightest shred of true uncertainty, then guard it like a forester nursing a campfire. If you can make it blaze up into a flame of curiosity, it will make you light and eager, and give purpose to your questioning and direction to your skills.</p>
  </Chapter>;
}