import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function PoliticsIsTheMindKiller() {
  return <Chapter title={["Politics is the Mind-Killer"]}>
    <p><span className="dropCap tall">P</span>eople go funny in the head when talking about politics. The evolutionary reasons for this are so obvious as to be worth belaboring: In the ancestral environment, politics was a matter of life and death. And sex, and wealth, and allies, and reputation… When, today, you get into an argument about whether “we” ought to raise the minimum wage, you’re executing adaptations for an ancestral environment where being on the wrong side of the argument could get you killed. Being on the <em>right</em> side of the argument could let <em>you</em> kill your hated rival!</p>
    <p>If you want to make a point about science, or rationality, then my advice is to not choose a domain from <em>contemporary</em> politics if you can possibly avoid it. If your point is inherently about politics, then talk about Louis XVI during the French Revolution. Politics is an important domain to which we should individually apply our rationality—but it’s a terrible domain in which to <em>learn</em> rationality, or discuss rationality, unless all the discussants are already rational.</p>
    <p>Politics is an extension of war by other means. Arguments are soldiers. Once you know which side you’re on, you must support all arguments of that side, and attack all arguments that appear to favor the enemy side; otherwise it’s like stabbing your soldiers in the back—providing aid and comfort to the enemy. People who would be level-headed about evenhandedly weighing all sides of an issue in their professional life as scientists, can suddenly turn into slogan-chanting zombies when there’s a Blue or Green position on an issue.</p>
    <p>In Artificial Intelligence, and particularly in the domain of nonmonotonic reasoning, there’s a standard problem: “All Quakers are pacifists. All Republicans are not pacifists. Nixon is a Quaker and a Republican. Is Nixon a pacifist?”</p>
    <p>What on Earth was the point of choosing this as an example? To rouse the political emotions of the readers and distract them from the main question? To make Republicans feel unwelcome in courses on Artificial Intelligence and discourage them from entering the field? (And no, I am not a Republican. Or a Democrat.)</p>
    <p>Why would anyone pick such a <em>distracting</em> example to illustrate nonmonotonic reasoning? Probably because the author just couldn’t resist getting in a good, solid dig at those hated Greens. It feels so <em>good</em> to get in a hearty punch, y’know, it’s like trying to resist a chocolate cookie.</p>
    <p>As with chocolate cookies, not everything that feels pleasurable is good for you.</p>
    <p>I’m not saying that I think we should be apolitical, or even that we should adopt Wikipedia’s ideal of the Neutral Point of View. But try to resist getting in those good, solid digs if you can possibly avoid it. If your topic legitimately relates to attempts to ban evolution in school curricula, then go ahead and talk about it—but don’t blame it explicitly on the whole Republican Party; some of your readers may be Republicans, and they may feel that the problem is a few rogues, not the entire party. As with Wikipedia’s npov, it doesn’t matter whether (you think) the Republican Party really <em>is</em> at fault. It’s just better for the spiritual growth of the community to discuss the issue without invoking color politics.</p>
  </Chapter >;
}