import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function RationalityAndTheEnglishLanguage() {
  return <Chapter title={["Rationality and the", "English Language"]}>

    <p><span className="dropCap">R</span>esponding to my discussion of applause lights, someone said that my writing reminded them of George Orwell’s Politics and the English Language. <span class="footnote">George Orwell, “Politics and the English Language,” <em>Horizon</em> (April 1946). </span> I was honored. Especially since I’d already thought of today’s topic.</p>
    <p>If you <em>really</em> want an artist’s perspective on rationality, then read Orwell; he is mandatory reading for rationalists as well as authors. Orwell was not a scientist, but a writer; his tools were not numbers, but words; his adversary was not Nature, but human evil. If you wish to imprison people for years without trial, you must think of some other way to say it than “I’m going to imprison Mr. Jennings for years without trial.” You must muddy the listener’s thinking, prevent clear images from outraging conscience. You say, “Unreliable elements were subjected to an alternative justice process.”</p>
    <p>Orwell was the outraged opponent of totalitarianism and the muddy thinking in which evil cloaks itself—which is how Orwell’s writings on language ended up as classic rationalist documents on a level with Feynman, Sagan, or Dawkins.</p>
    <p>“Writers are told to avoid usage of the passive voice.” A rationalist whose background comes <em>exclusively</em> from science may fail to see the flaw in the previous sentence; but anyone who’s done a little writing should see it right away. I wrote the sentence in the passive voice, without telling you <em>who</em> tells authors to avoid passive voice. Passive voice removes the actor, leaving only the acted-upon. “Unreliable elements were subjected to an alternative justice process”—subjected by <em>whom</em>? What does an “alternative justice process” <em>do</em>? With enough static noun phrases, you can keep anything unpleasant from actually <em>happening</em>.</p>
    <p>Journal articles are often written in passive voice. (Pardon me, <em>some scientists</em> write their journal articles in passive voice. It’s not as if the articles are being written by no one, with no one to blame.) It sounds more authoritative to say “The subjects were administered Progenitorivox” than “I gave each college student a bottle of 20 Progenitorivox, and told them to take one every night until they were gone.” If you remove the scientist from the description, that leaves only the all-important data. But in reality the scientist <em>is</em> there, and the subjects <em>are</em> college students, and the Progenitorivox wasn’t “administered” but handed over with instructions. Passive voice obscures reality.</p>
    <p>Judging from the comments I get, someone will protest that using the passive voice in a journal article is hardly a sin—after all, if you <em>think</em> about it, you can realize the scientist is there. It doesn’t seem like a logical flaw. And this is why rationalists need to read Orwell, not just Feynman or even Jaynes.</p>
    <p>Nonfiction conveys <em>knowledge</em>, fiction conveys <em>experience</em>. Medical science can extrapolate what would happen to a human unprotected in a vacuum. Fiction can make you live through it.</p>
    <p>Some rationalists will try to analyze a misleading phrase, try to see if there <em>might possibly</em> be anything meaningful to it, try to <em>construct</em> a logical interpretation. They will be charitable, give the author the benefit of the doubt. Authors, on the other hand, are trained <em>not</em> to give themselves the benefit of the doubt. Whatever the audience <em>thinks</em> you said <em>is</em> what you said, whether you meant to say it or not; you can’t argue with the audience no matter how clever your justifications.</p>
    <p>A writer knows that readers will <em>not</em> stop for a minute to think. A fictional experience is a continuous stream of first impressions. A writer-rationalist pays attention to the <em>experience</em> words create. If you are evaluating the public rationality of a statement, and you analyze the words deliberatively, rephrasing propositions, trying out different meanings, searching for nuggets of truthiness, then you’re losing track of the first impression—what the audience <em>sees</em>, or rather <em>feels</em>.</p>
    <p>A novelist would notice the screaming wrongness of “The subjects were administered Progenitorivox.” What life is here for a reader to live? This sentence creates a distant feeling of authoritativeness, and that’s <em>all</em>—the <em>only</em> experience is the feeling of being told something reliable. A novelist would see nouns too abstract to show what actually happened—the postdoc with the bottle in their hand, trying to look stern; the student listening with a nervous grin.</p>
    <p>My point is not to say that journal articles should be written like novels, but that a rationalist should become consciously aware of the <em>experiences</em> which words create. A rationalist must understand the mind and how to operate it. That includes the stream of consciousness, the part of yourself that unfolds in language. A rationalist must become consciously aware of the actual, experiential impact of phrases, beyond their mere propositional semantics.</p>
    <p>Or to say it more bluntly: <em>Meaning does not excuse impact!</em></p>
    <p>I don’t care what rational interpretation you can <em>construct</em> for an applause light like “AI should be developed through democratic processes.” That cannot excuse its irrational impact of signaling the audience to applaud, not to mention its cloudy question-begging vagueness.</p>
    <p>Here is Orwell, railing against the <em>impact</em> of cliches, their effect on the experience of thinking:</p>
    <blockquote>
      <p>When one watches some tired hack on the platform mechanically repeating the familiar phrases—<span className="smallCaps">bestial, atrocities, iron heel, bloodstained tyranny, free peoples of the world, stand shoulder to shoulder</span>—one often has a curious feeling that one is not watching a live human being but some kind of dummy… A speaker who uses that kind of phraseology has gone some distance toward turning himself into a machine. The appropriate noises are coming out of his larynx, but his brain is not involved, as it would be if he were choosing his words for himself…</p>
      <p>What is above all needed is to let the meaning choose the word, and not the other way around. In prose, the worst thing one can do with words is surrender to them. When you think of a concrete object, you think wordlessly, and then, if you want to describe the thing you have been visualising you probably hunt about until you find the exact words that seem to fit it. When you think of something abstract you are more inclined to use words from the start, and unless you make a conscious effort to prevent it, the existing dialect will come rushing in and do the job for you, at the expense of blurring or even changing your meaning. Probably it is better to put off using words as long as possible and get one’s meaning as clear as one can through pictures and sensations.</p>
    </blockquote>
    <p>Charles Sanders Peirce might have written that last paragraph. More than one path can lead to the Way.</p>
  </Chapter>;
}