import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function FakeSelfishness() {
  return <Chapter title={["Fake Selfishness"]}>


    <p><span className="dropCap">O</span>nce upon a time, I met someone who proclaimed himself to be purely selfish, and told me that I should be purely selfish as well. I was feeling mischievous<span class="footnote">Other mischievous questions to ask self-proclaimed Selfishes: “Would you sacrifice your own life to save the entire human species?” (If they notice that their own life is strictly included within the human species, you can specify that they can choose between dying immediately to save the Earth, or living in comfort for one more year and then dying along with Earth.) Or, taking into account that scope insensitivity leads many people to be more concerned over one life than the Earth, “If you had to choose one event or the other, would you rather that you stubbed your toe, or that the stranger standing near the wall there gets horribly tortured for fifty years?” (If they say that they’d be emotionally disturbed by knowing, specify that they won’t know about the torture.) “Would you steal a thousand dollars from Bill Gates if you could be guaranteed that neither he nor anyone else would ever find out about it?” (Selfish libertarians only.)</span> that day, so I said, “I’ve observed that with most religious people, at least the ones I meet, it doesn’t matter much what their religion says, because whatever they want to do, they can find a religious reason for it. Their religion says they should stone unbelievers, but they want to be nice to people, so they find a religious justification for that instead. It looks to me like when people espouse a philosophy of selfishness, it has no effect on their behavior, because whenever they want to be nice to people, they can rationalize it in selfish terms.”</p>
    <p>And the one said, “I don’t think that’s true.”</p>
    <p>I said, “If you’re <em>genuinely</em> selfish, then why do you want <em>me</em> to be selfish too? Doesn’t that make you concerned for my welfare? Shouldn’t you be trying to persuade me to be more altruistic, so you can exploit me?” The one replied: “Well, if you become selfish, then you’ll realize that it’s in your rational self-interest to play a productive role in the economy, instead of, for example, passing laws that infringe on my private property.”</p>
    <p>And I said, “But I’m a small-‘l’ libertarian <em>already</em>, so I’m not going to support those laws. And since I conceive of myself as an altruist, I’ve taken a job that I expect to benefit a lot of people, including you, instead of a job that pays more. Would you really benefit more from me if I became selfish? Besides, is trying to persuade me to be selfish the <em>most</em> selfish thing you could be doing? Aren’t there other things you could do with your time that would bring much more direct benefits? But what I really want to know is this: Did you start out by thinking that you wanted to be selfish, and then decide this was the most selfish thing you could possibly do? Or did you start out by wanting to convert others to selfishness, then look for ways to rationalize that as self-benefiting?”</p>
    <p>And the one said, “You may be right about that last part,” so I marked him down as intelligent.</p>
  </Chapter>;
}