import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function ChangingYourMetaethics() {
  return <Chapter title={["Changing Your Metaethics"]}>



    <p><span className="dropCap">I</span>f you say, “Killing people is wrong,” that’s morality. If you say, “You shouldn’t kill people because God prohibited it,” or “You shouldn’t kill people because it goes against the trend of the universe,” that’s metaethics.</p>
    <p>Just as there’s far more agreement on Special Relativity than there is on the question “What is science?,” people find it much easier to agree “Murder is bad” than to agree <em>what</em> makes it bad, or what it <em>means</em> for something to be bad.</p>
    <p>People do get attached to their metaethics. Indeed they frequently insist that if their metaethic is wrong, all morality necessarily falls apart. It might be interesting to set up a panel of metaethicists—theists, Objectivists, Platonists, etc.—all of whom agree that killing is wrong; all of whom disagree on what it means for a thing to be “wrong”; and all of whom insist that if their metaethic is untrue, then morality falls apart.</p>
    <p>Clearly a good number of people, if they are to make philosophical progress, will need to shift metathics at some point in their lives. <em>You</em> may have to do it.</p>
    <p>At that point, it might be useful to have an open line of retreat—not a retreat from morality, but a retreat from Your-Current-Metaethic. (You know, the one that, if it is not true, leaves no possible basis for not killing people.)</p>
    <p>And so I summarized below some possible lines of retreat. For I have learned that to change metaethical beliefs is nigh-impossible in the presence of an unanswered attachment.</p>
    <p>If, for example, someone believes the authority of “Thou Shalt Not Kill” derives from God, then there are several and well-known things to say that can help set up a line of retreat—as opposed to immediately attacking the plausibility of God. You can say, “Take personal responsibility! Even if you got orders from God, it would be your own decision to obey those orders. Even if God didn’t order you to be moral, you could just be moral anyway.”</p>
    <p>The above argument actually generalizes to quite a number of metaethics— you just substitute Their-Favorite-Source-Of-Morality, or even the word “morality,” for “God.” Even if your particular source of moral authority failed, couldn’t you just drag the child off the train tracks <em>anyway</em>? And indeed, who is it but you that ever decided to follow this source of moral authority in the first place? What responsibility are you really passing on?</p>
    <p>So the most important line of retreat is: If your metaethic stops telling you to save lives, you can just drag the kid off the train tracks anyway. To paraphrase Piers Anthony, only those who have moralities worry over whether or not they have them. If your metaethic tells you to kill people, why <em>should</em> you even listen? Maybe that which you would do even if there were no morality, <em>is</em> your morality.</p>
    <p>The point being, of course, not that no morality exists; but that you can hold your will in place, and not fear losing sight of what’s important to you, while your notions of the <em>nature</em> of morality change.</p>
    <p>I’ve written some essays to set up lines of retreat specifically for more <em>naturalistic</em> metaethics. Joy in the Merely Real and Explaining vs. Explaining Away argue that you shouldn’t be disappointed in any facet of life, just because it turns out to be <em>explicable</em> instead of inherently mysterious: for if we cannot take joy in the merely real, our lives shall be empty indeed.</p>
    <p>No Universally Compelling Arguments sets up a line of retreat from the desire to have <em>everyone</em> agree with our moral arguments. There’s a strong moral intuition which says that if our moral arguments are right, by golly, we ought to be able to <em>explain</em> them to people. This may be valid among humans, but you can’t explain moral arguments to a rock. There is no ideal philosophy student of perfect emptiness who can be persuaded to implement modus ponens, starting without modus ponens. If a mind doesn’t contain that which is moved by your moral arguments, it won’t respond to them.</p>
    <p>But then isn’t all morality circular logic, in which case it falls apart? Where Recursive Justification Hits Bottom and My Kind of Reflection explain the difference between a self-consistent loop through the meta-level, and actual circular logic. You shouldn’t find yourself saying “The universe is simple because it is simple,” or “Murder is wrong because it is wrong”; but neither should you try to abandon Occam’s Razor while evaluating the probability that Occam’s Razor works, nor should you try to evaluate “Is murder wrong?” from somewhere outside your brain. There is no ideal philosophy student of perfect emptiness to which you can unwind yourself—try to find the perfect rock to stand upon, and you’ll end up as a rock. So instead use the full force of your intelligence, your full rationality and your full morality, when you investigate the foundations of yourself.</p>
    <p>We can also set up a line of retreat for those afraid to allow a <em>causal</em> role for evolution, in their account of how morality came to be. (Note that this is extremely distinct from granting evolution a <em>justificational</em> status in moral theories.) Love has to come into existence somehow—for if we cannot take joy in things that can come into existence, our lives will be empty indeed. Evolution may not be a particularly <em>pleasant</em> way for love to evolve, but judge the end product—not the source. Otherwise you would be committing what is known (appropriately) as The Genetic Fallacy: causation is not the same concept as justification. It’s not like you can step outside the brain evolution gave you; rebelling against nature is only possible from within nature.</p>
    <p>The earlier series on Evolutionary Psychology should dispense with the metaethical confusion of believing that any normal human being thinks about their reproductive fitness, even unconsciously, in the course of making decisions. Only evolutionary biologists even know how to <em>define</em> genetic fitness, and they know better than to think it defines morality.</p>
    <p>Alarming indeed is the thought that morality might be computed inside our own minds—doesn’t this imply that morality is a mere thought? Doesn’t it imply that whatever you think is right, must be right?</p>
    <p>No. Just because a quantity is computed inside your head doesn’t mean that the quantity computed is <em>about</em> your thoughts. There’s a difference between a calculator that calculates “What is 2 + 3?” and one that outputs “What do I output when someone presses ‘2,’ ‘+,’ and ‘3’?”</p>
    <p>Finally, if life seems painful, reductionism may not be the real source of your problem—if living in a world of mere particles seems too unbearable, maybe your life isn’t exciting enough right now?</p>
    <p>And if you’re wondering why I deem this business of metaethics important, when it is all going to end up adding up to moral normality… telling you to pull the child off the train tracks, rather than the converse…</p>
    <p>Well, there <em>is</em> opposition to rationality from people who think it drains meaning from the universe.</p>
    <p>And this is a special case of a general phenomenon, in which many many people get messed up by misunderstanding where their morality comes from. Poor metaethics forms part of the teachings of many a cult, including the big ones. My target audience is not just people who are afraid that life is meaningless, but also those who’ve concluded that love is a delusion because real morality has to involve maximizing your inclusive fitness, or those who’ve concluded that unreturned kindness is evil because real morality arises only from selfishness, etc.</p>
  </Chapter>;
}