import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function NoUniversallyCompellingArguments() {
  return <Chapter title={["No Universally Compelling Arguments"]}>



    <p><span className="dropCap">W</span>hat is so <em>terrifying</em> about the idea that not every possible mind might agree with us, even in principle?</p>
    <p>For some folks, nothing—it doesn’t bother them in the slightest. And for some of <em>those</em> folks, the <em>reason</em> it doesn’t bother them is that they don’t have strong intuitions about standards and truths that go beyond personal whims. If they say the sky is blue, or that murder is wrong, that’s just their personal opinion; and that someone else might have a different opinion doesn’t surprise them.</p>
    <p>For other folks, a disagreement that persists even <em>in principle</em> is something they can’t accept. And for some of <em>those</em> folks, the <em>reason</em> it bothers them is that it seems to them that if you allow that some people cannot be persuaded <em>even in principle</em> that the sky is blue, then you’re conceding that “the sky is blue” is merely an <em>arbitrary</em> personal opinion.</p>
    <p>I’ve proposed that you should resist the temptation to generalize over all of mind design space. If we restrict ourselves to minds specifiable in a trillion bits or less, then each <em>universal</em> generalization “All minds <em>m</em>: <em>X</em> (<em>m</em>)” has two to the trillionth chances to be false, while each <em>existential</em> generalization “Exists mind <em>m</em>: <em>X</em> (<em>m</em>)” has two to the trillionth chances to be true.</p>
    <p>This would seem to argue that for every argument <em>A</em>, howsoever convincing it may seem to us, there exists at least one possible mind that doesn’t buy it.</p>
    <p>And the surprise and/or horror of this prospect (for some) has a great deal to do, I think, with the intuition of the ghost-in-the-machine—a ghost with some irreducible core that any <em>truly valid</em> argument will convince.</p>
    <p>I have previously spoken of the intuition whereby people map <em>programming a computer</em> onto <em>instructing a human servant</em>, so that the computer might rebel against its code—or perhaps look over the code, decide it is not reasonable, and hand it back.</p>
    <p>If there were a ghost in the machine and the ghost contained an irreducible core of reasonableness, above which any mere code was only a suggestion, then there might be universal arguments. Even if the ghost were initially handed code-suggestions that contradicted the Universal Argument, when we finally did expose the ghost to the Universal Argument—or the ghost could discover the Universal Argument on its own, that’s also a popular concept—the ghost would just override its own, mistaken source code.</p>
    <p>But as the student programmer once said, “I get the feeling that the computer just skips over all the comments.” The code is not given to the AI; the code <em>is</em> the AI.</p>
    <p>If you switch to the physical perspective, then the notion of a Universal Argument seems noticeably unphysical. If there’s a physical system that at time <em>T</em>, after being exposed to argument <em>E</em>, does <em>X</em>, then there ought to be another physical system that at time <em>T</em>, after being exposed to environment <em>E</em>, does <em>Y</em>. Any thought has to be implemented <em>somewhere</em>, in a physical system; any belief, any conclusion, any decision, any motor output. For every lawful causal system that zigs at a set of points, you should be able to specify another causal system that lawfully zags at the same points.</p>
    <p>Let’s say there’s a mind with a transistor that outputs +3 volts at time <em>T</em>, indicating that it has just assented to some persuasive argument. Then we can build a highly similar physical cognitive system with a tiny little trapdoor underneath the transistor containing a little gray man who climbs out at time <em>T</em> and sets that transistor’s output to −3 volts, indicating non-assent. Nothing acausal about that; the little gray man is there because we built him in. The notion of an argument that convinces <em>any</em> mind seems to involve a little blue woman who was <em>never</em> built into the system, who climbs out of literally <em>nowhere</em>, and strangles the little gray man, because that transistor has just <em>got</em> to output +3 volts. It’s such a <em>compelling argument</em>, you see.</p>
    <p>But compulsion is not a property of arguments; it is a property of minds that process arguments.</p>
    <p>So the reason I’m arguing against the ghost isn’t <em>just</em> to make the point that (1) Friendly AI has to be explicitly programmed and (2) the laws of physics do not forbid Friendly AI. (Though of course I take a certain interest in establishing this.)</p>
    <p>I also wish to establish the notion of a mind as a <em>causal, lawful, physical system</em> in which there <em>is no</em> irreducible central ghost that looks over the neurons/code and decides whether they are good suggestions.</p>
    <p>(There is a concept in Friendly AI of <em>deliberately</em> programming an FAI to review its own source code and possibly hand it back to the programmers. But the mind that reviews is not irreducible, it is just the mind that you created. The FAI is renormalizing itself <em>however it was designed to do so</em>; there is nothing acausal reaching in from outside. A bootstrap, not a skyhook.)</p>
    <p>All this echoes back to the worry about a Bayesian’s “arbitrary” priors. If you show me one Bayesian who draws 4 red balls and 1 white ball from a barrel, and who assigns probability 5/7 to obtaining a red ball on the next occasion (by Laplace’s Rule of Succession), then I can show you another mind which obeys Bayes’s Rule to conclude a 2/7 probability of obtaining red on the next occasion—corresponding to a different prior belief about the barrel, but, perhaps, a less “reasonable” one.</p>
    <p>Many philosophers are convinced that because you can in-principle construct a prior that updates to any given conclusion on a stream of evidence, therefore, Bayesian reasoning must be “arbitrary,” and the whole schema of Bayesianism flawed, because it relies on “unjustifiable” assumptions, and indeed “unscientific,” because you cannot force any possible journal editor in mindspace to agree with you.</p>
    <p>And this (I replied) relies on the notion that by unwinding all arguments and their justifications, you can obtain an ideal philosophy student of perfect emptiness, to be convinced by a line of reasoning that begins from absolutely no assumptions.</p>
    <p>But who is this ideal philosopher of perfect emptiness? Why, it is just the irreducible core of the ghost!</p>
    <p>And that is why (I went on to say) the result of trying to remove all assumptions from a mind, and unwind to the perfect absence of any prior, is not an ideal philosopher of perfect emptiness, but a rock. What is left of a mind after you remove the source code? Not the ghost who looks over the source code, but simply . . . no ghost.</p>
    <p>So—and I shall take up this theme again later—wherever you are to locate your notions of <em>validity</em> or <em>worth</em> or <em>rationality</em> or <em>justification</em> or even <em>objectivity</em>, it cannot rely on an argument that is <em>universally compelling to all physically possible minds</em>.</p>
    <p>Nor can you ground validity in a sequence of justifications that, beginning from nothing, persuades a perfect emptiness.</p>
    <p>Oh, there might be argument sequences that would compel any neurologically intact <em>human</em>—like the argument I use to make people let the AI out of the box<span class="footnote">Just kidding.</span>—but that is hardly the same thing from a philosophical perspective.</p>
    <p>The first great failure of those who try to consider Friendly AI is the One Great Moral Principle That Is All We Need To Program—a.k.a. the fake utility function—and of this I have already spoken.</p>
    <p>But the even worse failure is the One Great Moral Principle We Don’t Even <em>Need</em> To Program Because Any AI Must Inevitably Conclude It. This notion exerts a terrifying unhealthy fascination on those who spontaneously reinvent it; they dream of commands that no sufficiently advanced mind can disobey. The gods themselves will proclaim the rightness of their philosophy! (E.g., John C. Wright, Marc Geddes.)</p>
    <p>There is also a less severe version of the failure, where the one does not <em>declare</em> the One True Morality. Rather the one hopes for an AI created <em>perfectly free</em>, unconstrained by flawed humans desiring slaves, so that the AI may arrive at virtue of its own accord—virtue undreamed-of perhaps by the speaker, who confesses themselves too flawed to teach an AI. (E.g., John K. Clark, Richard Hollerith?, Eliezer1996.) This is a less tainted motive than the dream of absolute command. But though <em>this</em> dream arises from virtue rather than vice, it is still based on a flawed understanding of freedom, and will not actually <em>work in real life</em>. Of this, more to follow, of course.</p>
    <p>John C. Wright, who was previously writing a very nice transhumanist trilogy (first book: <em>The Golden Age</em>), inserted a huge Author Filibuster in the middle of his climactic third book, describing in tens of pages his Universal Morality That Must Persuade Any AI. I don’t know if anything happened after that, because I stopped reading. And then Wright converted to Christianity— yes, seriously. So you <em>really don’t</em> want to fall into this trap!</p>
  </Chapter>;
}