import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function OneLifeAgainstTheWorld() {
  return <Chapter title={["One Life Against the World"]}>



    <blockquote>
      <p>Whoever saves a single life, it is as if he had saved the whole world.</p>
      <p>—The Talmud, Sanhedrin 4:5</p>
    </blockquote>
    <p><span className="dropCap">I</span>t’s a beautiful thought, isn’t it? Feel that warm glow. <br /><br />I can testify that helping one person <em>feels</em> just as good as helping the whole world. Once upon a time, when I was burned out for the day and wasting time on the Internet—it’s a bit complicated, but essentially I managed to turn someone’s whole life around by leaving an anonymous blog comment. I wasn’t expecting it to have an effect that large, but it did. When I discovered what I had accomplished, it gave me a <em>tremendous</em> high. The euphoria lasted through that day and into the night, only wearing off somewhat the next morning. It felt just as good (this is the scary part) as the euphoria of a major scientific insight, which had previously been my best referent for what it might feel like to do drugs.</p>
    <p>Saving one life probably <em>does</em> feel just as good as being the first person to realize what makes the stars shine. It probably <em>does</em> feel just as good as saving the entire world.</p>
    <p>But if you ever have a choice, dear reader, between saving a single life and saving the whole world—then save the world. Please. Because beyond that warm glow is <em>one heck of a gigantic difference</em>. For some people, the notion that saving the world is <em>significantly better</em> than saving one human life will be obvious, like saying that six billion dollars is worth more than one dollar, or that six cubic kilometers of gold weighs more than one cubic meter of gold. (And never mind the expected value of posterity.) Why might it <em>not</em> be obvious? Well, suppose there’s a qualitative duty to save what lives you can—then someone who saves the world, and someone who saves one human life, are just fulfilling the same duty. Or suppose that we follow the Greek conception of personal virtue, rather than consequentialism; someone who saves the world is virtuous, but not six billion times as virtuous as someone who saves one human life. Or perhaps the value of one human life is already too great to comprehend—so that the passing grief we experience at funerals is an infinitesimal underestimate of what is lost—and thus passing to the entire world changes little.</p>
    <p>I agree that one human life is of unimaginably high value. I also hold that two human lives are twice as unimaginably valuable. Or to put it another way: Whoever saves one life, if it is as if they had saved the whole world; whoever saves ten lives, it is as if they had saved ten worlds. Whoever <em>actually</em> saves the whole world—not to be confused with pretend rhetorical saving the world—it is as if they had saved an intergalactic civilization.</p>
    <p>Two deaf children are sleeping on the railroad tracks, the train speeding down; you see this, but you are too far away to save the children. I’m nearby, within reach, so I leap forward and drag one child off the railroad tracks—and then stop, calmly sipping a Diet Pepsi as the train bears down on the second child. “<em>Quick!</em>” you scream to me. “<em>Do something!</em>” But (I call back) I already saved one child from the train tracks, and thus I am “unimaginably” far ahead on points. Whether I save the second child, or not, I will still be credited with an “unimaginably” good deed. Thus, I have no further motive to act. Doesn’t sound right, does it?</p>
    <p>Why should it be any different if a philanthropist spends $10 million on curing a rare but spectacularly fatal disease which afflicts only a hundred people planetwide, when the same money has an equal probability of producing a cure for a less spectacular disease that kills 10% of 100,000 people? I don’t think it <em>is</em> different. When human lives are at stake, we have a duty to <em>maximize</em>, not satisfice; and this duty has the same strength as the original duty to save lives. Whoever knowingly chooses to save one life, when they could have saved two—to say nothing of a thousand lives, or a world—they have damned themselves as thoroughly as any murderer.</p>
    <p>It’s not cognitively easy to spend money to save lives, since cliché methods that instantly leap to mind don’t work or are counterproductive. (I will write later on why this tends to be so.) Stuart Armstrong also points out that if we are to disdain the philanthropist who spends life-saving money inefficiently, we should be consistent and disdain more those who could spend money to save lives but don’t.</p>
  </Chapter>;
}