import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function ScopeInsensitivity() {
  return <Chapter title={["Scope Insensitivity"]}>



    <p><span className="dropCap">O</span>nce upon a time, three groups of subjects were asked how much they would pay to save 2,000 / 20,000 / 200,000 migrating birds from drowning in uncovered oil ponds. The groups respectively answered $80, $78, and $88.<span class="footnote">William H. Desvousges et al., <em>Measuring Nonuse Damages Using Contingent Valuation: An Experimental Evaluation of Accuracy</em>, technical report (Research Triangle Park, NC: RTI International, 2010), doi:10.3768/rtipress.2009.bk.0001.1009.</span> This is <em>scope insensitivity</em> or <em>scope neglect</em>: the number of birds saved—the <em>scope</em> of the altruistic action—had little effect on willingness to pay.</p>
    <p>Similar experiments showed that Toronto residents would pay little more to clean up all polluted lakes in Ontario than polluted lakes in a particular region of Ontario,<span class="footnote">Daniel Kahneman, “Comments by Professor Daniel Kahneman,” in <em>Valuing Environmental Goods: An Assessment of the Contingent Valuation Method</em>, ed. Ronald G. Cummings, David S. Brookshire, and William D. Schulze, vol. 1.B, Experimental Methods for Assessing Environmental Benefits (Totowa, NJ: Rowman & Allanheld, 1986), 226–235, http://yosemite.epa.gov/ee/epa/eerm.nsf/ vwAN/EE-0280B-04.pdf/$file/EE-0280B-04.pdf.</span> or that residents of four western US states would pay only 28% more to protect all 57 wilderness areas in those states than to protect a single area.<span class="footnote">Daniel L. McFadden and Gregory K. Leonard, “Issues in the Contingent Valuation of Environmental Goods: Methodologies for Data Collection and Analysis,” in <em>Contingent Valuation: A Critical Assessment</em>, ed. Jerry A. Hausman, Contributions to Economic Analysis 220 (New York: North-Holland, 1993), 165–215, doi:10.1108/S0573-8555(1993)0000220007.</span> People visualize “a single exhausted bird, its feathers soaked in black oil, unable to escape.”<span class="footnote">Kahneman, Ritov, and Schkade, “Economic Preferences or Attitude Expressions?”</span> This image, or <em>prototype</em>, calls forth some level of emotional arousal that is primarily responsible for willingness-to-pay—and the image is the same in all cases. As for scope, it gets tossed out the window—no human can visualize 2,000 birds at once, let alone 200,000. The usual finding is that <em>exponential</em> increases in scope create <em>linear</em> increases in willingness-to-pay—perhaps corresponding to the linear time for our eyes to glaze over the zeroes; this small amount of affect is added, not multiplied, with the prototype affect. This hypothesis is known as “valuation by prototype.”</p>
    <p>An alternative hypothesis is “purchase of moral satisfaction.” People spend enough money to create a <em>warm glow</em> in themselves, a sense of having done their duty. The level of spending needed to purchase a warm glow depends on personality and financial situation, but it certainly has nothing to do with the number of birds.</p>
    <p>We are insensitive to scope even when human lives are at stake: Increasing the alleged risk of chlorinated drinking water from 0.004 to 2.43 annual deaths per 1,000—a factor of 600—increased willingness-to-pay from $3.78 to $15.23.<span class="footnote">Richard T. Carson and Robert Cameron Mitchell, “Sequencing and Nesting in Contingent Valuation Surveys,” <em>Journal of Environmental Economics and Management</em> 28, no. 2 (1995): 155–173, doi:10.1006/jeem.1995.1011.</span> Baron and Greene found no effect from varying lives saved by a factor of 10.<span class="footnote">Jonathan Baron and Joshua D. Greene, “Determinants of Insensitivity to Quantity in Valuation of Public Goods: Contribution, Warm Glow, Budget Constraints, Availability, and Prominence,” <em>Journal of Experimental Psychology: Applied</em> 2, no. 2 (1996): 107–125, doi:10.1037/1076-898X.2.2.107.</span></p>
    <p>A paper entitled “Insensitivity to the value of human life: A study of psychophysical numbing” collected evidence that our perception of human deaths follows Weber’s Law—obeys a logarithmic scale where the “just noticeable difference” is a constant fraction of the whole. A proposed health program to save the lives of Rwandan refugees garnered far higher support when it promised to save 4,500 lives in a camp of 11,000 refugees, rather than 4,500 in a camp of 250,000. A potential disease cure had to promise to save far more lives in order to be judged worthy of funding, if the disease was originally stated to have killed 290,000 rather than 160,000 or 15,000 people per year.<span class="footnote">David Fetherstonhaugh et al., “Insensitivity to the Value of Human Life: A Study of Psychophysical Numbing,” <em>Journal of Risk and Uncertainty</em> 14, no. 3 (1997): 283–300, doi:10.1023/A:1007744326393.</span></p>
    <p>The moral: If you want to be an effective altruist, you have to think it through with the part of your brain that processes those unexciting inky zeroes on paper, not just the part that gets real worked up about that poor struggling oil-soaked bird.</p>
  </Chapter>;
}