import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function AschsConformityExperiment() {
  return <Chapter title={["Asch's Conformity", "Experiment"]}>

    <p><span className="dropCap">S</span>olomon Asch, with experiments originally carried out in the 1950s and well- replicated since, highlighted a phenomenon now known as “conformity.” In the classic experiment, a subject sees a puzzle like the one in the nearby dia- gram: Which of the lines <em>A</em>, <em>B</em>, and <em>C</em> is the same size as the line <em>X</em>? Take a moment to determine your own answer…</p>
    <figure>
      <img src="https://www.readthesequences.com/wiki/uploads/asch2.png" alt="diagram: four vertical line segments of different lengths, marked X, A, B, and C" title="diagram: four vertical line segments of different lengths, marked X, A, B, and C" />
    </figure>
    <p>The gotcha is that the subject is seated alongside a number of other people looking at the diagram—seemingly other subjects, actually confederates of the experimenter. The other “subjects” in the experiment, one after the other, say that line <em>C</em> seems to be the same size as <em>X</em>. The real subject is seated next-to-last. How many people, placed in this situation, would say “<em>C</em>”—giving an obviously incorrect answer that agrees with the unanimous answer of the other subjects? What do you think the percentage would be?</p>
    <p>Three-quarters of the subjects in Asch’s experiment gave a “conforming” answer at least once. A third of the subjects conformed more than half the time.</p>
    <p>Interviews after the experiment showed that while most subjects claimed to have not really believed their conforming answers, some said they’d really thought that the conforming option was the correct one.</p>
    <p>Asch was disturbed by these results:</p>
    <blockquote>
      <p>That we have found the tendency to conformity in our society so strong… is a matter of concern. It raises questions about our ways of education and about the values that guide our conduct.<span class="footnote">Solomon E. Asch, “Studies of Independence and Conformity: A Minority of One Against a Unanimous Majority,” <em>Psychological Monographs</em> 70 (1956).</span></p>
    </blockquote>
    <p>It is not a trivial question whether the subjects of Asch’s experiments behaved <em>irrationally</em>. Robert Aumann’s Agreement Theorem shows that honest Bayesians cannot agree to disagree—if they have common knowledge of their probability estimates, they have the same probability estimate. Aumann’s Agreement Theorem was proved more than twenty years after Asch’s experiments, but it only formalizes and strengthens an intuitively obvious point—other people’s beliefs are often legitimate evidence.</p>
    <p>If you were looking at a diagram like the one above, but you knew <em>for a fact</em> that the other people in the experiment were honest and seeing the same diagram as you, and three other people said that <em>C</em> was the same size as <em>X</em>, then what are the odds that <em>only you</em> are the one who’s right? I lay claim to no advantage of <em>visual</em> reasoning—I don’t think I’m better than an average human at judging whether two lines are the same size. In terms of individual rationality, I hope I would notice my own severe confusion and then assign &gt;50% probability to the majority vote.</p>
    <p>In terms of group rationality, seems to me that the proper thing for an honest rationalist to say is, “How surprising, it <em>looks</em> to me like <em>B</em> is the same size as <em>X</em>. But if we’re all looking at the same diagram and reporting honestly, I have no reason to believe that my assessment is better than yours.” The last sentence is important—it’s a much weaker claim of disagreement than, “Oh, <em>I</em> see the optical illusion—I understand why you think it’s <em>C</em>, of course, but the real answer is <em>B</em>.”</p>
    <p>So the conforming subjects in these experiments are not <em>automatically</em> convicted of irrationality, based on what I’ve described so far. But as you might expect, the devil is in the details of the experimental results. According to a meta-analysis of over a hundred replications by Smith and Bond:<span class="footnote">Rod Bond and Peter B. Smith, “Culture and Conformity: A Meta-Analysis of Studies Using Asch’s (1952b, 1956) Line Judgment Task,” <em>Psychological Bulletin</em> 119 (1996): 111–137.</span></p>
    <p>Conformity increases strongly up to 3 confederates, but doesn’t increase further up to 10–15 confederates. If people are conforming rationally, then the opinion of 15 other subjects should be substantially stronger evidence than the opinion of 3 other subjects.</p>
    <p>Adding a single dissenter—just one other person who gives the correct answer, or even an incorrect answer that’s different from the group’s incorrect answer—reduces conformity <em>very</em> sharply, down to 5–10% of subjects. If you’re applying some intuitive version of Aumann’s Agreement to think that when 1 person disagrees with 3 people, the 3 are probably right, then in most cases you should be equally willing to think that 2 people will disagree with 6 people. (Not automatically true, but true <em>ceteris paribus</em>.) On the other hand, if you’ve got people who are emotionally nervous about being the odd one out, then it’s easy to see how a single other person who agrees with you, or even a single other person who disagrees with the group, would make you much less nervous.</p>
    <p>Unsurprisingly, subjects in the one-dissenter condition did not think their nonconformity had been influenced or enabled by the dissenter. Like the 90% of drivers who think they’re <del>above-average</del> in the top 50%, some of them may be right about this, but not all. People are not self-aware of the causes of their conformity or dissent, which weighs against trying to argue them as manifestations of rationality. For example, in the hypothesis that people are socially-rationally choosing to lie in order to not stick out, it appears that (at least some) subjects in the one-dissenter condition do not consciously anticipate the “conscious strategy” they would employ when faced with unanimous opposition.</p>
    <p>When the single dissenter suddenly switched to <em>conforming to the group</em>, subjects’ conformity rates went back up to just as high as in the no-dissenter condition. Being the first dissenter is a valuable (and costly!) social service, but you’ve got to keep it up.</p>
    <p>Consistently within and across experiments, all-female groups (a female subject alongside female confederates) conform significantly more often than all-male groups. Around one-half the women conform more than half the time, versus a third of the men. If you argue that the average subject is rational, then apparently women are too agreeable and men are too disagreeable, so neither group is actually <em>rational</em>…</p>
    <p>Ingroup-outgroup manipulations (e.g., a handicapped subject alongside other handicapped subjects) similarly show that conformity is significantly higher among members of an ingroup.</p>
    <p>Conformity is lower in the case of blatant diagrams, like the one at the beginning of this essay, versus diagrams where the errors are more subtle. This is hard to explain if (all) the subjects are making a socially rational decision to avoid sticking out.</p>
    <p>Paul Crowley reminds me to note that when subjects can respond in a way that will not be seen by the group, conformity also drops, which also argues against an Aumann interpretation.</p>
  </Chapter>;
}