import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function GuardiansOfAynRand() {
  return <Chapter title={["Guardians of Ayn Rand"]}>

    <blockquote>
      <p>For skeptics, the idea that reason can lead to a cult is absurd. The characteristics of a cult are 180 degrees out of phase with reason. But as I will demonstrate, not only can it happen, it has happened, and to a group that would have to be considered the unlikeliest cult in history. It is a lesson in what happens when the truth becomes more important than the search for truth…</p>
      <p>—Michael Shermer, “The Unlikeliest Cult in History”<span class="footnote">Michael Shermer, “The Unlikeliest Cult in History,” <em>Skeptic</em> 2, no. 2 (1993): 74–81, http://www.2think.org/02_2_she.shtml.</span></p>
    </blockquote>
    <p><span className="dropCap">I</span> think Michael Shermer is over-explaining Objectivism. I’ll get around to amplifying on that.</p>
    <p>Ayn Rand’s novels glorify technology, capitalism, individual defiance of the System, limited government, private property, selfishness. Her ultimate fictional hero, John Galt, was <spoiler>a scientist who invented a new form of cheap renewable energy; but then refuses to give it to the world since the profits will only be stolen to prop up corrupt governments.</spoiler></p>
    <p>And then—somehow—it all turned into a moral and philosophical “closed system” with Ayn Rand at the center. The term “closed system” is not my own accusation; it’s the term the Ayn Rand Institute uses to describe Objectivism.</p>
    <p>Objectivism is defined by the works of Ayn Rand. Now that Rand is dead, Objectivism is closed. If you disagree with Rand’s works in any respect, you cannot be an Objectivist.</p>
    <p>Max Gluckman once said: “A science is any discipline in which the fool of this generation can go beyond the point reached by the genius of the last generation.” Science moves forward by slaying its heroes, as Newton fell to Einstein. Every young physicist dreams of being the new champion that future physicists will dream of dethroning.</p>
    <p>Ayn Rand’s philosophical idol was Aristotle. Now maybe Aristotle was a hot young math talent 2,350 years ago, but math has made noticeable progress since his day. Bayesian probability theory is the quantitative logic of which Aristotle’s qualitative logic is a special case; but there’s no sign that Ayn Rand knew about Bayesian probability theory when she wrote her magnum opus, <em>Atlas Shrugged</em>. Rand wrote about “rationality,” yet failed to familiarize herself with the modern research in heuristics and biases. How can anyone claim to be a master rationalist, yet know nothing of such elementary subjects?</p>
    <p>“Wait a minute,” objects the reader, “that’s not quite fair! <em>Atlas Shrugged</em> was published in 1957! Practically nobody knew about Bayes back then.” Bah. Next you’ll tell me that Ayn Rand died in 1982, and had no chance to read <em>Judgment Under Uncertainty: Heuristics and Biases</em>, which was published that same year.</p>
    <p>Science isn’t fair. That’s sorta the point. An aspiring rationalist in 2007 starts with a huge advantage over an aspiring rationalist in 1957. It’s how we know that progress has occurred.</p>
    <p>To me the thought of voluntarily embracing a system explicitly tied to the beliefs of one human being, who’s <em>dead</em>, falls somewhere between the silly and the suicidal. A computer isn’t five years old before it’s obsolete.</p>
    <p>The vibrance that Rand admired in science, in commerce, in every railroad that replaced a horse-and-buggy route, in every skyscraper built with <em>new</em> architecture—it all comes from the principle of <em>surpassing the ancient masters</em>. How can there be science, if the most knowledgeable scientist there will ever be, has already lived? Who would raise the New York skyline that Rand admired so, if the tallest building that would ever exist, had already been built?</p>
    <p>And yet Ayn Rand acknowledged no superior, in the past, or in the future yet to come. Rand, who began in admiring reason and individuality, ended by ostracizing anyone who dared contradict her. Shermer:</p>
    <blockquote>
      <p>[Barbara] Branden recalled an evening when a friend of Rand’s remarked that he enjoyed the music of Richard Strauss. “When he left at the end of the evening, Ayn said, in a reaction becoming increasingly typical, ‘Now I understand why he and I can never be real soulmates. The distance in our sense of life is too great.’ ” Often she did not wait until a friend had left to make such remarks.</p>
    </blockquote>
    <p>Ayn Rand changed over time, one suspects.</p>
    <p>Rand grew up in Russia, and witnessed the Bolshevik revolution firsthand.</p>
    <p>She was granted a visa to visit American relatives at the age of 21, and she never returned. It’s easy to hate authoritarianism when you’re the victim. It’s easy to champion the freedom of the individual, when you are yourself the oppressed.</p>
    <p>It takes a much stronger constitution to fear authority when <em>you</em> have the power. When people are looking to <em>you</em> for answers, it’s harder to say “What the hell do I know about music? I’m a writer, not a composer,” or “It’s hard to see how liking a piece of music can be untrue.”</p>
    <p>When you’re the one crushing those who dare offend you, the exercise of power somehow seems much more <em>justifiable</em> than when you’re the one being crushed. All sorts of excellent justifications somehow leap to mind.</p>
    <p>Michael Shermer goes into detail on how he thinks that Rand’s philosophy ended up descending into cultishness. In particular, Shermer says (it seems) that Objectivism failed because Rand thought that certainty was possible, while science is never certain. I can’t back Shermer on that one. The atomic theory of chemistry is pretty damned certain. But chemists haven’t become a cult.</p>
    <p>Actually, I think Shermer’s falling prey to correspondence bias by supposing that there’s any particular correlation between Rand’s philosophy and the way her followers formed a cult. Every cause wants to be a cult.</p>
    <p>Ayn Rand fled the Soviet Union, wrote a book about individualism that a lot of people liked, got plenty of compliments, and formed a coterie of admirers. Her admirers found nicer and nicer things to say about her (happy death spiral), and she enjoyed it too much to tell them to shut up. She found herself with the power to crush those of whom she disapproved, and she didn’t resist the temptation of power.</p>
    <p>Ayn Rand and Nathaniel Branden carried on a secret extramarital affair. (With permission from both their spouses, which counts for a lot in my view. If you want to turn that into a “problem,” you have to specify that the spouses were <em>unhappy</em>—and then it’s still not a matter for outsiders.) When Branden was revealed to have “cheated” on Rand with yet another woman, Rand flew into a fury and excommunicated him. Many Objectivists broke away when news of the affair became public.</p>
    <p>Who stayed with Rand, rather than following Branden, or leaving Objectivism altogether? Her <em>strongest</em> supporters. Who departed? The previous voices of moderation. (Evaporative cooling of group beliefs.) Ever after, Rand’s grip over her remaining coterie was absolute, and no questioning was allowed.</p>
    <p>The only extraordinary thing about the whole business, is how ordinary it was.</p>
    <p>You might think that a belief system which praised “reason” and “rationality” and “individualism” would have gained some kind of special immunity, somehow…?</p>
    <p>Well, it didn’t.</p>
    <p>It worked around as well as putting a sign saying “Cold” on a refrigerator that wasn’t plugged in.</p>
    <p>The active effort required to resist the slide into entropy wasn’t there, and decay inevitably followed.</p>
    <p>And if you call that the “unlikeliest cult in history,” you’re just calling reality nasty names.</p>
    <p>Let that be a lesson to all of us: Praising “rationality” counts for nothing. Even saying “You must justify your beliefs through Reason, not by agreeing with the Great Leader” just runs a little automatic program that takes whatever the Great Leader says and generates a justification that your fellow followers will view as Reason-able.</p>
    <p>So where is the true art of rationality to be found? Studying up on the math of probability theory and decision theory. Absorbing the cognitive sciences like evolutionary psychology, or heuristics and biases. Reading history books…</p>
    <p>“Study science, not just me!” is probably the most important piece of advice Ayn Rand should’ve given her followers and didn’t. There’s no one human being who ever lived, whose shoulders were broad enough to bear all the weight of a true science with many contributors.</p>
    <p>It’s noteworthy, I think, that Ayn Rand’s fictional heroes were architects and engineers; John Galt, her ultimate, was a physicist; and yet Ayn Rand herself wasn’t a great scientist. As far as I know, she wasn’t particularly good at math. She could not aspire to rival her own heroes. Maybe that’s why she began to lose track of the will to keep improving herself.</p>
    <p>Now me, y’know, I admire Francis Bacon’s audacity, but I retain my ability to bashfully confess, “If I could go back in time, and somehow make Francis Bacon understand the problem I’m currently working on, his eyeballs would pop out of their sockets like champagne corks and explode.”</p>
    <p>I admire Newton’s accomplishments. But my attitude toward a woman’s right to vote bars me from accepting Newton as a moral paragon. Just as my knowledge of Bayesian probability bars me from viewing Newton as the ultimate unbeatable source of mathematical knowledge. And my knowledge of Special Relativity, paltry and little-used though it may be, bars me from viewing Newton as the ultimate authority on physics.</p>
    <p>Newton couldn’t realistically have discovered any of the ideas I’m lording over him—<em>but progress isn’t fair! That’s the point!</em></p>
    <p>Science has heroes, but no gods. The great Names are not our superiors, or even our rivals; they are passed milestones on our road. And the most important milestone is the hero yet to come.</p>
    <p>To be one more milestone in humanity’s road is the best that can be said of anyone; but this seemed too lowly to please Ayn Rand. And that is how she became a mere Ultimate Prophet.</p>
  </Chapter>;
}