import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function TheHaloEffect() {
  return <Chapter title={["The Halo Effect"]}>
    <p><span className="dropCap">T</span>he affect heuristic is how an overall feeling of goodness or badness contributes to many other judgments, whether it’s logical or not, whether you’re aware of it or not. Subjects told about the benefits of nuclear power are likely to rate it as having fewer risks; stock analysts rating unfamiliar stocks judge them as generally good or generally bad—low risk and high returns, or high risk and low returns—in defiance of ordinary economic theory, which says that risk and return should correlate positively.</p>
    <p>The halo effect is the manifestation of the affect heuristic in social psychology. Robert Cialdini, in <em>Influence: Science and Practice</em>,<span className="footnote">Robert B. Cialdini, <em>Influence: Science and Practice</em> (Boston: Allyn &amp; Bacon, 2001). </span> summarizes:</p>
    <blockquote>
      <p>
        <span>Research has shown that we automatically assign to good-looking individuals such favorable traits as talent, kindness, honesty, and intelligence (for a review of this evidence, see Eagly, Ashmore, Makhijani, and Longo, 1991).</span><span className="footnote">Alice H. Eagly et al., “What Is Beautiful Is Good, But… A Meta-analytic Review of Research on the Physical Attractiveness Stereotype,” <em>Psychological Bulletin</em> 110 (1 1991): 109–128, doi:10.1037/0033-2909.110.1.109.</span><span> Furthermore, we make these judgments without being aware that physical attractiveness plays a role in the process. Some consequences of this unconscious assumption that “good-looking equals good” scare me. For example, a study of the 1974 Canadian federal elections found that attractive candidates received more than two and a half times as many votes as unattractive candidates.</span><span className="footnote">M. G. Efran and E. W. J. Patterson, “The Politics of Appearance” (Unpublished PhD thesis, 1976).</span><span> Despite such evidence of favoritism toward handsome politicians, follow-up research demonstrated that voters did not realize their bias. In fact, 73 percent of Canadian voters surveyed denied in the strongest possible terms that their votes had been influenced by physical appearance; only 14 percent even allowed for the possibility of such influence.</span><span className="footnote">Ibid.</span><span> Voters can deny the impact of attractiveness on electability all they want, but evidence has continued to confirm its troubling presence.</span><span className="footnote">Thomas Lee Budesheim and Stephen DePaola, “Beauty or the Beast?: The Effects of Appearance, Personality, and Issue Information on Evaluations of Political Candidates,” <em>Personality and Social Psychology Bulletin</em> 20 (4 1994): 339–348, doi:10.1177/0146167294204001.</span>
      </p>
      <p>A similar effect has been found in hiring situations. In one study, good grooming of applicants in a simulated employment interview accounted for more favorable hiring decisions than did job qualifications—this, even though the interviewers claimed that appearance played a small role in their choices (Mack and Rainey, 1990).<span className="footnote">Denise Mack and David Rainey, “Female Applicants’ Grooming and Personnel Selection,” <em>Journal of Social Behavior and Personality</em> 5 (5 1990): 399–407.</span> The advantage given to attractive workers extends past hiring day to payday. Economists examining US and Canadian samples have found that attractive individuals get paid an average of 12–14 percent more than their unattractive coworkers (Hamermesh and Biddle, 1994).<span className="footnote">Daniel S. Hamermesh and Jeff E. Biddle, “Beauty and the Labor Market,” <em>The American Economic Review</em> 84 (5 1994): 1174–1194.</span></p>
      <p>Equally unsettling research indicates that our judicial process is similarly susceptible to the influences of body dimensions and bone structure. It now appears that good-looking people are likely to receive highly favorable treatment in the legal system (see Castellow, Wuensch, and Moore, 1991; and Downs and Lyons, 1990, for reviews).<span className="footnote">Wilbur A. Castellow, Karl L. Wuensch, and Charles H. Moore, “Effects of Physical Attractiveness of the Plaintiff and Defendant in Sexual Harassment Judgments,” <em>Journal of Social Behavior and Personality</em> 5 (6 1990): 547–562; A. Chris Downs and Phillip M. Lyons, “Natural Observations of the Links Between Attractiveness and Initial Legal Judgments,” <em>Personality and Social Psychology Bulletin</em> 17 (5 1991): 541–547, doi:10.1177/0146167291175009.</span> For example, in a Pennsylvania study (Stewart, 1980),<span className="footnote">John E. Stewart, “Defendants’ Attractiveness as a Factor in the Outcome of Trials: An Observational Study,” <em>Journal of Applied Social Psychology</em> 10 (4 1980): 348–361, doi:10.1111/j.1559-1816.1980.tb00715.x.</span> researchers rated the physical attractiveness of 74 separate male defendants at the start of their criminal trials. When, much later, the researchers checked court records for the results of these cases, they found that the handsome men had received significantly lighter sentences. In fact, attractive defendants were twice as likely to avoid jail as unattractive defendants. In another study—this one on the damages awarded in a staged negligence trial—a defendant who was better looking than his victim was assessed an average amount of $5,623; but when the victim was the more attractive of the two, the average compensation was $10,051. What’s more, both male and female jurors exhibited the attractiveness-based favoritism (Kulka and Kessler, 1978).<span className="footnote">Richard A. Kulka and Joan B. Kessler, “Is Justice Really Blind?: The Effect of Litigant Physical Attractiveness on Judicial Judgment,” <em>Journal of Applied Social Psychology</em> 8 (4 1978): 366–381, doi:10.1111/j.1559-1816.1978.tb00790.x.</span></p>

      <p>Other experiments have demonstrated that attractive people are more likely to obtain help when in need<span className="footnote">Peter L. Benson, Stuart A. Karabenick, and Richard M. Lerner, “Pretty Pleases: The Effects of Physical Attractiveness, Race, and Sex on Receiving Help,” <em>Journal of Experimental Social Psychology</em> 12 (5 1976): 409–415, doi:10.1016/0022-1031(76)90073-1.</span> and are more persuasive in changing the opinions of an audience<span className="footnote">Shelly Chaiken, “Communicator Physical Attractiveness and Persuasion,” <em>Journal of Personality and Social Psychology</em> 37 (8 1979): 1387–1397, doi:10.1037/0022-3514.37.8.1387.</span></p>
    </blockquote>


    <p>The influence of attractiveness on ratings of intelligence, honesty, or kindness is a clear example of bias—especially when you judge these other qualities based on fixed text—because we wouldn’t expect judgments of honesty and attractiveness to conflate for any legitimate reason. On the other hand, how much of my perceived intelligence is due to my honesty? How much of my perceived honesty is due to my intelligence? Finding the truth, and saying the truth, are not as widely separated in nature as looking pretty and looking smart…</p>
    <p>But these studies on the halo effect of attractiveness should make us suspicious that there may be a similar halo effect for kindness, or intelligence. Let’s say that you know someone who not only seems very intelligent, but also honest, altruistic, kindly, and serene. You should be suspicious that some of these perceived characteristics are influencing your perception of the others. Maybe the person is genuinely intelligent, honest, and altruistic, but not all that kindly or serene. You should be suspicious if the people you know seem to separate too cleanly into devils and angels.</p>
    <p>And—I know you don’t think <em>you</em> have to do it, but maybe <em>you</em> should—be just a little more skeptical of the more attractive political candidates.</p>
  </Chapter>;
}