import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function HandVsFingers() {
  return <Chapter title={["Hand vs. Fingers"]}>


    <p><span className="dropCap">B</span>ack to our original topic: Reductionism and the Mind Projection Fallacy. There can be emotional problems in accepting reductionism, if you think that things have to be fundamental to be fun. But this position commits us to never taking joy in anything more complicated than a quark, and so I prefer to reject it.</p>
    <p>To review, the reductionist thesis is that we use multi-level models for computational reasons, but physical reality has only a single level.</p>
    <p>Here I’d like to pose the following conundrum: When you pick up a cup of water, is it your <em>hand</em> that picks it up?</p>
    <p>Most people, of course, go with the naive popular answer: “Yes.”</p>
    <p>Recently, however, scientists have made a stunning discovery: It’s not your <em>hand</em> that holds the cup, it’s actually your fingers, thumb, and palm.</p>
    <p>Yes, I know! I was shocked too. But it seems that after scientists measured the forces exerted on the cup by each of your fingers, your thumb, and your palm, they found there was no force left over—so the force exerted by your <em>hand</em> must be zero.</p>
    <p>The theme here is that, if you can see <em>how</em> (not just <em>know that</em>) a higher level reduces to a lower one, they will not seem like separate things within your map; you will be able to <em>see</em> how silly it is to think that your fingers could be in one place, and your hand somewhere else; you will be able to <em>see</em> how silly it is to argue about whether it is your hand that picks up the cup, or your fingers.</p>
    <p>The operative word is “see,” as in concrete visualization. Imagining your hand causes you to imagine the fingers and thumb and palm; conversely, imagining fingers and thumb and palm causes you to identify a hand in the mental picture. Thus the high level <em>of your map</em> and the low level <em>of your map</em> will be tightly bound together <em>in your mind</em>.</p>
    <p>In reality, of course, the levels are bound together even tighter than that— bound together by the tightest possible binding: physical identity. You can <em>see</em> this: You can see that saying (1) “hand” or (2) “fingers and thumb and palm,” does not refer to different <em>things</em>, but different <em>points of view</em>.</p>
    <p>But suppose you lack the knowledge to so tightly bind together the levels of your map. For example, you could have a “hand scanner” that showed a “hand” as a dot on a map (like an old-fashioned radar display), and similar scanners for fingers/thumbs/palms; then you would see a cluster of dots around the hand, but you would be able to <em>imagine</em> the hand-dot moving off from the others. So, even though the physical reality of the hand (that is, the thing the dot corresponds to) was identical with / strictly composed of the physical realities of the fingers and thumb and palm, you would not be able to see this fact; even if someone told you, or you guessed from the correspondence of the dots, you would only <em>know</em> the fact of reduction, not <em>see</em> it. You would still be able to <em>imagine</em> the hand dot moving around independently, even though, if the physical makeup of the sensors were held constant, it would be physically impossible for this to actually happen.</p>
    <p>Or, at a still lower level of binding, people might just tell you “There’s a hand over there, and some fingers over there”—in which case you would know little more than a Good-Old-Fashioned AI representing the situation using suggestively named lisp tokens. There wouldn’t be anything <em>obviously</em> contradictory about asserting:</p>
    <p>⊢Inside(Room,Hand)</p>
    <p>⊢¬Inside(Room,Fingers) ,</p>
    <p>because you would not possess the <em>knowledge</em></p>
    <p>⊢Inside(x,Hand) ⇒ Inside(x,Fingers) .</p>
    <p>None of this says that a hand can actually detach its existence from your fingers and crawl, ghostlike, across the room; it just says that a Good-Old-Fashioned AI with a propositional representation may not <em>know</em> any better. The map is not the territory.</p>
    <p>In particular, you shouldn’t draw too many conclusions from how it seems <em>conceptually possible</em>, in the mind of some specific conceiver, to separate the hand from its constituent elements of fingers, thumb, and palm. Conceptual possibility is not the same as logical possibility or physical possibility.</p>
    <p>It is <em>conceptually</em> possible <em>to you</em> that 235,757 is prime, because you don’t know any better. But it isn’t <em>logically</em> possible that 235,757 is prime; if you were logically omniscient, 235,757 would be obviously composite (and you would know the factors). That’s why we have the notion of impossible possible worlds, so that we can put probability distributions on propositions that may or may not be <em>in fact</em> logically impossible.</p>
    <p>And you can imagine philosophers who criticize “eliminative fingerists” who contradict the direct facts of experience—we can <em>feel</em> our hand holding the cup, after all—by suggesting that “hands” <em>don’t really exist</em>, in which case, obviously, the cup would fall down. And philosophers who suggest “appendigital bridging laws” to explain how a particular configuration of fingers evokes a hand into existence—with the note, of course, that while our world contains those particular appendigital bridging laws, the laws could have been conceivably different, and so are not in any sense <em>necessary facts</em>, etc.</p>
    <p>All of these are cases of Mind Projection Fallacy, and what I call “naive philosophical realism”—the confusion of philosophical intuitions for direct, veridical information about reality. Your inability to imagine something is just a computational fact about what your brain can or can’t imagine. Another brain might work differently.</p>
  </Chapter>;
}