import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function HeatVsMotion() {
  return <Chapter title={["Heat vs. Motion"]}>


    <p><span className="dropCap">A</span>fter the last essay, it occurred to me that there’s a much simpler example of reductionism jumping a gap of apparent-difference-in-kind: the reduction of heat to motion.</p>
    <p>Today, the equivalence of heat and motion may seem too obvious in hindsight—everyone says that “heat is motion,” therefore, it can’t be a “weird” belief.</p>
    <p>But there was a time when the kinetic theory of heat was a highly controversial scientific hypothesis, contrasting to belief in a caloric fluid that flowed from hot objects to cold objects. Still earlier, the main theory of heat was “Phlogiston!”</p>
    <p>Suppose you’d <em>separately</em> studied kinetic theory and caloric theory. You now know something about kinetics: collisions, elastic rebounds, momentum, kinetic energy, gravity, inertia, free trajectories. Separately, you know something about heat: temperatures, pressures, combustion, heat flows, engines, melting, vaporization.</p>
    <p>Not only is this state of knowledge a plausible one, it is the state of knowledge possessed by e.g. Sadi Carnot, who, working strictly from within the caloric theory of heat, developed the principle of the Carnot cycle—a heat engine of maximum efficiency, whose existence implies the Second Law of Thermodynamics. This in 1824, when kinetics was a highly developed science.</p>
    <p>Suppose, like Carnot, you know a great deal about kinetics, and a great deal about heat, as <em>separate</em> entities. Separate entities of <em>knowledge</em>, that is: your brain has separate filing baskets for beliefs about kinetics and beliefs about heat. But from the inside, this state of knowledge <em>feels</em> like living in a world of moving things and hot things, a world where motion and heat are independent properties of matter.</p>
    <p>Now a Physicist From The Future comes along and tells you: “Where there is heat, there is motion, and vice versa. That’s why, for example, rubbing things together makes them hotter.”</p>
    <p>There are (at least) two possible interpretations you could attach to this statement, “Where there is heat, there is motion, and vice versa.”</p>
    <p>First, you could suppose that heat and motion exist separately—that the caloric theory is correct—but that among our universe’s physical laws is a “bridging law” which states that, where objects are moving quickly, caloric will come into existence. And conversely, another bridging law says that caloric can exert pressure on things and make them move, which is why a hotter gas exerts more pressure on its enclosure (thus a steam engine can use steam to drive a piston).</p>
    <p>Second, you could suppose that heat and motion are, in some as-yet-mysterious sense, <em>the same thing</em>.</p>
    <p>“Nonsense,” says Thinker 1, “the words ‘heat’ and ‘motion’ have two different meanings; that is why we have two different words. We know how to determine when we will call an observed phenomenon ‘heat’—heat can melt things, or make them burst into flame. We know how to determine when we will say that an object is ‘moving quickly’—it changes position; and when it crashes, it may deform, or shatter. Heat is concerned with change of substance; motion, with change of position and shape. To say that these two words have the same meaning is simply to confuse yourself.”</p>
    <p>“Impossible,” says Thinker 2. “It may be that, in our world, heat and motion are associated by bridging laws, so that it is a law of physics that motion creates caloric, and vice versa. But I can easily imagine a world where rubbing things together does <em>not</em> make them hotter, and gases <em>don’t</em> exert more pressure at higher temperatures. Since there are possible worlds where heat and motion are not associated, they must be different properties—this is true a priori.”</p>
    <p>Thinker 1 is confusing the quotation and the referent: 2 + 2 = 4, but “2 + 2” ≠ “4.” The string “2 + 2” contains five characters (including whitespace) and the string “4” contains only one character. If you type the two strings into a Python interpreter, they yield the same output, &gt;&gt;&gt; 4. So you can’t conclude, from looking at the strings “2 + 2” and “4,” that just because the strings are different, they must have different “meanings” relative to the Python Interpreter.</p>
    <p>The words “heat” and “kinetic energy” can be said to “refer to” the same thing, even before we <em>know</em> how heat reduces to motion, in the sense that we don’t know yet what the referent is, but the referents are in fact the same. You might imagine an Idealized Omniscient Science Interpreter that would give the same output when we typed in “heat” and “kinetic energy” on the command line.</p>
    <p>I talk about the Science Interpreter to emphasize that, to dereference the pointer, you’ve got to step outside cognition. The end result of the dereference is something out there in reality, not in anyone’s mind. So you can <em>say</em> “real referent” or “actual referent,” but you can’t <em>evaluate</em> the words locally, from the inside of your own head. You can’t reason using the actual heat-referent—if you thought using <em>real heat</em>, thinking “one million Kelvin” would vaporize your brain. But, by forming a belief about your belief about heat, you can talk <em>about</em> your belief about heat, and say things like “It’s possible that my belief about heat doesn’t much resemble <em>real</em> heat.” You can’t actually perform that comparison right there in your own mind, but you can talk <em>about</em> it.</p>
    <p>Hence you can say, “My beliefs about heat and motion are not the same beliefs, but it’s possible that actual heat and actual motion are the same thing.” It’s just like being able to acknowledge that “the morning star” and “the evening star” might be the same planet, while also understanding that you can’t determine this just by examining your beliefs—you’ve got to haul out the telescope.</p>
    <p>Thinker 2’s mistake follows similarly. A physicist told them, “Where there is heat, there is motion” and Thinker 2 mistook this for a statement of <em>physical law</em>: The presence of caloric <em>causes</em> the existence of motion. What the physicist really means is more akin to an <em>inferential rule</em>: Where you are told there is “heat,” deduce the presence of “motion.”</p>
    <p>From this basic projection of a multilevel model into a multilevel reality follows another, distinct error: the conflation of conceptual possibility with logical possibility. To Sadi Carnot, it is <em>conceivable</em> that there could be another world where heat and motion are not associated. To Richard Feynman, armed with specific knowledge of how to derive equations about heat from equations about motion, this idea is not only inconceivable, but so wildly inconsistent as to make one’s head explode.</p>
    <p>I should note, in fairness to philosophers, that there are philosophers who have said these things. For example, Hilary Putnam, writing on the “Twin Earth” thought experiment:<span class="footnote">Hilary Putnam, “The Meaning of Meaning,” in <em>The Twin Earth Chronicles</em>, ed. Andrew Pessin and Sanford Goldberg (M. E. Sharpe, Inc., 1996), 3–52.</span></p>
    <blockquote>
      <p>Once we have discovered that water (in the actual world) is H2O, <em>nothing counts as a possible world in which water isn’t H2O</em>. In particular, if a “logically possible” statement is one that holds in some “logically possible world,” <em>it isn’t logically possible that water isn’t H2O</em>.</p>
      <p>On the other hand, we can perfectly well imagine having experiences that would convince us (and that would make it rational to believe that) water <em>isn’t</em> H2O. In that sense, it is conceivable that water isn’t H2O. It is conceivable but it isn’t logically possible! Conceivability is no proof of logical possibility.</p>
    </blockquote>
    <p>It appears to me that “water” is being used in two different senses in these two paragraphs—one in which the word “water” <em>refers</em> to what we type into the Science Interpreter, and one in which “water” <em>refers</em> to what we get out of the Science Interpreter when we type “water” into it. In the first paragraph, Hilary seems to be saying that after we do some experiments and find out that water is H2O, water becomes automatically redefined to <em>mean</em> H2O. But you could coherently hold a different position about whether the word “water” now <em>means</em> “H2O” or “whatever is <em>really</em> in that bottle next to me,” so long as you use your terms consistently.</p>
    <p>I believe the above has already been said as well? Anyway…</p>
    <p>It is quite possible for there to be only <em>one</em> thing out-there-in-the-world, but for it to take on sufficiently different forms, and for you yourself to be sufficiently ignorant of the reduction, that it feels like living in a world containing two entirely different things. Knowledge concerning these two different phenomena may be taught in two different classes, and studied by two different academic fields, located in two different buildings of your university.</p>
    <p>You’ve got to put yourself quite a ways back, into a historically realistic frame of mind, to remember how <em>different</em> heat and motion once seemed. Though, depending on how much you know today, it may not be as hard as all that, if you can look past the pressure of conventionality (that is, “heat is motion” is an un-weird belief, “heat is not motion” is a weird belief). I mean, suppose that tomorrow the physicists stepped forward and said, “Our popularizations of science have always contained one lie. Actually, heat has nothing to do with motion.” Could you <em>prove</em> they were wrong?</p>
    <p>Saying “Maybe heat and motion are the same thing!” is easy. The difficult part is explaining <em>how</em>. It takes a great deal of detailed knowledge to get yourself to the point where you can no longer <em>conceive</em> of a world in which the two phenomena go separate ways. Reduction isn’t cheap, and that’s why it buys so much.</p>
    <p>Or maybe you could say: “Reductionism is easy, reduction is hard.” But it does kinda help to be a reductionist, I think, when it comes time to go looking for a reduction.</p>
  </Chapter>;
}