import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function AdaptationExecutersNotFitnessMaximizers() {
  return <Chapter title={["Adaptation-Executers,", "Not Fitness-Maximizers"]}>
    <blockquote>
      <p>Individual organisms are best thought of as adaptation-executers rather than as fitness-maximizers.</p>
      <p>—John Tooby and Leda Cosmides,  <br />
        “The Psychological Foundations of Culture”<span class="footnote">John Tooby and Leda Cosmides, “The Psychological Foundations of Culture,” in&nbsp;<em>The Adapted Mind: Evolutionary Psychology and the Generation of Culture</em>, ed. Jerome H. Barkow, Leda Cosmides, and John Tooby (New York: Oxford University Press, 1992), 19–136.</span></p>
    </blockquote>
    <p><span className="dropCap">F</span>ifty thousand years ago, the taste buds of&nbsp;<em>Homo sapiens</em>&nbsp;directed their bearers to the scarcest, most critical food resources—sugar and fat. Calories, in a word. Today, the context of a taste bud’s function has changed, but the taste buds themselves have not. Calories, far from being scarce (in First World countries), are actively harmful. Micronutrients that were reliably abundant in leaves and nuts are absent from bread, but our taste buds don’t complain. A scoop of ice cream is a&nbsp;superstimulus, containing more sugar, fat, and salt than anything in the ancestral environment.</p>
    <p>No human being with the&nbsp;<em>deliberate</em>&nbsp;goal of maximizing their alleles’ inclusive genetic fitness would ever eat a cookie unless they were starving. But individual organisms are best thought of as adaptation-executers, not fitness-maximizers.</p>
    <p>A Phillips-head screwdriver, though its designer intended it to turn screws, won’t reconform itself to a flat-head screw to fulfill its function. We created these tools, but they exist independently of us, and they continue independently of us.</p>
    <p>The atoms of a screwdriver don’t have tiny little XML tags inside describing their “objective” purpose. The designer had something in mind, yes, but that’s not the same as what&nbsp;<em>happens</em>&nbsp;in the real world. If you forgot that the designer is a separate entity from the designed thing, you might think, “The&nbsp;<em>purpose</em>&nbsp;of the screwdriver is to drive screws”—as though this were an explicit property of the screwdriver itself, rather than a property of the designer’s state of mind. You might be surprised that the screwdriver didn’t reconfigure itself to the flat-head screw, since, after all, the screwdriver’s&nbsp;<em>purpose</em>&nbsp;is to turn screws.</p>
    <p>The&nbsp;<em>cause</em>&nbsp;of the screwdriver’s existence is the designer’s mind, which imagined an imaginary screw, and imagined an imaginary handle turning. The&nbsp;<em>actual</em>&nbsp;operation of the screwdriver, its&nbsp;<em>actual</em>&nbsp;fit to an actual screw head,&nbsp;<em>cannot</em>&nbsp;be the objective cause of the screwdriver’s existence: The future cannot cause the past. But the designer’s brain, as an actually existent thing within the past, can indeed be the cause of the screwdriver.</p>
    <p>The&nbsp;<em>consequence</em>&nbsp;of the screwdriver’s existence may not correspond to the imaginary consequences in the designer’s mind. The screwdriver blade could slip and cut the user’s hand.</p>
    <p>And the&nbsp;<em>meaning</em>&nbsp;of the screwdriver—why, that’s something that exists in the mind of a user, not in tiny little labels on screwdriver atoms. The designer may intend it to turn screws. A murderer may buy it to use as a weapon. And then accidentally drop it, to be picked up by a child, who uses it as a chisel.</p>
    <p>So the screwdriver’s&nbsp;<em>cause</em>, and its&nbsp;<em>shape</em>, and its&nbsp;<em>consequence</em>, and its various&nbsp;<em>meanings</em>, are all different things; and only&nbsp;<em>one</em>&nbsp;of these things is found within the screwdriver itself.</p>
    <p>Where do taste buds come from? Not from an intelligent designer visualizing their consequences, but from a frozen history of ancestry: Adam liked sugar and ate an apple and reproduced, Barbara liked sugar and ate an apple and reproduced, Charlie liked sugar and ate an apple and reproduced, and&nbsp;2763 generations later, the allele became fixed in the population. For convenience of thought, we sometimes compress this giant history and say: “Evolution did it.” But it’s not a quick, local event like a human designer visualizing a screwdriver. This is the&nbsp;<em>objective cause</em>&nbsp;of a taste bud.</p>
    <p>What is the&nbsp;<em>objective shape</em>&nbsp;of a taste bud? Technically, it’s a molecular sensor connected to reinforcement circuitry. This adds another level of indirection, because the taste bud isn’t directly acquiring food. It’s influencing the organism’s mind, making the organism want to eat foods that are similar to the food just eaten.</p>
    <p>What is the&nbsp;<em>objective consequence</em>&nbsp;of a taste bud? In a modern First World human, it plays out in multiple chains of causality: from the desire to eat more chocolate, to the plan to eat more chocolate, to eating chocolate, to getting fat, to getting fewer dates, to reproducing less successfully. This consequence is directly&nbsp;<em>opposite</em>&nbsp;the key regularity in the long chain of ancestral successes that caused the taste bud’s shape. But, since overeating has only recently become a problem, no significant evolution (compressed regularity of ancestry) has further influenced the taste bud’s shape.</p>
    <p>What is the&nbsp;<em>meaning</em>&nbsp;of eating chocolate? That’s between you and your moral philosophy. Personally, I think chocolate tastes good, but I wish it were less harmful; acceptable solutions would include redesigning the chocolate or redesigning my biochemistry.</p>
    <p>Smushing several of the concepts together, you could sort-of-say, “Modern humans do today what would have propagated our genes in a hunter-gatherer society, whether or not it helps our genes in a modern society.” But this still isn’t quite right, because we’re not&nbsp;<em>actually</em>&nbsp;asking ourselves which behaviors would maximize our ancestors’ inclusive fitness. And many of our activities today have no ancestral analogue. In the hunter-gatherer society there wasn’t any such thing as chocolate.</p>
    <p>So it’s better to view our taste buds as an&nbsp;<em>adaptation</em>&nbsp;fitted to ancestral conditions that included near-starvation and apples and roast rabbit, which modern humans&nbsp;<em>execute</em>&nbsp;in a new context that includes cheap chocolate and constant bombardment by advertisements.</p>
    <p>Therefore it is said: Individual organisms are best thought of as adaptation-executers, not fitness-maximizers.</p>
  </Chapter>;
}
