import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function AnEspeciallyElegantEvolutionaryPsychologyExperiment() {
  return <Chapter title={["An Especially Elegant", "Evolutionary Psychology Experiment"]}>


    <blockquote>
      <p>In a 1989 Canadian study, adults were asked to imagine the death of children of various ages and estimate which deaths would create the greatest sense of loss in a parent. The results, plotted on a graph, show grief growing until just before adolescence and then beginning to drop. When this curve was compared with a curve showing changes in reproductive potential over the life cycle (a pattern calculated from Canadian demographic data), the correlation was fairly strong. But much stronger—nearly perfect, in fact—was the correlation between the grief curves of these modern Canadians and the reproductive-potential curve of a hunter-gatherer people, the !Kung of Africa. In other words, the pattern of changing grief was almost exactly what a Darwinian would predict, given demographic realities in the ancestral environment.</p>
      <p>—Robert Wright, <em>The Moral Animal</em>,  <br />
        summarizing Crawford et al.<span class="footnote">Robert Wright, <em>The Moral Animal: Why We Are the Way We Are: The New Science of Evolutionary Psychology</em> (Pantheon Books, 1994); Charles B. Crawford, Brenda E. Salter, and Kerry L. Jang, “Human Grief: Is Its Intensity Related to the Reproductive Value of the Deceased?,” <em>Ethology and Sociobiology</em> 10, no. 4 (1989): 297–307. </span></p>
    </blockquote>
    <p><span className="dropCap">T</span>he first correlation was 0.64, the second an extremely high 0.92 (<em>N</em> = 221). The most obvious <em>in</em>elegance of this study, as described, is that it was conducted by asking human adults to imagine parental grief, rather than asking real parents with children of particular ages. (Presumably that would have cost more / allowed fewer subjects.) However, my understanding is that the results here squared well with the data from closer studies of parental grief that were looking for other correlations (i.e., a raw correlation between parental grief and child age).</p>
    <p>That said, consider some of this experiment’s elegant aspects:</p>
    <ol>
      <li>A correlation of 0.92(!) This may sound suspiciously high—could evolution really do such exact fine-tuning?—until you realize that this selection pressure was not only great enough to <em>fine-tune</em> parental grief, but, in fact, <em>carve it out of existence from scratch in the first place</em>.</li>
      <li>People who say that evolutionary psychology hasn’t made any advance predictions are (ironically) mere victims of “no one knows what science doesn’t know” syndrome. You wouldn’t even <em>think of this as an experiment to be performed</em> if not for evolutionary psychology.</li>
      <li>The experiment illustrates, as beautifully and as cleanly as any I have ever seen, the distinction between a <em>conscious or subconscious ulterior motive</em> and an <em>executing adaptation with no realtime sensitivity to the original selection pressure that created it</em>.</li>
    </ol>
    <p>The parental grief is <em>not even subconsciously</em> about reproductive value—otherwise it would update for Canadian reproductive value instead of !Kung reproductive value. Grief is an adaptation that now simply exists, real in the mind and continuing under its own inertia.</p>
    <p>Parents do <em>not</em> care about children for the sake of their reproductive contribution. Parents care about children for their own sake; and the <em>non-cognitive</em>, <em>evolutionary-historical</em> reason why such minds exist in the universe in the first place is that children carry their parents’ genes.</p>
    <p>Indeed, evolution is the reason why there are any minds in the universe at all. So you can see why I’d want to draw a sharp line through my cynicism about ulterior motives at the evolutionary-cognitive boundary; otherwise, I might as well stand up in a supermarket checkout line and say, “Hey! You’re only correctly processing visual information while bagging my groceries in order to maximize your inclusive genetic fitness!”</p>
    <p><strong>(1)</strong> I think 0.92 is the highest correlation I’ve ever seen in any evolutionary psychology experiment, and indeed, one of the highest correlations I’ve seen in any psychology experiment. (Although I’ve seen e.g. a correlation of 0.98 reported for asking one group of subjects “How similar is <em>A</em> to <em>B</em>?” and another group “What is the probability of <em>A</em> given <em>B</em>?” on questions like “How likely are you to draw 60 red balls and 40 white balls from this barrel of 800 red balls and 200 white balls?”—in other words, these are simply processed as the same question.)</p>
    <p>Since we are all Bayesians here, we may take our priors into account and ask if at least <em>some</em> of this unexpectedly high correlation is due to luck. The evolutionary fine-tuning we can probably take for granted; this is a huge selection pressure we’re talking about. The remaining sources of suspiciously low variance are (a) whether a large group of adults could correctly envision, on average, relative degrees of parental grief (apparently they can), and (b) whether the surviving !Kung are <em>typical</em> ancestral hunter-gatherers in this dimension, or whether variance <em>between</em> hunter-gatherer tribal types should have been too high to allow a correlation of 0.92.</p>
    <p>But even after taking into account any skeptical priors, correlation 0.92 and <em>N</em> = 221 is pretty strong evidence, and our posteriors should be less skeptical on all these counts.</p>
    <p><strong>(2)</strong> You might think it an inelegance of the experiment that it was performed <em>prospectively</em> on imagined grief, rather than retrospectively on real grief. But it is <em>prospectively</em> imagined grief that will actually operate to steer parental behavior <em>away</em> from losing the child! From an evolutionary standpoint, an actual dead child is a sunk cost; evolution “wants” the parent to learn from the pain, not do it again, adjust back to their hedonic set point, and go on raising other children.</p>
    <p><strong>(3)</strong> Similarly, the graph that correlates to parental grief is for <em>the future reproductive potential of a child that has survived to a given age</em>, and not <em>the sunk cost of raising the child which has survived to that age</em>. (Might we get an even <em>higher</em> correlation if we tried to take into account the reproductive opportunity cost of raising a child of age <em>X</em> to independent maturity, while discarding all sunk costs to raise a child to age <em>X</em>?)</p>
    <p>Humans usually do notice sunk costs—this is presumably either an adaptation to prevent us from switching strategies too often (compensating for an overeager opportunity-noticer?) or an unfortunate spandrel of pain felt on wasting resources.</p>
    <p>Evolution, on the other hand—it’s not that evolution “doesn’t care about sunk costs,” but that evolution doesn’t even remotely “think” that way; “evolution” is just a macrofact about the real historical reproductive consequences.</p>
    <p>So—of course—the parental grief adaptation is fine-tuned in a way that has nothing to do with past investment in a child, and everything to do with the future reproductive consequences of losing that child. Natural selection isn’t crazy about sunk costs the way we are.</p>
    <p>But—of course—the parental grief adaptation goes on functioning as if the parent were living in a !Kung tribe rather than Canada. Most humans would notice the difference.</p>
    <p>Humans and natural selection are insane in <em>different stable complicated ways</em>.</p>
  </Chapter>;
}
