import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function FakeOptimizationCriteria() {
  return <Chapter title={["Fake Optimization Criteria"]}>
    <p><span className="dropCap">I</span>’ve previously dwelt in considerable length upon forms of rationalization whereby our beliefs appear to match the evidence much more strongly than they actually do. And I’m not overemphasizing the point, either. If we could beat this fundamental metabias and see what every hypothesis <em>really</em> predicted, we would be able to recover from almost any other error of fact.</p>
    <p>The mirror challenge for decision theory is seeing which option a choice criterion <em>really</em> endorses. If your stated moral principles call for you to provide laptops to everyone, does that <em>really</em> endorse buying a $1 million gem-studded laptop for yourself, or spending the same money on shipping 5,000 OLPCs?</p>
    <p>We seem to have evolved a knack for arguing that practically any goal implies practically any action. A phlogiston theorist explaining why magnesium gains weight when burned has nothing on an Inquisitor explaining why God’s infinite love for all His children requires burning some of them at the stake.</p>
    <p>There’s no mystery about this. Politics was a feature of the ancestral environment. We are descended from those who argued most persuasively that the good of the tribe meant executing their hated rival Uglak. (We sure ain’t descended from Uglak.)</p>
    <p>And yet… is it possible to <em>prove</em> that if Robert Mugabe cared <em>only</em> for the good of Zimbabwe, he would resign from its presidency? You can <em>argue</em> that the policy follows from the goal, but haven’t we just seen that humans can match up any goal to any policy? How do you know that you’re right and Mugabe is wrong? (There are a number of reasons this is a good guess, but bear with me here.)</p>
    <p>Human motives are manifold and obscure, our decision processes as vastly complicated as our brains. And the world itself is vastly complicated, on every choice of real-world policy. Can we even <em>prove</em> that human beings are rationalizing—that we’re systematically distorting the link from principles to policy—when we lack a single firm place on which to stand? When there’s no way to find out <em>exactly</em> what even a single optimization criterion implies? (Actually, you can just observe that people <em>disagree</em> about office politics in ways that strangely correlate to their own interests, while simultaneously denying that any such interests are at work. But again, bear with me here.)</p>
    <p>Where is the standardized, open-source, generally intelligent, consequentialist optimization process into which we can feed a complete morality as an XML file, to find out what that morality <em>really</em> recommends when applied to our world? Is there even a single real-world case where we can know <em>exactly</em> what a choice criterion recommends? Where is the <em>pure</em> moral reasoner—of known utility function, purged of all other stray desires that might distort its optimization—whose trustworthy output we can contrast to human rationalizations of the same utility function?</p>
    <p>Why, it’s our old friend the alien god, of course! Natural selection is guaranteed free of all mercy, all love, all compassion, all aesthetic sensibilities, all political factionalism, all ideological allegiances, all academic ambitions, all libertarianism, all socialism, all Blue and all Green. Natural selection doesn’t <em>maximize</em> its criterion of inclusive genetic fitness—it’s not that smart. But when you look at the output of natural selection, you are guaranteed to be looking at an output that was optimized <em>only</em> for inclusive genetic fitness, and not the interests of the US agricultural industry.</p>
    <p>In the case histories of evolutionary science—in, for example, The Tragedy of Group Selectionism—we can directly compare human rationalizations to the result of <em>pure</em> optimization for a known criterion. What did Wynne-Edwards think would be the result of group selection for small subpopulation sizes? Voluntary individual restraint in breeding, and enough food for everyone. What was the actual laboratory result? Cannibalism.</p>
    <p>Now you might ask: Are these case histories of evolutionary science really relevant to human morality, which doesn’t give two figs for inclusive genetic fitness when it gets in the way of love, compassion, aesthetics, healing, freedom, fairness, et cetera? Human societies didn’t even have a concept of “inclusive genetic fitness” until the twentieth century.</p>
    <p>But I ask in return: If we can’t see clearly the result of a single monotone optimization criterion—if we can’t even train ourselves to hear a single pure note—then how will we listen to an orchestra? How will we see that “Always be selfish” or “Always obey the government” are poor guiding principles for human beings to adopt—if we think that even <em>optimizing genes for inclusive fitness</em> will yield organisms that sacrifice reproductive opportunities in the name of social resource conservation?</p>
    <p>To train ourselves to see clearly, we need simple practice cases.</p>
  </Chapter>;
}
