import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function SuperstimuliAndTheCollapseOfWesternCivilization() {
  return <Chapter title={["Superstimuli and the Collapse", "of Western Civilization"]}>


    <p><span className="dropCap">A</span>t least three people have died playing online games for days without rest. People have lost their spouses, jobs, and children to <em>World of Warcraft</em>. If people have the right to play video games—and it’s hard to imagine a more fundamental right—then the market is going to respond by supplying the most <em>engaging</em> video games that can be sold, to the point that exceptionally engaged consumers are removed from the gene pool.</p>
    <p>How does a consumer product become so <em>involving</em> that, after 57 hours of using the product, the consumer would rather use the product for one more hour than eat or sleep? (I suppose one could argue that the consumer makes a rational decision that they’d rather play <em>Starcraft</em> for the next hour than live out the rest of their life, but let’s just not go there. Please.)</p>
    <p>A candy bar is a <em>superstimulus</em>: it contains more concentrated sugar, salt, and fat than anything that exists in the ancestral environment. A candy bar matches taste buds that evolved in a hunter-gatherer environment, but it matches those taste buds much more strongly than anything that actually existed <em>in</em> the hunter-gatherer environment. The signal that once reliably correlated to healthy food has been hijacked, blotted out with a point in tastespace that wasn’t in the training dataset—an impossibly distant outlier on the old ancestral graphs. Tastiness, formerly representing the evolutionarily identified correlates of healthiness, has been reverse-engineered and perfectly matched with an artificial substance. Unfortunately there’s no equally powerful market incentive to make the resulting food item as healthy as it is tasty. We can’t taste healthfulness, after all.</p>
    <p>The now-famous Dove Evolution video shows the painstaking construction of another superstimulus: an ordinary woman transformed by makeup, careful photography, and finally extensive Photoshopping, into a billboard model—a beauty impossible, unmatchable by human women in the unretouched real world. Actual women are killing themselves (e.g., supermodels using cocaine to keep their weight down) to keep up with competitors that literally don’t exist.</p>
    <p>And likewise, a video game can be so much more <em>engaging</em> than mere reality, even through a simple computer monitor, that someone will play it without food or sleep until they literally die. I don’t know all the tricks used in video games, but I can guess some of them—challenges poised at the critical point between ease and impossibility, intermittent reinforcement, feedback showing an ever-increasing score, social involvement in massively multiplayer games.</p>
    <p>Is there a limit to the market incentive to make video games more engaging? You might hope there’d be no incentive past the point where the players lose their jobs; after all, they must be able to pay their subscription fee. This would imply a “sweet spot” for the addictiveness of games, where the mode of the bell curve is having fun, and only a few unfortunate souls on the tail become addicted to the point of losing their jobs. As of 2007, playing <em>World of Warcraft</em> for 58 hours straight until you literally die <em>is</em> still the exception rather than the rule. But video game manufacturers compete against each other, and if you can make your game 5% more addictive, you may be able to steal 50% of your competitor’s customers. You can see how this problem could get a <em>lot</em> worse.</p>
    <p>If people have the right to be tempted—and that’s what free will is all about—the market is going to respond by supplying as much temptation as can be sold. The incentive is to make your stimuli 5% more tempting than those of your current leading competitors. This continues well beyond the point where the stimuli become ancestrally anomalous superstimuli. Consider how our standards of product-selling feminine beauty have changed since the advertisements of the 1950s. And as candy bars demonstrate, the market incentive also continues well beyond the point where the superstimulus begins wreaking collateral damage on the consumer.</p>
    <p>So why don’t we just say no? A key assumption of free-market economics is that, in the absence of force and fraud, people can always refuse to engage in a harmful transaction. (To the extent this is true, a free market would be, not merely the <em>best</em> policy on the whole, but a policy with few or no downsides.)</p>
    <p>An organism that regularly passes up food will die, as some video game players found out the hard way. But, on some occasions in the ancestral environment, a typically beneficial (and therefore tempting) act may in fact be harmful. Humans, as organisms, have an unusually strong ability to perceive these special cases using abstract thought. On the other hand we also tend to imagine lots of special-case consequences that don’t exist, like ancestor spirits commanding us not to eat perfectly good rabbits.</p>
    <p>Evolution seems to have struck a compromise, or perhaps just aggregated new systems on top of old. <em>Homo sapiens</em> are still tempted by food, but our oversized prefrontal cortices give us a <em>limited</em> ability to resist temptation. Not unlimited ability—our ancestors with too much willpower probably starved themselves to sacrifice to the gods, or failed to commit adultery one too many times. The video game players who died must have exercised willpower (in some sense) to keep playing for so long without food or sleep; the evolutionary hazard of self-control.</p>
    <p>Resisting any temptation takes conscious expenditure of an exhaustible supply of mental energy. It is not in fact <em>true</em> that we can “just say no”—not <em>just</em> say no, without cost to ourselves. Even humans who won the birth lottery for willpower or foresightfulness still pay a price to resist temptation. The price is just more easily paid.</p>
    <p>Our limited willpower evolved to deal with ancestral temptations; it may not operate well against enticements beyond anything known to hunter-gatherers. Even where we successfully resist a superstimulus, it seems plausible that the effort required would deplete willpower much faster than resisting ancestral temptations.</p>
    <p>Is public display of superstimuli a negative externality, even to the people who say no? Should we ban chocolate cookie ads, or storefronts that openly say “Ice Cream”?</p>
    <p>Just because a problem exists doesn’t show (without further justification and a substantial burden of proof) that the government can fix it. The regulator’s career incentive does not focus on products that combine low-grade consumer harm with addictive superstimuli; it focuses on products with failure modes spectacular enough to get into the newspaper. Conversely, just because the government may not be able to fix something, doesn’t mean it isn’t going wrong.</p>
    <p>I leave you with a final argument from fictional evidence: Simon Funk’s online novel After Life depicts (among other plot points) the planned extermination of biological <em>Homo sapiens</em>—not by marching robot armies, but by artificial children that are much cuter and sweeter and more fun to raise than real children. Perhaps the demographic collapse of advanced societies happens because the market supplies ever-more-tempting alternatives to having children, while the attractiveness of changing diapers remains constant over time. Where are the advertising billboards that say “Breed”? Who will pay professional image consultants to make arguing with sullen teenagers seem more alluring than a vacation in Tahiti?</p>
    <p>“In the end,” Simon Funk wrote, “the human species was simply marketed out of existence.”</p>
  </Chapter>;
}
