import React from "react";
import Chapter from "@/components/Chapter/Chapter";

export default function TheTragedyOfGroupSelectionism() {
  return <Chapter title={["The Tragedy of", "Group Selectionism"]}>


    <p><span className="dropCap">B</span>efore 1966, it was not unusual to see serious biologists advocating evolutionary hypotheses that we would now regard as magical thinking. These muddled notions played an important historical role in the development of later evolutionary theory, error calling forth correction; like the folly of English kings provoking into existence the Magna Carta and constitutional democracy.</p>
    <p>As an example of romance, Vero Wynne-Edwards, Warder Allee, and J. L. Brereton, among others, believed that predators would voluntarily restrain their breeding to avoid overpopulating their habitat and exhausting the prey population.</p>
    <p>But evolution does not open the floodgates to arbitrary purposes. You cannot explain a rattlesnake’s rattle by saying that it exists to benefit other animals who would otherwise be bitten. No outside Evolution Fairy decides when a gene <em>ought</em> to be promoted; the gene’s effect must somehow <em>directly cause</em> the gene to be more prevalent in the next generation. It’s clear why our human sense of aesthetics, witnessing a population crash of foxes who’ve eaten all the rabbits, cries “Something should’ve been done!” But how would a gene complex for <em>restraining reproduction</em>—of all things!—cause itself to become more frequent in the next generation?</p>
    <p>A human being designing a neat little toy ecology—for entertainment purposes, like a model railroad—might be annoyed if their painstakingly constructed fox and rabbit populations self-destructed by the foxes eating all the rabbits and then dying of starvation themselves. So the human would tinker with the toy ecology—a fox-breeding-restrainer is the obvious solution that leaps to our human minds—until the ecology looked nice and neat. Nature has no human, of course, but <em>that</em> needn’t stop us—now that we know what <em>we</em> want on <em>aesthetic</em> grounds, we just have to come up with a plausible argument that persuades Nature to want the <em>same</em> thing on <em>evolutionary</em> grounds.</p>
    <p>Obviously, selection on the level of the individual won’t produce individual restraint in breeding. Individuals who reproduce unrestrainedly will, naturally, produce more offspring than individuals who restrain themselves.</p>
    <p>(Individual selection will not produce <em>individual sacrifice of breeding opportunities</em>. Individual selection can certainly produce individuals who, after acquiring all available resources, use those resources to produce four big eggs instead of eight small eggs—<em>not</em> to conserve social resources, but because that is the <em>individual</em> sweet spot for (number of eggs)×(egg survival probability). This does not get rid of the commons problem.)</p>
    <p>But suppose that the species population was broken up into subpopulations, which were mostly isolated, and only occasionally interbred. Then, surely, subpopulations that restrained their breeding would be less likely to go extinct, and would send out more messengers, and create new colonies to reinhabit the territories of crashed populations.</p>
    <p>The problem with this scenario wasn’t that it was mathematically <em>impossible</em>. The problem was that it was <em>possible but very difficult</em>.</p>
    <p>The fundamental problem is that it’s not only restrained breeders who reap the benefits of restrained breeding. If some foxes refrain from spawning cubs who eat rabbits, then the uneaten rabbits don’t go to <em>only</em> cubs who carry the restrained-breeding adaptation. The unrestrained foxes, and their many more cubs, will happily eat any rabbits left unhunted. The only way the restraining gene can survive against this pressure, is if the benefits of restraint preferentially go to restrainers.</p>
    <p>Specifically, the requirement is <em>C/B &lt; FST</em> where <em>C</em> is the cost of altruism to the donor, <em>B</em> is the benefit of altruism to the recipient, and <em>FST</em> is the spatial structure of the population: the average <em>relatedness</em> between a randomly selected organism and its randomly selected neighbor, where a “neighbor” is any other fox who benefits from an altruistic fox’s restraint.<span class="footnote">David Sloan Wilson, “A Theory of Group Selection,” <em>Proceedings of the National Academy of Sciences of the United States of America</em> 72, no. 1 (1975): 143–146.</span></p>
    <p>So is the cost of restrained breeding sufficiently small, and the empirical benefit of less famine sufficiently large, compared to the empirical spatial structure of fox populations and rabbit populations, that the group selection argument can work?</p>
    <p>The math suggests this is pretty unlikely. In this simulation, for example, the cost to altruists is 3% of fitness, pure altruist groups have a fitness twice as great as pure selfish groups, the subpopulation size is 25, and 20% of all deaths are replaced with messengers from another group: the result is polymorphic for selfishness and altruism. If the subpopulation size is doubled to 50, selfishness is fixed; if the cost to altruists is increased to 6%, selfishness is fixed; if the altruistic benefit is decreased by half, selfishness is fixed or in large majority. Neighborhood-groups must be very small, with only around 5 members, for group selection to operate when the cost of altruism exceeds 10%. This doesn’t seem plausibly true of foxes restraining their breeding.</p>
    <p>You can guess by now, I think, that the group selectionists ultimately lost the scientific argument. The kicker was not the mathematical argument, but empirical observation: foxes <em>didn’t</em> restrain their breeding (I forget the exact species of dispute; it wasn’t foxes and rabbits), and indeed, predator-prey systems crash all the time. Group selectionism would later revive, somewhat, in drastically different form—mathematically speaking, there <em>is</em> neighborhood structure, which implies nonzero group selection pressure <em>not</em> necessarily capable of overcoming countervailing individual selection pressure, and if you don’t take it into account your math will be wrong, full stop. And evolved enforcement mechanisms (not originally postulated) change the game entirely. So why is this now-historical scientific dispute worthy material for <em>Overcoming Bias</em>?</p>
    <p>A decade after the controversy, a biologist had a fascinating idea. The mathematical conditions for group selection overcoming individual selection were too extreme to be found in Nature. Why not create them artificially, in the laboratory? Michael J. Wade proceeded to do just that, repeatedly selecting populations of insects for low numbers of adults per subpopulation.<span class="footnote">Michael J. Wade, “Group selections among laboratory populations of Tribolium,” <em>Proceedings of the National Academy of Sciences of the United States of America</em> 73, no. 12 (1976): 4604–4607, doi:10.1073/pnas.73.12.4604.</span> And what was the result? Did the insects restrain their breeding and live in quiet peace with enough food for all?</p>
    <p>No; the adults adapted to cannibalize eggs and larvae, especially female larvae.</p>
    <p><em>Of course</em> selecting for small subpopulation sizes would not select for individuals who restrained their <em>own</em> breeding; it would select for individuals who ate <em>other</em> individuals’ children. Especially the girls.</p>
    <p>Once you have that experimental result in hand—and it’s massively obvious in retrospect—then it suddenly becomes clear how the original group selectionists allowed romanticism, a human sense of aesthetics, to cloud their predictions of Nature.</p>
    <p>This is an archetypal example of a missed Third Alternative, resulting from a rationalization of a predetermined bottom line that produced a fake justification and then motivatedly stopped. The group selectionists didn’t start with clear, fresh minds, happen upon the idea of group selection, and <em>neutrally</em> extrapolate forward the probable outcome. They started out with the beautiful idea of fox populations voluntarily restraining their reproduction to what the rabbit population would bear, Nature in perfect harmony; then they searched for a reason why this would happen, and came up with the idea of group selection; then, since they knew what they <em>wanted</em> the outcome of group selection to be, they didn’t look for any <em>less</em> beautiful and aesthetic adaptations that group selection would be more likely to promote instead. If they’d <em>really</em> been trying to calmly and neutrally predict the result of selecting for small subpopulation sizes resistant to famine, they would have thought of cannibalizing other organisms’ children or some similarly “ugly” outcome—<em>long before</em> they imagined anything so evolutionarily outré as <em>individual restraint in breeding!</em></p>
    <p>This also illustrates the point I was trying to make in Einstein’s Arrogance: With large answer spaces, nearly all of the real work goes into promoting one possible answer to the point of being singled out for attention. If a hypothesis is improperly promoted to your attention—your sense of aesthetics suggests a beautiful way for Nature to be, and yet natural selection doesn’t involve an Evolution Fairy who shares your appreciation—then this alone may seal your doom, unless you can manage to clear your mind entirely and start over.</p>
    <p>In principle, the world’s stupidest person may say the Sun is shining, but that doesn’t make it dark out. Even if an answer is suggested by a lunatic on LSD, you should be able to neutrally calculate the evidence for and against, and if necessary, un-believe.</p>
    <p>In practice, the group selectionists were doomed because their bottom line was originally suggested by their sense of aesthetics, and Nature’s bottom line was produced by natural selection. These two processes had no principled reason for their outputs to correlate, and indeed they didn’t. All the furious argument afterward didn’t change that.</p>
    <p>If you start with your own desires for what Nature should do, consider Nature’s own observed reasons for doing things, and then rationalize an extremely persuasive argument for why Nature should produce your preferred outcome for Nature’s own reasons, then Nature, alas, <em>still</em> won’t listen. The universe has no mind and is not subject to clever political persuasion. You can argue all day why gravity should really make water flow _up_hill, and the water just ends up in the same place regardless. It’s like the universe plain isn’t listening. J. R. Molloy said: “Nature is the ultimate bigot, because it is obstinately and intolerantly devoted to its own prejudices and absolutely refuses to yield to the most persuasive rationalizations of humans.”</p>
    <p>I often recommend evolutionary biology to friends just because the modern field tries to train its students against rationalization, error calling forth correction. Physicists and electrical engineers don’t have to be carefully trained to avoid anthropomorphizing electrons, because electrons don’t exhibit mindish behaviors. Natural selection creates purposefulnesses which are alien to humans, and students of evolutionary theory are warned accordingly. It’s good training for any thinker, but it is <em>especially</em> important if you want to think clearly about other weird mindish processes that do not work like you do.</p>
  </Chapter>;
}
