import Chapter from "@/components/Chapter/Chapter";

export default function FailingToLearnFromHistory() {


  return <Chapter title={["Failing to Learn from History"]}>
    <p><span className="dropCap">O</span>nce upon a time, in my wild and reckless youth, when I knew not the Way of Bayes, I gave a Mysterious Answer to a mysterious-seeming question. Many failures occurred in sequence, but one mistake stands out as most critical: My younger self did not realize that <em>solving a mystery should make it feel less confusing</em>. I was trying to explain a Mysterious Phenomenon—which to me meant providing a cause for it, fitting it into an integrated model of reality. Why should this make the phenomenon less Mysterious, when that is its nature? I was trying to <em>explain</em> the Mysterious Phenomenon, not render it (by some impossible alchemy) into a mundane phenomenon, a phenomenon that wouldn’t even call out for an unusual explanation in the first place.</p>
    <p>As a Traditional Rationalist, I knew the historical tales of astrologers and astronomy, of alchemists and chemistry, of vitalists and biology. But the Mysterious Phenomenon was not like this. It was something <em>new</em>, something stranger, something more difficult, something that ordinary science had failed to explain for centuries—</p>
    <p>—as if stars and matter and life had not been mysteries for hundreds of years and thousands of years, from the dawn of human thought right up until science finally solved them—</p>
    <p>We learn about astronomy and chemistry and biology in school, and it seems to us that these matters have <em>always been</em> the proper realm of science, that they have <em>never been</em> mysterious. When science dares to challenge a new Great Puzzle, the children of that generation are skeptical, for they have never seen science explain something that <em>feels</em> mysterious to them. Science is only good for explaining <em>scientific</em> subjects, like stars and matter and life.</p>
    <p>I thought the lesson of history was that astrologers and alchemists and vitalists had an innate character flaw, a tendency toward mysterianism, which led them to come up with mysterious explanations for non-mysterious subjects. But surely, if a phenomenon really <em>was</em> very weird, a weird explanation might be in order?</p>
    <p>It was only afterward, when I began to see the mundane structure inside the mystery, that I realized whose shoes I was standing in. Only then did I realize how reasonable vitalism had seemed <em>at the time</em>, how <em>surprising</em> and <em>embarrassing</em> had been the universe’s reply of, “Life is mundane, and does not need a weird explanation.”</p>
    <p>We read history but we don’t <em>live</em> it, we don’t <em>experience</em> it. If only I had <em>personally</em> postulated astrological mysteries and then discovered Newtonian mechanics, postulated alchemical mysteries and then discovered chemistry, postulated vitalistic mysteries and then discovered biology. I would have thought of my Mysterious Answer and said to myself: <em>No way am I falling for that again</em>.</p>
  </Chapter>
}