import Chapter from "@/components/Chapter/Chapter";

export default function ScienceAsAttire() {


  return <Chapter title={["Science as Attire"]}>
    <p><span className="dropCap">T</span>he preview for the <em>X-Men</em> movie has a voice-over saying: “In every human being… there is the genetic code… for mutation.” Apparently you can acquire all sorts of neat abilities by mutation. The mutant Storm, for example, has the ability to throw lightning bolts.</p>
    <p>I beg you, dear reader, to consider the biological machinery necessary to generate electricity; the biological adaptations necessary to avoid being harmed by electricity; and the cognitive circuitry required for finely tuned control of lightning bolts. If we actually observed any organism acquiring these abilities in <em>one generation</em>, as the result of <em>mutation</em>, it would outright falsify the neo-Darwinian model of natural selection. It would be worse than finding rabbit fossils in the pre-Cambrian. If evolutionary theory could <em>actually</em> stretch to cover Storm, it would be able to explain anything, and we all know what that would imply.</p>
    <p>The <em>X-Men</em> comics use terms like “evolution,” “mutation,” and “genetic code,” purely to place themselves in what they conceive to be the <em>literary genre</em> of science. The part that scares me is wondering how many people, especially in the media, understand science <em>only</em> as a literary genre.</p>
    <p>I encounter people who very definitely believe in evolution, who sneer at the folly of creationists. And yet they have no idea of what the theory of evolutionary biology permits and prohibits. They’ll talk about “the next step in the evolution of humanity,” as if natural selection got here by following a plan. Or even worse, they’ll talk about something completely outside the domain of evolutionary biology, like an improved design for computer chips, or corporations splitting, or humans uploading themselves into computers, and they’ll call <em>that</em> “evolution.” If evolutionary biology could cover that, it could cover anything.</p>
    <p>Probably an actual majority of the people who <em>believe in</em> evolution use the phrase “because of evolution” because they want to be part of the scientific in-crowd—belief as scientific attire, like wearing a lab coat. If the scientific in-crowd instead used the phrase “because of intelligent design,” they would just as cheerfully use that instead—it would make no difference to their anticipation-controllers. Saying “because of evolution” instead of “because of intelligent design” does not, <em>for them</em>, prohibit Storm. Its only purpose, for them, is to identify with a tribe.</p>
    <p>I encounter people who are quite willing to entertain the notion of dumber-than-human Artificial Intelligence, or even mildly smarter-than-human Artificial Intelligence. Introduce the notion of strongly superhuman Artificial Intelligence, and they’ll suddenly decide it’s “pseudoscience.” It’s not that they think they have a theory of intelligence which lets them calculate a theoretical upper bound on the power of an optimization process. Rather, they associate strongly superhuman AI to the <em>literary genre</em> of apocalyptic literature; whereas an AI running a small corporation associates to the literary genre of <em>Wired</em> magazine. They aren’t speaking from within a model of cognition. They don’t realize they <em>need</em> a model. They don’t realize that science is <em>about</em> models. Their devastating critiques consist purely of <em>comparisons to apocalyptic literature</em>, rather than, say, known laws which prohibit such an outcome. They understand science <em>only</em> as a literary genre, or in-group to belong to. The attire doesn’t look to them like a lab coat; this isn’t the football team they’re cheering for.</p>
    <p>Is there any idea in science that you are <em>proud</em> of believing, though you do not use the belief professionally? You had best ask yourself which future experiences your belief <em>prohibits</em> from happening to you. That is the sum of what you have assimilated and made a true part of yourself. Anything else is probably passwords or attire.</p>
  </Chapter>
}